/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Public-exposure turbo. It reports explicit public and unencrypted evidence
 * without changing links, routes, or network settings.
 */

export const NETWORK_SAFETY_PUBLIC_EXPOSURE_TURBO_ID = 'network-safety.public-exposure';
export const NETWORK_SAFETY_PUBLIC_EXPOSURE_TURBO_VERSION = 1;
export const NETWORK_SAFETY_PUBLIC_EXPOSURE_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Public-exposure snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Public-exposure requires a system-facts snapshot'); if (!Array.isArray(snapshot.network)) throw new TypeError('Public-exposure snapshot requires a network list'); return snapshot; }
function requireTrigger(trigger) { if (!NETWORK_SAFETY_PUBLIC_EXPOSURE_TRIGGERS.includes(trigger)) throw new Error(`Unsupported public-exposure trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Public-exposure windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Public-exposure minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Public-exposure ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Public-exposure clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot) { const source = requireSnapshot(snapshot); const rows = source.network.filter(isRecord).map((link) => ({ key: `${text(link.name) || 'unnamed'}|${text(link.kind) || 'unknown'}`, public: typeof link.public === 'boolean' ? link.public : null, encrypted: typeof link.encrypted === 'boolean' ? link.encrypted : null })); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', linkCount: rows.length, exposureCount: 0, unknownEvidenceCount: rows.filter((row) => row.public === null || row.encrypted === null).length, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-network', linkCount: 0, exposureCount: 0, unknownEvidenceCount: 0, review: false }); const unknownEvidenceCount = rows.filter((row) => row.public === null || row.encrypted === null).length; if (unknownEvidenceCount > 0) return Object.freeze({ state: 'incomplete', linkCount: rows.length, exposureCount: rows.filter((row) => row.public === true && row.encrypted === false).length, unknownEvidenceCount, review: false }); const exposureCount = rows.filter((row) => row.public === true && row.encrypted === false).length; return Object.freeze({ state: 'observed', linkCount: rows.length, exposureCount, unknownEvidenceCount: 0, review: exposureCount > 0 }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, exposureSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-network')) return 'no-network'; if (incompleteCount > 0) return 'incomplete-evidence'; if (exposureSampleCount >= persistenceThreshold) return 'public-exposure-sustained'; if (exposureSampleCount > 0) return 'public-exposure-observed'; return 'no-public-exposure'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-public-exposure-evidence']); if (state === 'no-network') return Object.freeze(['no-network-exposure-review']); if (state === 'incomplete-evidence') return Object.freeze(['request-public-and-encryption-evidence']); if (state === 'public-exposure-sustained') return Object.freeze(['review-public-unencrypted-evidence-without-network-mutation']); if (state === 'public-exposure-observed') return Object.freeze(['observe-public-exposure-stability']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runNetworkSafetyPublicExposureTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Public-exposure samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = selected.map(aggregate); const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noNetworkCount = evidence.filter((item) => item.state === 'no-network').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const exposureSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const latest = evidence.at(-1) || Object.freeze({ linkCount: 0, exposureCount: 0, unknownEvidenceCount: 0 }); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, exposureSampleCount, requiredPersistence); return Object.freeze({ protocolVersion: 1, turbo: NETWORK_SAFETY_PUBLIC_EXPOSURE_TURBO_ID, turboVersion: NETWORK_SAFETY_PUBLIC_EXPOSURE_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, linkCount: latest.linkCount, exposureCount: latest.exposureCount, unknownEvidenceCount: latest.unknownEvidenceCount, observedCount, incompleteCount, noNetworkCount, exposureSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
