import { DRIVER_CAPABILITY_INVENTORY_DRIFT_TURBO_ID, runDriverCapabilityInventoryDriftTurbo } from '../pc/engines/driver-capability/turbos/inventory-drift/turbo.js';

const driver = (name, vendor = 'NVIDIA') => ({ name, vendor, version: '550', documented: true });
const facts = (drivers, environment = 'interactive') => ({ engine: 'system-facts', environment, drivers });

describe('driver-capability inventory-drift turbo', () => {
  test('detects sustained inventory drift', () => { const result = runDriverCapabilityInventoryDriftTurbo([facts([driver('GPU'), driver('Audio', 'AMD')]), facts([driver('GPU'), driver('Network', 'Intel')]), facts([driver('GPU'), driver('Display', 'AMD')])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(DRIVER_CAPABILITY_INVENTORY_DRIFT_TURBO_ID); expect(result.state).toBe('inventory-drift-sustained'); expect(result.addedCount).toBe(1); expect(result.removedCount).toBe(1); expect(result.inventoryChangeCount).toBe(2); expect(result.inventoryChangeSampleCount).toBe(2); expect(result.comparisonCount).toBe(2); expect(result.recommendations).toEqual(['review-driver-inventory-drift-without-change']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes stable, observed, empty, and incomplete evidence', () => { const observed = runDriverCapabilityInventoryDriftTurbo([facts([driver('GPU')]), facts([driver('GPU'), driver('Audio', 'AMD')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const stable = runDriverCapabilityInventoryDriftTurbo([facts([driver('GPU')]), facts([driver('GPU')])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runDriverCapabilityInventoryDriftTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runDriverCapabilityInventoryDriftTurbo([facts([driver('GPU')], 'unknown'), facts([{ name: 'GPU', version: '550' }])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('inventory-drift-observed'); expect(stable.state).toBe('stable-inventory'); expect(empty.state).toBe('no-drivers'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runDriverCapabilityInventoryDriftTurbo([facts([driver('GPU')]), facts([driver('Audio', 'AMD')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runDriverCapabilityInventoryDriftTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('stable-inventory'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runDriverCapabilityInventoryDriftTurbo()).toThrow(); expect(() => runDriverCapabilityInventoryDriftTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runDriverCapabilityInventoryDriftTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityInventoryDriftTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityInventoryDriftTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityInventoryDriftTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityInventoryDriftTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runDriverCapabilityInventoryDriftTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runDriverCapabilityInventoryDriftTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runDriverCapabilityInventoryDriftTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
