import { DRIVER_CAPABILITY_VERSION_CHURN_TURBO_ID, runDriverCapabilityVersionChurnTurbo } from '../pc/engines/driver-capability/turbos/version-churn/turbo.js';

const driver = (version = '550') => ({ name: 'GPU', vendor: 'NVIDIA', version, documented: true });
const facts = (drivers, environment = 'interactive') => ({ engine: 'system-facts', environment, drivers });

describe('driver-capability version-churn turbo', () => {
  test('detects sustained version churn', () => { const result = runDriverCapabilityVersionChurnTurbo([facts([driver('550')]), facts([driver('551')]), facts([driver('552')])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(DRIVER_CAPABILITY_VERSION_CHURN_TURBO_ID); expect(result.state).toBe('version-churn-sustained'); expect(result.versionChangeCount).toBe(1); expect(result.versionChangeSampleCount).toBe(2); expect(result.comparisonCount).toBe(2); expect(result.recommendations).toEqual(['review-driver-version-churn-without-change']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes stable, observed, empty, and incomplete evidence', () => { const observed = runDriverCapabilityVersionChurnTurbo([facts([driver('550')]), facts([driver('551')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const stable = runDriverCapabilityVersionChurnTurbo([facts([driver()]), facts([driver()])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runDriverCapabilityVersionChurnTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runDriverCapabilityVersionChurnTurbo([facts([driver()], 'unknown'), facts([{ version: '550', documented: true }])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('version-churn-observed'); expect(stable.state).toBe('stable-versions'); expect(empty.state).toBe('no-drivers'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runDriverCapabilityVersionChurnTurbo([facts([driver('550')]), facts([driver('551')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runDriverCapabilityVersionChurnTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('stable-versions'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runDriverCapabilityVersionChurnTurbo()).toThrow(); expect(() => runDriverCapabilityVersionChurnTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runDriverCapabilityVersionChurnTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityVersionChurnTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityVersionChurnTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityVersionChurnTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityVersionChurnTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runDriverCapabilityVersionChurnTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runDriverCapabilityVersionChurnTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runDriverCapabilityVersionChurnTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
