import { DRIVER_CAPABILITY_IDENTITY_COMPLETENESS_TURBO_ID, runDriverCapabilityIdentityCompletenessTurbo } from '../pc/engines/driver-capability/turbos/identity-completeness/turbo.js';

const driver = (overrides = {}) => ({ name: 'NVIDIA', vendor: 'NVIDIA', version: '550', documented: true, ...overrides });
const facts = (drivers, environment = 'interactive') => ({ engine: 'system-facts', environment, drivers });

describe('driver-capability identity-completeness turbo', () => {
  test('detects sustained missing identity fields', () => { const result = runDriverCapabilityIdentityCompletenessTurbo([facts([driver({ version: '' })]), facts([driver({ vendor: null })])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(DRIVER_CAPABILITY_IDENTITY_COMPLETENESS_TURBO_ID); expect(result.state).toBe('identity-gap-sustained'); expect(result.incompleteRowCount).toBe(1); expect(result.missingFieldCount).toBe(1); expect(result.recommendations).toEqual(['review-driver-identity-source-without-change']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes complete, observed gap, empty, and incomplete evidence', () => { const observed = runDriverCapabilityIdentityCompletenessTurbo([facts([driver({ version: '' })]), facts([driver()])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const complete = runDriverCapabilityIdentityCompletenessTurbo([facts([driver()]), facts([driver()])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runDriverCapabilityIdentityCompletenessTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runDriverCapabilityIdentityCompletenessTurbo([facts([driver()], 'unknown'), facts([driver({ documented: undefined })])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('identity-gap-observed'); expect(complete.state).toBe('complete-identity'); expect(empty.state).toBe('no-drivers'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runDriverCapabilityIdentityCompletenessTurbo([facts([driver({ name: '' })]), facts([driver()])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runDriverCapabilityIdentityCompletenessTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('complete-identity'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runDriverCapabilityIdentityCompletenessTurbo()).toThrow(); expect(() => runDriverCapabilityIdentityCompletenessTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runDriverCapabilityIdentityCompletenessTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityIdentityCompletenessTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityIdentityCompletenessTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityIdentityCompletenessTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runDriverCapabilityIdentityCompletenessTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runDriverCapabilityIdentityCompletenessTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runDriverCapabilityIdentityCompletenessTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runDriverCapabilityIdentityCompletenessTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
