import { NETWORK_SAFETY_TRUST_DRIFT_TURBO_ID, runNetworkSafetyTrustDriftTurbo } from '../pc/engines/network-safety/turbos/trust-drift/turbo.js';

const link = (name, trusted = true, kind = 'ethernet') => ({ name, kind, encrypted: true, trusted, public: false });
const facts = (network, environment = 'interactive') => ({ engine: 'system-facts', environment, network });

describe('network-safety trust-drift turbo', () => {
  test('detects sustained trust drift', () => { const result = runNetworkSafetyTrustDriftTurbo([facts([link('eth0', true)]), facts([link('eth0', false)]), facts([link('eth0', true)])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(NETWORK_SAFETY_TRUST_DRIFT_TURBO_ID); expect(result.state).toBe('trust-drift-sustained'); expect(result.trustChangeCount).toBe(1); expect(result.trustChangeSampleCount).toBe(2); expect(result.comparisonCount).toBe(2); expect(result.recommendations).toEqual(['review-trust-drift-without-network-mutation']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes stable, observed, empty, and incomplete evidence', () => { const observed = runNetworkSafetyTrustDriftTurbo([facts([link('eth0', true)]), facts([link('eth0', false)])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const stable = runNetworkSafetyTrustDriftTurbo([facts([link('eth0', true)]), facts([link('eth0', true)])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runNetworkSafetyTrustDriftTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runNetworkSafetyTrustDriftTurbo([facts([link('eth0', true)], 'unknown'), facts([{}])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('trust-drift-observed'); expect(stable.state).toBe('stable-trust'); expect(empty.state).toBe('no-network'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runNetworkSafetyTrustDriftTurbo([facts([link('eth0', true)]), facts([link('eth0', false)])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runNetworkSafetyTrustDriftTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('stable-trust'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runNetworkSafetyTrustDriftTurbo()).toThrow(); expect(() => runNetworkSafetyTrustDriftTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runNetworkSafetyTrustDriftTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyTrustDriftTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyTrustDriftTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyTrustDriftTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyTrustDriftTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runNetworkSafetyTrustDriftTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runNetworkSafetyTrustDriftTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runNetworkSafetyTrustDriftTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
