import { NETWORK_OBSERVATION_INTERFACE_INVENTORY_TURBO_ID, runNetworkObservationInterfaceInventoryTurbo } from '../pc/engines/network-observation/turbos/interface-inventory/turbo.js';

const link = (name, kind = 'ethernet') => ({ name, kind, state: 'up', defaultRoute: false, mesh: false });
const facts = (network, environment = 'interactive') => ({ engine: 'system-facts', environment, network });

describe('network-observation interface-inventory turbo', () => {
  test('detects sustained interface inventory drift', () => { const result = runNetworkObservationInterfaceInventoryTurbo([facts([link('eth0'), link('audio', 'virtual')]), facts([link('eth0'), link('wifi', 'wireless')]), facts([link('eth0'), link('loop', 'virtual')])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(NETWORK_OBSERVATION_INTERFACE_INVENTORY_TURBO_ID); expect(result.state).toBe('interface-drift-sustained'); expect(result.addedCount).toBe(1); expect(result.removedCount).toBe(1); expect(result.inventoryChangeCount).toBe(2); expect(result.inventoryChangeSampleCount).toBe(2); expect(result.comparisonCount).toBe(2); expect(result.recommendations).toEqual(['review-interface-inventory-drift-without-network-mutation']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes stable, observed, empty, and incomplete evidence', () => { const observed = runNetworkObservationInterfaceInventoryTurbo([facts([link('eth0')]), facts([link('eth0'), link('wifi', 'wireless')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const stable = runNetworkObservationInterfaceInventoryTurbo([facts([link('eth0')]), facts([link('eth0')])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runNetworkObservationInterfaceInventoryTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runNetworkObservationInterfaceInventoryTurbo([facts([link('eth0')], 'unknown'), facts([{ name: 'eth0' }])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('interface-drift-observed'); expect(stable.state).toBe('stable-interface-inventory'); expect(empty.state).toBe('no-network'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runNetworkObservationInterfaceInventoryTurbo([facts([link('eth0')]), facts([link('wifi', 'wireless')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runNetworkObservationInterfaceInventoryTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('stable-interface-inventory'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runNetworkObservationInterfaceInventoryTurbo()).toThrow(); expect(() => runNetworkObservationInterfaceInventoryTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runNetworkObservationInterfaceInventoryTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationInterfaceInventoryTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationInterfaceInventoryTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationInterfaceInventoryTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationInterfaceInventoryTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runNetworkObservationInterfaceInventoryTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runNetworkObservationInterfaceInventoryTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runNetworkObservationInterfaceInventoryTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
