import { NETWORK_SAFETY_ENCRYPTION_DRIFT_TURBO_ID, runNetworkSafetyEncryptionDriftTurbo } from '../pc/engines/network-safety/turbos/encryption-drift/turbo.js';

const link = (name, encrypted = true, kind = 'ethernet') => ({ name, kind, encrypted, trusted: true, public: false });
const facts = (network, environment = 'interactive') => ({ engine: 'system-facts', environment, network });

describe('network-safety encryption-drift turbo', () => {
  test('detects sustained encryption drift', () => { const result = runNetworkSafetyEncryptionDriftTurbo([facts([link('eth0', true)]), facts([link('eth0', false)]), facts([link('eth0', true)])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(NETWORK_SAFETY_ENCRYPTION_DRIFT_TURBO_ID); expect(result.state).toBe('encryption-drift-sustained'); expect(result.encryptionChangeCount).toBe(1); expect(result.encryptionChangeSampleCount).toBe(2); expect(result.comparisonCount).toBe(2); expect(result.recommendations).toEqual(['review-encryption-drift-without-network-mutation']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes stable, observed, empty, and incomplete evidence', () => { const observed = runNetworkSafetyEncryptionDriftTurbo([facts([link('eth0', true)]), facts([link('eth0', false)])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const stable = runNetworkSafetyEncryptionDriftTurbo([facts([link('eth0', true)]), facts([link('eth0', true)])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runNetworkSafetyEncryptionDriftTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runNetworkSafetyEncryptionDriftTurbo([facts([link('eth0', true)], 'unknown'), facts([{}])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('encryption-drift-observed'); expect(stable.state).toBe('stable-encryption'); expect(empty.state).toBe('no-network'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runNetworkSafetyEncryptionDriftTurbo([facts([link('eth0', true)]), facts([link('eth0', false)])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runNetworkSafetyEncryptionDriftTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('stable-encryption'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runNetworkSafetyEncryptionDriftTurbo()).toThrow(); expect(() => runNetworkSafetyEncryptionDriftTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runNetworkSafetyEncryptionDriftTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyEncryptionDriftTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyEncryptionDriftTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyEncryptionDriftTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyEncryptionDriftTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runNetworkSafetyEncryptionDriftTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runNetworkSafetyEncryptionDriftTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runNetworkSafetyEncryptionDriftTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
