import { NETWORK_SAFETY_PUBLIC_EXPOSURE_TURBO_ID, runNetworkSafetyPublicExposureTurbo } from '../pc/engines/network-safety/turbos/public-exposure/turbo.js';

const link = (name, publicLink = false, encrypted = true, kind = 'ethernet') => ({ name, kind, public: publicLink, encrypted, trusted: true });
const facts = (network, environment = 'interactive') => ({ engine: 'system-facts', environment, network });

describe('network-safety public-exposure turbo', () => {
  test('detects sustained public unencrypted exposure', () => { const result = runNetworkSafetyPublicExposureTurbo([facts([link('eth0', true, false)]), facts([link('eth0', true, false)]), facts([link('eth0', true, false)])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(NETWORK_SAFETY_PUBLIC_EXPOSURE_TURBO_ID); expect(result.state).toBe('public-exposure-sustained'); expect(result.exposureCount).toBe(1); expect(result.exposureSampleCount).toBe(3); expect(result.recommendations).toEqual(['review-public-unencrypted-evidence-without-network-mutation']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes no exposure, observed, empty, and incomplete evidence', () => { const observed = runNetworkSafetyPublicExposureTurbo([facts([link('eth0', true, false)]), facts([link('eth0')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const safe = runNetworkSafetyPublicExposureTurbo([facts([link('eth0')]), facts([link('eth0')])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runNetworkSafetyPublicExposureTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runNetworkSafetyPublicExposureTurbo([facts([link('eth0')], 'unknown'), facts([{}, { public: true }])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('public-exposure-observed'); expect(safe.state).toBe('no-public-exposure'); expect(empty.state).toBe('no-network'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runNetworkSafetyPublicExposureTurbo([facts([link('eth0', true, false)]), facts([link('eth0')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runNetworkSafetyPublicExposureTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('no-public-exposure'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runNetworkSafetyPublicExposureTurbo()).toThrow(); expect(() => runNetworkSafetyPublicExposureTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runNetworkSafetyPublicExposureTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyPublicExposureTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyPublicExposureTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyPublicExposureTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetyPublicExposureTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runNetworkSafetyPublicExposureTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runNetworkSafetyPublicExposureTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runNetworkSafetyPublicExposureTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
