import { NETWORK_OBSERVATION_ROUTE_STABILITY_TURBO_ID, runNetworkObservationRouteStabilityTurbo } from '../pc/engines/network-observation/turbos/route-stability/turbo.js';

const link = (name, defaultRoute = false, kind = 'ethernet') => ({ name, kind, state: 'up', defaultRoute, mesh: false });
const facts = (network, environment = 'interactive') => ({ engine: 'system-facts', environment, network });

describe('network-observation route-stability turbo', () => {
  test('detects sustained route drift', () => { const result = runNetworkObservationRouteStabilityTurbo([facts([link('eth0', true)]), facts([link('wlan0', true, 'wifi')]), facts([link('eth1', true)])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(NETWORK_OBSERVATION_ROUTE_STABILITY_TURBO_ID); expect(result.state).toBe('route-drift-sustained'); expect(result.routeChangeCount).toBe(1); expect(result.routeChangeSampleCount).toBe(2); expect(result.comparisonCount).toBe(2); expect(result.recommendations).toEqual(['review-route-drift-without-network-mutation']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes stable, observed, empty, and incomplete evidence', () => { const observed = runNetworkObservationRouteStabilityTurbo([facts([link('eth0', true)]), facts([link('wlan0', true, 'wifi')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const stable = runNetworkObservationRouteStabilityTurbo([facts([link('eth0', true)]), facts([link('eth0', true)])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runNetworkObservationRouteStabilityTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runNetworkObservationRouteStabilityTurbo([facts([link('eth0', true)], 'unknown'), facts([{ defaultRoute: true }])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('route-drift-observed'); expect(stable.state).toBe('stable-routes'); expect(empty.state).toBe('no-network'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runNetworkObservationRouteStabilityTurbo([facts([link('eth0', true)]), facts([link('wlan0', true, 'wifi')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runNetworkObservationRouteStabilityTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('stable-routes'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runNetworkObservationRouteStabilityTurbo()).toThrow(); expect(() => runNetworkObservationRouteStabilityTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runNetworkObservationRouteStabilityTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationRouteStabilityTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationRouteStabilityTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationRouteStabilityTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationRouteStabilityTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runNetworkObservationRouteStabilityTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runNetworkObservationRouteStabilityTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runNetworkObservationRouteStabilityTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
