import { NETWORK_OBSERVATION_LINK_HEALTH_TURBO_ID, runNetworkObservationLinkHealthTurbo } from '../pc/engines/network-observation/turbos/link-health/turbo.js';

const link = (name, state = 'up', kind = 'ethernet') => ({ name, kind, state, defaultRoute: false, mesh: false });
const facts = (network, environment = 'interactive') => ({ engine: 'system-facts', environment, network });

describe('network-observation link-health turbo', () => {
  test('detects sustained link-state drift', () => { const result = runNetworkObservationLinkHealthTurbo([facts([link('eth0', 'up')]), facts([link('eth0', 'degraded')]), facts([link('eth0', 'down')])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(NETWORK_OBSERVATION_LINK_HEALTH_TURBO_ID); expect(result.state).toBe('link-health-drift-sustained'); expect(result.stateChangeCount).toBe(1); expect(result.stateChangeSampleCount).toBe(2); expect(result.comparisonCount).toBe(2); expect(result.recommendations).toEqual(['review-link-state-drift-without-network-mutation']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes stable, observed, empty, and incomplete evidence', () => { const observed = runNetworkObservationLinkHealthTurbo([facts([link('eth0', 'up')]), facts([link('eth0', 'degraded')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const stable = runNetworkObservationLinkHealthTurbo([facts([link('eth0')]), facts([link('eth0')])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runNetworkObservationLinkHealthTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runNetworkObservationLinkHealthTurbo([facts([link('eth0')], 'unknown'), facts([{}])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('link-health-drift-observed'); expect(stable.state).toBe('stable-link-health'); expect(empty.state).toBe('no-network'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runNetworkObservationLinkHealthTurbo([facts([link('eth0', 'up')]), facts([link('eth0', 'down')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runNetworkObservationLinkHealthTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('stable-link-health'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runNetworkObservationLinkHealthTurbo()).toThrow(); expect(() => runNetworkObservationLinkHealthTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runNetworkObservationLinkHealthTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationLinkHealthTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationLinkHealthTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationLinkHealthTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationLinkHealthTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runNetworkObservationLinkHealthTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runNetworkObservationLinkHealthTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runNetworkObservationLinkHealthTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
