import { NETWORK_OBSERVATION_MESH_EVIDENCE_TURBO_ID, runNetworkObservationMeshEvidenceTurbo } from '../pc/engines/network-observation/turbos/mesh-evidence/turbo.js';

const link = (name, mesh = false, kind = 'ethernet') => ({ name, kind, state: 'up', defaultRoute: false, mesh });
const facts = (network, environment = 'interactive') => ({ engine: 'system-facts', environment, network });

describe('network-observation mesh-evidence turbo', () => {
  test('detects sustained mesh evidence drift', () => { const result = runNetworkObservationMeshEvidenceTurbo([facts([link('eth0', true)]), facts([link('wlan0', true, 'wifi')]), facts([link('eth1', true)])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(NETWORK_OBSERVATION_MESH_EVIDENCE_TURBO_ID); expect(result.state).toBe('mesh-drift-sustained'); expect(result.meshChangeCount).toBe(1); expect(result.meshChangeSampleCount).toBe(2); expect(result.comparisonCount).toBe(2); expect(result.recommendations).toEqual(['review-mesh-evidence-drift-without-network-mutation']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes stable, observed, empty, and incomplete evidence', () => { const observed = runNetworkObservationMeshEvidenceTurbo([facts([link('eth0', true)]), facts([link('eth0'), link('wlan0', true, 'wifi')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const stable = runNetworkObservationMeshEvidenceTurbo([facts([link('eth0', true)]), facts([link('eth0', true)])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runNetworkObservationMeshEvidenceTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runNetworkObservationMeshEvidenceTurbo([facts([link('eth0', true)], 'unknown'), facts([{}, { mesh: true }])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('mesh-drift-observed'); expect(stable.state).toBe('stable-mesh-evidence'); expect(empty.state).toBe('no-network'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runNetworkObservationMeshEvidenceTurbo([facts([link('eth0', true)]), facts([link('wlan0', true, 'wifi')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runNetworkObservationMeshEvidenceTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('stable-mesh-evidence'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runNetworkObservationMeshEvidenceTurbo()).toThrow(); expect(() => runNetworkObservationMeshEvidenceTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runNetworkObservationMeshEvidenceTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationMeshEvidenceTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationMeshEvidenceTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationMeshEvidenceTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkObservationMeshEvidenceTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runNetworkObservationMeshEvidenceTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runNetworkObservationMeshEvidenceTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runNetworkObservationMeshEvidenceTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
