import { NETWORK_SAFETY_SAFETY_EVIDENCE_TURBO_ID, runNetworkSafetySafetyEvidenceTurbo } from '../pc/engines/network-safety/turbos/safety-evidence/turbo.js';

const link = (name, values = {}, kind = 'ethernet') => ({ name, kind, trusted: true, encrypted: true, public: false, ...values });
const facts = (network, environment = 'interactive') => ({ engine: 'system-facts', environment, network });

describe('network-safety safety-evidence turbo', () => {
  test('detects sustained review risk', () => { const result = runNetworkSafetySafetyEvidenceTurbo([facts([link('eth0', { trusted: false })]), facts([link('eth0', { public: true, encrypted: false })]), facts([link('eth0', { trusted: false })])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(NETWORK_SAFETY_SAFETY_EVIDENCE_TURBO_ID); expect(result.state).toBe('review-risk-sustained'); expect(result.reviewCount).toBe(1); expect(result.reviewSampleCount).toBe(3); expect(result.recommendations).toEqual(['review-network-safety-evidence-without-network-mutation']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes review, unknown, observed-safe, empty, and incomplete evidence', () => { const review = runNetworkSafetySafetyEvidenceTurbo([facts([link('eth0', { trusted: false })]), facts([link('eth0')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const unknown = runNetworkSafetySafetyEvidenceTurbo([facts([{}]), facts([{}])], { trigger: 'system.facts.request', now: () => 0 }); const safe = runNetworkSafetySafetyEvidenceTurbo([facts([link('eth0')]), facts([link('eth0', { encrypted: false })])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runNetworkSafetySafetyEvidenceTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runNetworkSafetySafetyEvidenceTurbo([facts([link('eth0')], 'unknown'), facts([link('eth0')])], { trigger: 'health.interval', now: () => 0 }); expect(review.state).toBe('review-risk-observed'); expect(unknown.state).toBe('unknown-risk-evidence'); expect(safe.state).toBe('observed-safe-evidence'); expect(empty.state).toBe('no-network'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runNetworkSafetySafetyEvidenceTurbo([facts([link('eth0', { trusted: false })]), facts([link('eth0')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runNetworkSafetySafetyEvidenceTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('observed-safe-evidence'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runNetworkSafetySafetyEvidenceTurbo()).toThrow(); expect(() => runNetworkSafetySafetyEvidenceTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runNetworkSafetySafetyEvidenceTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetySafetyEvidenceTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetySafetyEvidenceTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetySafetyEvidenceTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runNetworkSafetySafetyEvidenceTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runNetworkSafetySafetyEvidenceTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runNetworkSafetySafetyEvidenceTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runNetworkSafetySafetyEvidenceTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
