import { ORGANIZATION_PREVIEW_ITEM_INVENTORY_TURBO_ID, runOrganizationPreviewItemInventoryTurbo } from '../pc/engines/organization-preview/turbos/item-inventory/turbo.js';

const item = (name) => ({ name, category: 'documents', proposal: 'preview', userOwned: false });
const facts = (items, environment = 'interactive') => ({ engine: 'system-facts', environment, organization: { items } });

describe('organization-preview item-inventory turbo', () => {
  test('detects sustained item inventory drift', () => { const result = runOrganizationPreviewItemInventoryTurbo([facts([item('a'), item('b')]), facts([item('a'), item('c')]), facts([item('a'), item('d')])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(ORGANIZATION_PREVIEW_ITEM_INVENTORY_TURBO_ID); expect(result.state).toBe('item-drift-sustained'); expect(result.addedCount).toBe(1); expect(result.removedCount).toBe(1); expect(result.inventoryChangeCount).toBe(2); expect(result.inventoryChangeSampleCount).toBe(2); expect(result.recommendations).toEqual(['review-item-inventory-drift-without-file-mutation']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes stable, observed, empty, and incomplete evidence', () => { const observed = runOrganizationPreviewItemInventoryTurbo([facts([item('a')]), facts([item('a'), item('b')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const stable = runOrganizationPreviewItemInventoryTurbo([facts([item('a')]), facts([item('a')])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runOrganizationPreviewItemInventoryTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runOrganizationPreviewItemInventoryTurbo([facts([item('a')], 'unknown'), facts([{}])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('item-drift-observed'); expect(stable.state).toBe('stable-item-inventory'); expect(empty.state).toBe('no-organization-preview'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runOrganizationPreviewItemInventoryTurbo([facts([item('a')]), facts([item('b')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runOrganizationPreviewItemInventoryTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('stable-item-inventory'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runOrganizationPreviewItemInventoryTurbo()).toThrow(); expect(() => runOrganizationPreviewItemInventoryTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runOrganizationPreviewItemInventoryTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewItemInventoryTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewItemInventoryTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewItemInventoryTurbo([{ engine: 'system-facts', environment: 'interactive' }], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewItemInventoryTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewItemInventoryTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runOrganizationPreviewItemInventoryTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runOrganizationPreviewItemInventoryTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runOrganizationPreviewItemInventoryTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
