import { ORGANIZATION_PREVIEW_PROPOSAL_DRIFT_TURBO_ID, runOrganizationPreviewProposalDriftTurbo } from '../pc/engines/organization-preview/turbos/proposal-drift/turbo.js';

const item = (name, proposal = 'documents/a') => ({ name, category: 'documents', proposal, userOwned: false });
const facts = (items, environment = 'interactive') => ({ engine: 'system-facts', environment, organization: { items } });

describe('organization-preview proposal-drift turbo', () => {
  test('detects sustained proposal drift', () => { const result = runOrganizationPreviewProposalDriftTurbo([facts([item('a', 'documents/a')]), facts([item('a', 'media/a')]), facts([item('a', 'projects/a')])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(ORGANIZATION_PREVIEW_PROPOSAL_DRIFT_TURBO_ID); expect(result.state).toBe('proposal-drift-sustained'); expect(result.proposalChangeCount).toBe(1); expect(result.proposalChangeSampleCount).toBe(2); expect(result.recommendations).toEqual(['review-proposal-drift-without-file-mutation']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes stable, observed, empty, and incomplete evidence', () => { const observed = runOrganizationPreviewProposalDriftTurbo([facts([item('a', 'documents/a')]), facts([item('a', 'media/a')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const stable = runOrganizationPreviewProposalDriftTurbo([facts([item('a')]), facts([item('a')])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runOrganizationPreviewProposalDriftTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runOrganizationPreviewProposalDriftTurbo([facts([item('a')], 'unknown'), facts([{}])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('proposal-drift-observed'); expect(stable.state).toBe('stable-proposals'); expect(empty.state).toBe('no-organization-preview'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runOrganizationPreviewProposalDriftTurbo([facts([item('a', 'documents/a')]), facts([item('a', 'media/a')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runOrganizationPreviewProposalDriftTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('stable-proposals'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runOrganizationPreviewProposalDriftTurbo()).toThrow(); expect(() => runOrganizationPreviewProposalDriftTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runOrganizationPreviewProposalDriftTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewProposalDriftTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewProposalDriftTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewProposalDriftTurbo([{ engine: 'system-facts', environment: 'interactive' }], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewProposalDriftTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewProposalDriftTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runOrganizationPreviewProposalDriftTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runOrganizationPreviewProposalDriftTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runOrganizationPreviewProposalDriftTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
