import { ORGANIZATION_PREVIEW_OWNERSHIP_REVIEW_TURBO_ID, runOrganizationPreviewOwnershipReviewTurbo } from '../pc/engines/organization-preview/turbos/ownership-review/turbo.js';

const item = (name, userOwned = false) => ({ name, category: 'documents', proposal: 'preview', userOwned });
const facts = (items, environment = 'interactive') => ({ engine: 'system-facts', environment, organization: { items } });

describe('organization-preview ownership-review turbo', () => {
  test('detects sustained user-owned review evidence', () => { const result = runOrganizationPreviewOwnershipReviewTurbo([facts([item('a', true)]), facts([item('a', true)]), facts([item('a', true)])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(ORGANIZATION_PREVIEW_OWNERSHIP_REVIEW_TURBO_ID); expect(result.state).toBe('ownership-review-sustained'); expect(result.userOwnedCount).toBe(1); expect(result.ownedSampleCount).toBe(3); expect(result.recommendations).toEqual(['request-explicit-organization-approval']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes no ownership, observed, empty, and incomplete evidence', () => { const observed = runOrganizationPreviewOwnershipReviewTurbo([facts([item('a', true)]), facts([item('a')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const none = runOrganizationPreviewOwnershipReviewTurbo([facts([item('a')]), facts([item('a')])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runOrganizationPreviewOwnershipReviewTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runOrganizationPreviewOwnershipReviewTurbo([facts([item('a')], 'unknown'), facts([{}])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('ownership-review-observed'); expect(none.state).toBe('no-user-owned-items'); expect(empty.state).toBe('no-organization-preview'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runOrganizationPreviewOwnershipReviewTurbo([facts([item('a', true)]), facts([item('a')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runOrganizationPreviewOwnershipReviewTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('no-user-owned-items'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runOrganizationPreviewOwnershipReviewTurbo()).toThrow(); expect(() => runOrganizationPreviewOwnershipReviewTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runOrganizationPreviewOwnershipReviewTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewOwnershipReviewTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewOwnershipReviewTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewOwnershipReviewTurbo([{ engine: 'system-facts', environment: 'interactive' }], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewOwnershipReviewTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewOwnershipReviewTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runOrganizationPreviewOwnershipReviewTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runOrganizationPreviewOwnershipReviewTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runOrganizationPreviewOwnershipReviewTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
