import { ORGANIZATION_PREVIEW_CATEGORY_DRIFT_TURBO_ID, runOrganizationPreviewCategoryDriftTurbo } from '../pc/engines/organization-preview/turbos/category-drift/turbo.js';

const item = (name, category = 'documents') => ({ name, category, proposal: 'preview', userOwned: false });
const facts = (items, environment = 'interactive') => ({ engine: 'system-facts', environment, organization: { items } });

describe('organization-preview category-drift turbo', () => {
  test('detects sustained category drift', () => { const result = runOrganizationPreviewCategoryDriftTurbo([facts([item('a', 'documents')]), facts([item('a', 'media')]), facts([item('a', 'projects')])], { trigger: 'workload.changed', minimumSamples: 2, persistenceThreshold: 2, now: () => 0 }); expect(result.turbo).toBe(ORGANIZATION_PREVIEW_CATEGORY_DRIFT_TURBO_ID); expect(result.state).toBe('category-drift-sustained'); expect(result.categoryChangeCount).toBe(1); expect(result.categoryChangeSampleCount).toBe(2); expect(result.comparisonCount).toBe(2); expect(result.recommendations).toEqual(['review-category-drift-without-file-mutation']); expect(Object.isFrozen(result)).toBe(true); });
  test('distinguishes stable, observed, empty, and incomplete evidence', () => { const observed = runOrganizationPreviewCategoryDriftTurbo([facts([item('a', 'documents')]), facts([item('a', 'media')])], { trigger: 'health.interval', persistenceThreshold: 2, now: () => 0 }); const stable = runOrganizationPreviewCategoryDriftTurbo([facts([item('a')]), facts([item('a')])], { trigger: 'system.facts.request', now: () => 0 }); const empty = runOrganizationPreviewCategoryDriftTurbo([facts([]), facts([])], { trigger: 'install.preflight', now: () => 0 }); const incomplete = runOrganizationPreviewCategoryDriftTurbo([facts([item('a')], 'unknown'), facts([{}, { category: 'other' }])], { trigger: 'health.interval', now: () => 0 }); expect(observed.state).toBe('category-drift-observed'); expect(stable.state).toBe('stable-categories'); expect(empty.state).toBe('no-organization-preview'); expect(incomplete.state).toBe('incomplete-evidence'); });
  test('bounds samples and reports insufficient evidence', () => { const bounded = runOrganizationPreviewCategoryDriftTurbo([facts([item('a', 'documents')]), facts([item('a', 'media')])], { trigger: 'system.facts.request', windowSize: 1, minimumSamples: 1, now: () => 0 }); const insufficient = runOrganizationPreviewCategoryDriftTurbo([], { trigger: 'install.preflight', now: () => 0 }); expect(bounded.sampleCount).toBe(1); expect(bounded.state).toBe('stable-categories'); expect(insufficient.state).toBe('insufficient-data'); expect(insufficient.confidence).toBe(0); });
  test('rejects invalid triggers, snapshots, bounds, and clocks', () => { expect(() => runOrganizationPreviewCategoryDriftTurbo()).toThrow(); expect(() => runOrganizationPreviewCategoryDriftTurbo([], { trigger: 'bad' })).toThrow(); expect(() => runOrganizationPreviewCategoryDriftTurbo('bad', { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewCategoryDriftTurbo([{}], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewCategoryDriftTurbo([null], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewCategoryDriftTurbo([{ engine: 'system-facts', environment: 'interactive' }], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewCategoryDriftTurbo([facts({})], { trigger: 'health.interval' })).toThrow(); expect(() => runOrganizationPreviewCategoryDriftTurbo([], { trigger: 'health.interval', windowSize: 0 })).toThrow(); expect(() => runOrganizationPreviewCategoryDriftTurbo([], { trigger: 'health.interval', windowSize: 1, minimumSamples: 2 })).toThrow(); expect(() => runOrganizationPreviewCategoryDriftTurbo([], { trigger: 'health.interval', persistenceThreshold: 0 })).toThrow(); expect(() => runOrganizationPreviewCategoryDriftTurbo([], { trigger: 'health.interval', now: () => Number.NaN })).toThrow(); });
});
