import { SAFETY_ADMIN_BOUNDARY_LIBRARY_ID, mergeSafetyAdminBoundaryReports,
  buildSafetyAdminBoundaryPlan, buildSafetyAdminBoundaryEnvelope,
  createSafetyAdminBoundaryLibrary } from '../pc/engines/safety-audit/turbos/admin-boundary/library.js';
function report(overrides = {}) { return { turbo: 'safety-audit.admin-boundary', state: 'normal-user-boundary', sampleCount: 4, minimumSamples: 2, persistenceThreshold: 2, observedCount: 4, unknownCount: 0, comparisonCount: 3, changeCount: 0, finalEnvironment: 'interactive', finalAdminRequired: false, confidence: 1, ...overrides }; }
describe('safety-audit admin-boundary library', () => {
  test('publishes identity and merges reports', () => { const merged = mergeSafetyAdminBoundaryReports([report(), report({ state: 'admin-boundary-drift-sustained', changeCount: 2, finalAdminRequired: true })]); expect(merged).toMatchObject({ library: SAFETY_ADMIN_BOUNDARY_LIBRARY_ID, reportCount: 2, state: 'admin-boundary-drift-sustained', changeCount: 2, finalAdminRequired: true }); expect(Object.isFrozen(merged)).toBe(true); });
  test('applies precedence and builds every plan', () => { expect(mergeSafetyAdminBoundaryReports([report({ state: 'admin-unknown' }), report({ state: 'admin-review' })]).state).toBe('admin-unknown'); const states = ['admin-unknown', 'observation-required', 'admin-boundary-drift-sustained', 'admin-boundary-drift-observed', 'admin-review', 'insufficient-data', 'normal-user-boundary']; const modes = ['evidence-bootstrap', 'evidence-bootstrap', 'admin-boundary-review', 'admin-boundary-observation', 'admin-review', 'sample-bootstrap', 'normal-user-observation']; states.forEach((state, index) => { expect(mergeSafetyAdminBoundaryReports([report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4, observedCount: state === 'admin-unknown' ? 0 : 4, unknownCount: state === 'observation-required' ? 1 : 0, finalAdminRequired: state === 'admin-review' })]).state).toBe(state); expect(buildSafetyAdminBoundaryPlan(report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4 }), 'interactive')).toMatchObject({ state, mode: modes[index] }); }); expect(buildSafetyAdminBoundaryPlan(report(), 'headless')).toMatchObject({ environment: 'headless', intervalMs: 10000 }); expect(buildSafetyAdminBoundaryPlan(report(), 'other')).toMatchObject({ environment: 'unknown', mode: 'profile-required' }); });
  test('builds envelopes and facades', () => { const envelope = buildSafetyAdminBoundaryEnvelope(report(), { trigger: 'health.interval', now: () => 0 }); expect(envelope).toMatchObject({ library: SAFETY_ADMIN_BOUNDARY_LIBRARY_ID, generatedAt: '1970-01-01T00:00:00.000Z' }); expect(Object.isFrozen(envelope)).toBe(true); expect(createSafetyAdminBoundaryLibrary().merge([]).state).toBe('insufficient-data'); });
  test('rejects malformed reports and envelope inputs', () => { expect(() => mergeSafetyAdminBoundaryReports(null)).toThrow('reports must be an array'); expect(() => mergeSafetyAdminBoundaryReports(new Array(65).fill(report()))).toThrow('at most 64'); expect(() => mergeSafetyAdminBoundaryReports([null])).toThrow('report must be an object'); expect(() => mergeSafetyAdminBoundaryReports([report({ turbo: 'other' })])).toThrow('requires an admin-boundary turbo report'); expect(() => mergeSafetyAdminBoundaryReports([report({ state: 'other' })])).toThrow('invalid state'); expect(() => mergeSafetyAdminBoundaryReports([report({ sampleCount: -1 })])).toThrow('sampleCount'); expect(() => mergeSafetyAdminBoundaryReports([report({ minimumSamples: 0 })])).toThrow('minimumSamples'); expect(() => mergeSafetyAdminBoundaryReports([report({ persistenceThreshold: 65 })])).toThrow('persistenceThreshold'); expect(() => mergeSafetyAdminBoundaryReports([report({ observedCount: -1 })])).toThrow('observed count'); expect(() => mergeSafetyAdminBoundaryReports([report({ finalEnvironment: 'other' })])).toThrow('finalEnvironment'); expect(() => mergeSafetyAdminBoundaryReports([report({ finalAdminRequired: 1 })])).toThrow('finalAdminRequired'); expect(() => mergeSafetyAdminBoundaryReports([report({ confidence: 2 })])).toThrow('confidence'); expect(() => buildSafetyAdminBoundaryEnvelope(report())).toThrow('trigger is required'); expect(() => buildSafetyAdminBoundaryEnvelope(report(), { trigger: '', now: () => 0 })).toThrow('trigger is required'); expect(() => buildSafetyAdminBoundaryEnvelope(report(), { trigger: 'health.interval', now: () => NaN })).toThrow('clock must return a number'); });
});
