import { SAFETY_APPROVAL_DRIFT_LIBRARY_ID, mergeSafetyApprovalDriftReports,
  buildSafetyApprovalDriftPlan, buildSafetyApprovalDriftEnvelope,
  createSafetyApprovalDriftLibrary } from '../pc/engines/safety-audit/turbos/approval-drift/library.js';
function report(overrides = {}) { return { turbo: 'safety-audit.approval-drift', state: 'approval-stable', sampleCount: 4, minimumSamples: 2, persistenceThreshold: 2, observedCount: 4, unknownCount: 0, comparisonCount: 3, changeCount: 0, finalEnvironment: 'interactive', finalApproval: true, confidence: 1, ...overrides }; }
describe('safety-audit approval-drift library', () => {
  test('publishes identity and merges reports', () => { const merged = mergeSafetyApprovalDriftReports([report(), report({ state: 'approval-drift-sustained', changeCount: 2, finalApproval: false })]); expect(merged).toMatchObject({ library: SAFETY_APPROVAL_DRIFT_LIBRARY_ID, reportCount: 2, state: 'approval-drift-sustained', changeCount: 2, finalApproval: false }); expect(Object.isFrozen(merged)).toBe(true); });
  test('applies precedence and builds every plan', () => { expect(mergeSafetyApprovalDriftReports([report({ state: 'approval-unknown' }), report({ state: 'approval-drift-sustained' })]).state).toBe('approval-unknown'); const states = ['approval-unknown', 'observation-required', 'approval-drift-sustained', 'approval-drift-observed', 'approval-required', 'insufficient-data', 'approval-stable']; const modes = ['evidence-bootstrap', 'evidence-bootstrap', 'approval-review', 'approval-observation', 'approval-request', 'sample-bootstrap', 'stable-observation']; states.forEach((state, index) => { expect(mergeSafetyApprovalDriftReports([report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4, observedCount: state === 'approval-unknown' ? 0 : 4, unknownCount: state === 'observation-required' ? 1 : 0, finalApproval: state === 'approval-required' ? false : true })]).state).toBe(state); expect(buildSafetyApprovalDriftPlan(report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4 }), 'interactive')).toMatchObject({ state, mode: modes[index] }); }); expect(buildSafetyApprovalDriftPlan(report(), 'headless')).toMatchObject({ environment: 'headless', intervalMs: 10000 }); expect(buildSafetyApprovalDriftPlan(report(), 'other')).toMatchObject({ environment: 'unknown', mode: 'profile-required' }); });
  test('builds envelopes and facades', () => { const envelope = buildSafetyApprovalDriftEnvelope(report(), { trigger: 'health.interval', now: () => 0 }); expect(envelope).toMatchObject({ library: SAFETY_APPROVAL_DRIFT_LIBRARY_ID, generatedAt: '1970-01-01T00:00:00.000Z' }); expect(Object.isFrozen(envelope)).toBe(true); expect(createSafetyApprovalDriftLibrary().merge([]).state).toBe('insufficient-data'); });
  test('rejects malformed reports and envelope inputs', () => { expect(() => mergeSafetyApprovalDriftReports(null)).toThrow('reports must be an array'); expect(() => mergeSafetyApprovalDriftReports(new Array(65).fill(report()))).toThrow('at most 64'); expect(() => mergeSafetyApprovalDriftReports([null])).toThrow('report must be an object'); expect(() => mergeSafetyApprovalDriftReports([report({ turbo: 'other' })])).toThrow('requires an approval-drift turbo report'); expect(() => mergeSafetyApprovalDriftReports([report({ state: 'other' })])).toThrow('invalid state'); expect(() => mergeSafetyApprovalDriftReports([report({ sampleCount: -1 })])).toThrow('sampleCount'); expect(() => mergeSafetyApprovalDriftReports([report({ minimumSamples: 0 })])).toThrow('minimumSamples'); expect(() => mergeSafetyApprovalDriftReports([report({ persistenceThreshold: 65 })])).toThrow('persistenceThreshold'); expect(() => mergeSafetyApprovalDriftReports([report({ observedCount: -1 })])).toThrow('observed count'); expect(() => mergeSafetyApprovalDriftReports([report({ finalEnvironment: 'other' })])).toThrow('finalEnvironment'); expect(() => mergeSafetyApprovalDriftReports([report({ finalApproval: 1 })])).toThrow('finalApproval'); expect(() => mergeSafetyApprovalDriftReports([report({ confidence: 2 })])).toThrow('confidence'); expect(() => buildSafetyApprovalDriftEnvelope(report())).toThrow('trigger is required'); expect(() => buildSafetyApprovalDriftEnvelope(report(), { trigger: '', now: () => 0 })).toThrow('trigger is required'); expect(() => buildSafetyApprovalDriftEnvelope(report(), { trigger: 'health.interval', now: () => NaN })).toThrow('clock must return a number'); });
});
