import { SAFETY_MUTATION_BOUNDARY_LIBRARY_ID, mergeSafetyMutationBoundaryReports,
  buildSafetyMutationBoundaryPlan, buildSafetyMutationBoundaryEnvelope,
  createSafetyMutationBoundaryLibrary } from '../pc/engines/safety-audit/turbos/mutation-boundary/library.js';
function report(overrides = {}) { return { turbo: 'safety-audit.mutation-boundary', state: 'safe-mutation-boundary', sampleCount: 4, minimumSamples: 2, persistenceThreshold: 2, observedCount: 4, unknownCount: 0, comparisonCount: 3, changeCount: 0, fileChangeCount: 0, networkChangeCount: 0, finalEnvironment: 'interactive', finalFileMutation: false, finalNetworkMutation: false, confidence: 1, ...overrides }; }
describe('safety-audit mutation-boundary library', () => {
  test('publishes identity and merges reports', () => { const merged = mergeSafetyMutationBoundaryReports([report(), report({ state: 'mutation-boundary-drift-sustained', changeCount: 2, fileChangeCount: 1, networkChangeCount: 1, finalNetworkMutation: true })]); expect(merged).toMatchObject({ library: SAFETY_MUTATION_BOUNDARY_LIBRARY_ID, reportCount: 2, state: 'mutation-boundary-drift-sustained', changeCount: 2, fileChangeCount: 1, networkChangeCount: 1, finalNetworkMutation: true }); expect(Object.isFrozen(merged)).toBe(true); });
  test('applies precedence and builds every plan', () => { expect(mergeSafetyMutationBoundaryReports([report({ state: 'mutation-unknown' }), report({ state: 'mutation-review' })]).state).toBe('mutation-unknown'); const states = ['mutation-unknown', 'observation-required', 'mutation-boundary-drift-sustained', 'mutation-boundary-drift-observed', 'mutation-review', 'insufficient-data', 'safe-mutation-boundary']; const modes = ['evidence-bootstrap', 'evidence-bootstrap', 'mutation-boundary-review', 'mutation-boundary-observation', 'mutation-review', 'sample-bootstrap', 'no-mutation-observation']; states.forEach((state, index) => { expect(mergeSafetyMutationBoundaryReports([report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4, observedCount: state === 'mutation-unknown' ? 0 : 4, unknownCount: state === 'observation-required' ? 1 : 0, finalFileMutation: state === 'mutation-review' })]).state).toBe(state); expect(buildSafetyMutationBoundaryPlan(report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4 }), 'interactive')).toMatchObject({ state, mode: modes[index] }); }); expect(buildSafetyMutationBoundaryPlan(report(), 'headless')).toMatchObject({ environment: 'headless', intervalMs: 10000 }); expect(buildSafetyMutationBoundaryPlan(report(), 'other')).toMatchObject({ environment: 'unknown', mode: 'profile-required' }); });
  test('builds envelopes and facades', () => { const envelope = buildSafetyMutationBoundaryEnvelope(report(), { trigger: 'health.interval', now: () => 0 }); expect(envelope).toMatchObject({ library: SAFETY_MUTATION_BOUNDARY_LIBRARY_ID, generatedAt: '1970-01-01T00:00:00.000Z' }); expect(Object.isFrozen(envelope)).toBe(true); expect(createSafetyMutationBoundaryLibrary().merge([]).state).toBe('insufficient-data'); });
  test('rejects malformed reports and envelope inputs', () => { expect(() => mergeSafetyMutationBoundaryReports(null)).toThrow('reports must be an array'); expect(() => mergeSafetyMutationBoundaryReports(new Array(65).fill(report()))).toThrow('at most 64'); expect(() => mergeSafetyMutationBoundaryReports([null])).toThrow('report must be an object'); expect(() => mergeSafetyMutationBoundaryReports([report({ turbo: 'other' })])).toThrow('requires a mutation-boundary turbo report'); expect(() => mergeSafetyMutationBoundaryReports([report({ state: 'other' })])).toThrow('invalid state'); expect(() => mergeSafetyMutationBoundaryReports([report({ sampleCount: -1 })])).toThrow('sampleCount'); expect(() => mergeSafetyMutationBoundaryReports([report({ minimumSamples: 0 })])).toThrow('minimumSamples'); expect(() => mergeSafetyMutationBoundaryReports([report({ persistenceThreshold: 65 })])).toThrow('persistenceThreshold'); expect(() => mergeSafetyMutationBoundaryReports([report({ observedCount: -1 })])).toThrow('observed count'); expect(() => mergeSafetyMutationBoundaryReports([report({ finalEnvironment: 'other' })])).toThrow('finalEnvironment'); expect(() => mergeSafetyMutationBoundaryReports([report({ finalFileMutation: 1 })])).toThrow('finalFileMutation'); expect(() => mergeSafetyMutationBoundaryReports([report({ finalNetworkMutation: 1 })])).toThrow('finalNetworkMutation'); expect(() => mergeSafetyMutationBoundaryReports([report({ confidence: 2 })])).toThrow('confidence'); expect(() => buildSafetyMutationBoundaryEnvelope(report())).toThrow('trigger is required'); expect(() => buildSafetyMutationBoundaryEnvelope(report(), { trigger: '', now: () => 0 })).toThrow('trigger is required'); expect(() => buildSafetyMutationBoundaryEnvelope(report(), { trigger: 'health.interval', now: () => NaN })).toThrow('clock must return a number'); });
});
