import { SAFETY_PROPOSAL_RISK_LIBRARY_ID, mergeSafetyProposalRiskReports,
  buildSafetyProposalRiskPlan, buildSafetyProposalRiskEnvelope,
  createSafetyProposalRiskLibrary } from '../pc/engines/safety-audit/turbos/proposal-risk/library.js';
function report(overrides = {}) { return { turbo: 'safety-audit.proposal-risk', state: 'no-proposal', sampleCount: 4, minimumSamples: 2, persistenceThreshold: 2, observedCount: 4, unknownCount: 0, comparisonCount: 3, changeCount: 0, actionChangeCount: 0, destructiveChangeCount: 0, finalEnvironment: 'interactive', finalActionCount: 0, finalDestructiveCount: 0, confidence: 1, ...overrides }; }
describe('safety-audit proposal-risk library', () => {
  test('publishes identity and merges reports', () => { const merged = mergeSafetyProposalRiskReports([report(), report({ state: 'destructive-risk-sustained', changeCount: 2, finalActionCount: 3, finalDestructiveCount: 2 })]); expect(merged).toMatchObject({ library: SAFETY_PROPOSAL_RISK_LIBRARY_ID, reportCount: 2, state: 'destructive-risk-sustained', changeCount: 2, finalActionCount: 3, finalDestructiveCount: 2 }); expect(Object.isFrozen(merged)).toBe(true); });
  test('applies precedence and builds every plan', () => { expect(mergeSafetyProposalRiskReports([report({ state: 'risk-unknown' }), report({ state: 'proposal-review' })]).state).toBe('risk-unknown'); const states = ['risk-unknown', 'observation-required', 'destructive-risk-sustained', 'destructive-risk-observed', 'destructive-proposal', 'proposal-review', 'insufficient-data', 'no-proposal']; const modes = ['evidence-bootstrap', 'evidence-bootstrap', 'destructive-risk-review', 'destructive-risk-observation', 'destructive-review', 'proposal-review', 'sample-bootstrap', 'no-action-observation']; states.forEach((state, index) => { expect(mergeSafetyProposalRiskReports([report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4, observedCount: state === 'risk-unknown' ? 0 : 4, unknownCount: state === 'observation-required' ? 1 : 0, finalActionCount: state === 'proposal-review' ? 1 : 0, finalDestructiveCount: state.includes('destructive') ? 1 : 0 })]).state).toBe(state); expect(buildSafetyProposalRiskPlan(report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4 }), 'interactive')).toMatchObject({ state, mode: modes[index] }); }); expect(buildSafetyProposalRiskPlan(report(), 'headless')).toMatchObject({ environment: 'headless', intervalMs: 10000 }); expect(buildSafetyProposalRiskPlan(report(), 'other')).toMatchObject({ environment: 'unknown', mode: 'profile-required' }); });
  test('builds envelopes and facades', () => { const envelope = buildSafetyProposalRiskEnvelope(report(), { trigger: 'health.interval', now: () => 0 }); expect(envelope).toMatchObject({ library: SAFETY_PROPOSAL_RISK_LIBRARY_ID, generatedAt: '1970-01-01T00:00:00.000Z' }); expect(Object.isFrozen(envelope)).toBe(true); expect(createSafetyProposalRiskLibrary().merge([]).state).toBe('insufficient-data'); });
  test('rejects malformed reports and envelope inputs', () => { expect(() => mergeSafetyProposalRiskReports(null)).toThrow('reports must be an array'); expect(() => mergeSafetyProposalRiskReports(new Array(65).fill(report()))).toThrow('at most 64'); expect(() => mergeSafetyProposalRiskReports([null])).toThrow('report must be an object'); expect(() => mergeSafetyProposalRiskReports([report({ turbo: 'other' })])).toThrow('requires a proposal-risk turbo report'); expect(() => mergeSafetyProposalRiskReports([report({ state: 'other' })])).toThrow('invalid state'); expect(() => mergeSafetyProposalRiskReports([report({ sampleCount: -1 })])).toThrow('sampleCount'); expect(() => mergeSafetyProposalRiskReports([report({ minimumSamples: 0 })])).toThrow('minimumSamples'); expect(() => mergeSafetyProposalRiskReports([report({ persistenceThreshold: 65 })])).toThrow('persistenceThreshold'); expect(() => mergeSafetyProposalRiskReports([report({ observedCount: -1 })])).toThrow('observed count'); expect(() => mergeSafetyProposalRiskReports([report({ finalActionCount: -1 })])).toThrow('finalActionCount'); expect(() => mergeSafetyProposalRiskReports([report({ finalDestructiveCount: -1 })])).toThrow('finalDestructiveCount'); expect(() => mergeSafetyProposalRiskReports([report({ finalEnvironment: 'other' })])).toThrow('finalEnvironment'); expect(() => mergeSafetyProposalRiskReports([report({ confidence: 2 })])).toThrow('confidence'); expect(() => buildSafetyProposalRiskEnvelope(report())).toThrow('trigger is required'); expect(() => buildSafetyProposalRiskEnvelope(report(), { trigger: '', now: () => 0 })).toThrow('trigger is required'); expect(() => buildSafetyProposalRiskEnvelope(report(), { trigger: 'health.interval', now: () => NaN })).toThrow('clock must return a number'); });
});
