import { WORKLOAD_DECLARATION_STABILITY_LIBRARY_ID, mergeWorkloadDeclarationStabilityReports,
  buildWorkloadDeclarationStabilityPlan, buildWorkloadDeclarationStabilityEnvelope,
  createWorkloadDeclarationStabilityLibrary } from '../pc/engines/workload-profile/turbos/declaration-stability/library.js';
function report(overrides = {}) { return { turbo: 'workload-profile.declaration-stability', state: 'stable-declaration', sampleCount: 4, minimumSamples: 2, persistenceThreshold: 2, observedCount: 4, unknownCount: 0, comparisonCount: 3, changeCount: 0, declarationChangeCount: 0, interactiveChangeCount: 0, finalEnvironment: 'interactive', finalDeclared: true, finalInteractive: true, confidence: 1, ...overrides }; }
describe('workload-profile declaration-stability library', () => {
  test('publishes identity and merges reports', () => { const merged = mergeWorkloadDeclarationStabilityReports([report(), report({ state: 'declaration-drift-sustained', changeCount: 2, declarationChangeCount: 2, finalDeclared: false })]); expect(merged).toMatchObject({ library: WORKLOAD_DECLARATION_STABILITY_LIBRARY_ID, reportCount: 2, state: 'declaration-drift-sustained', changeCount: 2, finalDeclared: false }); expect(Object.isFrozen(merged)).toBe(true); });
  test('applies precedence and builds all plans', () => {
    expect(mergeWorkloadDeclarationStabilityReports([report({ state: 'declaration-unknown' }), report({ state: 'declaration-drift-sustained' })]).state).toBe('declaration-unknown');
    const states = ['declaration-unknown', 'observation-required', 'declaration-drift-sustained', 'declaration-drift-observed', 'declaration-required', 'insufficient-data', 'stable-declaration']; const modes = ['evidence-bootstrap', 'evidence-bootstrap', 'declaration-review', 'declaration-observation', 'declaration-request', 'sample-bootstrap', 'stable-observation'];
    states.forEach((state, index) => { expect(mergeWorkloadDeclarationStabilityReports([report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4, observedCount: state === 'declaration-unknown' ? 0 : 4, unknownCount: state === 'observation-required' ? 1 : 0, finalDeclared: state === 'declaration-required' ? false : true })]).state).toBe(state); expect(buildWorkloadDeclarationStabilityPlan(report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4 }), 'interactive')).toMatchObject({ state, mode: modes[index] }); });
    expect(buildWorkloadDeclarationStabilityPlan(report(), 'headless')).toMatchObject({ environment: 'headless', intervalMs: 10000 }); expect(buildWorkloadDeclarationStabilityPlan(report(), 'other')).toMatchObject({ environment: 'unknown', mode: 'profile-required' });
  });
  test('builds envelopes and facades', () => { const envelope = buildWorkloadDeclarationStabilityEnvelope(report(), { trigger: 'health.interval', now: () => 0 }); expect(envelope).toMatchObject({ library: WORKLOAD_DECLARATION_STABILITY_LIBRARY_ID, generatedAt: '1970-01-01T00:00:00.000Z' }); expect(Object.isFrozen(envelope)).toBe(true); expect(createWorkloadDeclarationStabilityLibrary().merge([]).state).toBe('insufficient-data'); });
  test('rejects malformed reports and envelope inputs', () => { expect(() => mergeWorkloadDeclarationStabilityReports(null)).toThrow('reports must be an array'); expect(() => mergeWorkloadDeclarationStabilityReports(new Array(65).fill(report()))).toThrow('at most 64'); expect(() => mergeWorkloadDeclarationStabilityReports([null])).toThrow('report must be an object'); expect(() => mergeWorkloadDeclarationStabilityReports([report({ turbo: 'other' })])).toThrow('requires a declaration-stability turbo report'); expect(() => mergeWorkloadDeclarationStabilityReports([report({ state: 'other' })])).toThrow('invalid state'); expect(() => mergeWorkloadDeclarationStabilityReports([report({ sampleCount: -1 })])).toThrow('sampleCount'); expect(() => mergeWorkloadDeclarationStabilityReports([report({ minimumSamples: 0 })])).toThrow('minimumSamples'); expect(() => mergeWorkloadDeclarationStabilityReports([report({ persistenceThreshold: 65 })])).toThrow('persistenceThreshold'); expect(() => mergeWorkloadDeclarationStabilityReports([report({ observedCount: -1 })])).toThrow('observed count'); expect(() => mergeWorkloadDeclarationStabilityReports([report({ finalEnvironment: 'other' })])).toThrow('finalEnvironment'); expect(() => mergeWorkloadDeclarationStabilityReports([report({ finalDeclared: 1 })])).toThrow('finalDeclared'); expect(() => mergeWorkloadDeclarationStabilityReports([report({ finalInteractive: 1 })])).toThrow('finalInteractive'); expect(() => mergeWorkloadDeclarationStabilityReports([report({ confidence: 2 })])).toThrow('confidence'); expect(() => buildWorkloadDeclarationStabilityEnvelope(report())).toThrow('trigger is required'); expect(() => buildWorkloadDeclarationStabilityEnvelope(report(), { trigger: '', now: () => 0 })).toThrow('trigger is required'); expect(() => buildWorkloadDeclarationStabilityEnvelope(report(), { trigger: 'health.interval', now: () => NaN })).toThrow('clock must return a number'); });
});
