import { WORKLOAD_ENVIRONMENT_BOUNDARY_LIBRARY_ID, mergeWorkloadEnvironmentBoundaryReports,
  buildWorkloadEnvironmentBoundaryPlan, buildWorkloadEnvironmentBoundaryEnvelope,
  createWorkloadEnvironmentBoundaryLibrary } from '../pc/engines/workload-profile/turbos/environment-boundary/library.js';
function report(overrides = {}) { return { turbo: 'workload-profile.environment-boundary', state: 'interactive-boundary', sampleCount: 4, minimumSamples: 2, persistenceThreshold: 2, observedCount: 4, unknownCount: 0, comparisonCount: 3, changeCount: 0, finalEnvironment: 'interactive', confidence: 1, ...overrides }; }
describe('workload-profile environment-boundary library', () => {
  test('publishes identity and merges reports', () => { const merged = mergeWorkloadEnvironmentBoundaryReports([report(), report({ state: 'headless-boundary', finalEnvironment: 'headless' })]); expect(merged).toMatchObject({ library: WORKLOAD_ENVIRONMENT_BOUNDARY_LIBRARY_ID, reportCount: 2, state: 'headless-boundary', finalEnvironment: 'headless' }); expect(Object.isFrozen(merged)).toBe(true); });
  test('applies precedence and builds every plan mode', () => {
    expect(mergeWorkloadEnvironmentBoundaryReports([report({ state: 'profile-required' }), report({ state: 'headless-boundary' })]).state).toBe('profile-required');
    const states = ['profile-required', 'observation-required', 'environment-drift-sustained', 'environment-drift-observed', 'headless-boundary', 'insufficient-data', 'interactive-boundary']; const modes = ['profile-required', 'evidence-bootstrap', 'boundary-review', 'boundary-observation', 'headless-observation', 'sample-bootstrap', 'interactive-observation'];
    states.forEach((state, index) => { expect(mergeWorkloadEnvironmentBoundaryReports([report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4, observedCount: state === 'profile-required' ? 0 : 4, unknownCount: state === 'observation-required' ? 1 : 0, finalEnvironment: state === 'headless-boundary' ? 'headless' : 'interactive' })]).state).toBe(state); expect(buildWorkloadEnvironmentBoundaryPlan(report({ state, sampleCount: state === 'insufficient-data' ? 0 : 4, finalEnvironment: state === 'headless-boundary' ? 'headless' : 'interactive' }), 'interactive')).toMatchObject({ state, mode: modes[index] }); });
    expect(buildWorkloadEnvironmentBoundaryPlan(report(), 'headless')).toMatchObject({ environment: 'headless', intervalMs: 10000 }); expect(buildWorkloadEnvironmentBoundaryPlan(report(), 'other')).toMatchObject({ environment: 'unknown', mode: 'profile-required' });
  });
  test('builds envelopes and facades', () => { const envelope = buildWorkloadEnvironmentBoundaryEnvelope(report(), { trigger: 'health.interval', now: () => 0 }); expect(envelope).toMatchObject({ library: WORKLOAD_ENVIRONMENT_BOUNDARY_LIBRARY_ID, generatedAt: '1970-01-01T00:00:00.000Z' }); expect(Object.isFrozen(envelope)).toBe(true); expect(createWorkloadEnvironmentBoundaryLibrary().merge([]).state).toBe('insufficient-data'); });
  test('rejects malformed reports and envelope inputs', () => {
    expect(() => mergeWorkloadEnvironmentBoundaryReports(null)).toThrow('reports must be an array'); expect(() => mergeWorkloadEnvironmentBoundaryReports(new Array(65).fill(report()))).toThrow('at most 64'); expect(() => mergeWorkloadEnvironmentBoundaryReports([null])).toThrow('report must be an object'); expect(() => mergeWorkloadEnvironmentBoundaryReports([report({ turbo: 'other' })])).toThrow('requires an environment-boundary turbo report'); expect(() => mergeWorkloadEnvironmentBoundaryReports([report({ state: 'other' })])).toThrow('invalid state');
    expect(() => mergeWorkloadEnvironmentBoundaryReports([report({ sampleCount: -1 })])).toThrow('sampleCount'); expect(() => mergeWorkloadEnvironmentBoundaryReports([report({ minimumSamples: 0 })])).toThrow('minimumSamples'); expect(() => mergeWorkloadEnvironmentBoundaryReports([report({ persistenceThreshold: 65 })])).toThrow('persistenceThreshold'); expect(() => mergeWorkloadEnvironmentBoundaryReports([report({ observedCount: -1 })])).toThrow('observed count'); expect(() => mergeWorkloadEnvironmentBoundaryReports([report({ finalEnvironment: 'other' })])).toThrow('finalEnvironment'); expect(() => mergeWorkloadEnvironmentBoundaryReports([report({ confidence: 2 })])).toThrow('confidence');
    expect(() => buildWorkloadEnvironmentBoundaryEnvelope(report())).toThrow('trigger is required'); expect(() => buildWorkloadEnvironmentBoundaryEnvelope(report(), { trigger: '', now: () => 0 })).toThrow('trigger is required'); expect(() => buildWorkloadEnvironmentBoundaryEnvelope(report(), { trigger: 'health.interval', now: () => NaN })).toThrow('clock must return a number');
  });
});
