/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Dedicated throughput-skew library. It validates, aggregates, and plans
 * read/write balance reports without importing the turbo or changing disks.
 */

export const DISK_IO_THROUGHPUT_SKEW_LIBRARY_ID = 'disk-io.throughput-skew.library';
export const DISK_IO_THROUGHPUT_SKEW_LIBRARY_VERSION = 1;
const STATES = Object.freeze(['throughput-skew-sustained', 'throughput-skew-observed', 'balanced-throughput', 'no-disks', 'incomplete-throughput-evidence', 'insufficient-data']);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function requireSampleCount(report, field, label) { if (!Number.isInteger(report[field]) || report[field] < 0 || report[field] > report.sampleCount) throw new RangeError(`Throughput-skew library report ${label} must fit inside sampleCount`); return report[field]; }
function requireReport(report) {
  if (!isRecord(report)) throw new TypeError('Throughput-skew library report must be an object'); if (report.turbo !== 'disk-io.throughput-skew') throw new Error('Throughput-skew library requires a throughput-skew turbo report'); if (!STATES.includes(report.state)) throw new Error('Throughput-skew library report has an invalid state');
  if (!Number.isInteger(report.sampleCount) || report.sampleCount < 0 || report.sampleCount > 64) throw new RangeError('Throughput-skew library report sampleCount must be from 0 to 64'); if (!Number.isInteger(report.minimumSamples) || report.minimumSamples < 1 || report.minimumSamples > 64) throw new RangeError('Throughput-skew library minimumSamples must be from 1 to 64'); if (!Number.isFinite(report.skewThreshold) || report.skewThreshold < 0 || report.skewThreshold > 100) throw new RangeError('Throughput-skew library skewThreshold must be between 0 and 100'); if (!Number.isInteger(report.persistenceThreshold) || report.persistenceThreshold < 1 || report.persistenceThreshold > 64) throw new RangeError('Throughput-skew library persistenceThreshold must be from 1 to 64');
  for (const [field, label] of [['observedCount', 'observed count'], ['incompleteCount', 'incomplete count'], ['noDiskCount', 'no-disk count'], ['skewSampleCount', 'skew sample count']]) requireSampleCount(report, field, label); if (!Number.isInteger(report.diskCount) || report.diskCount < 0 || report.diskCount > 4096) throw new RangeError('Throughput-skew library diskCount must be from 0 to 4096'); if (report.maximumSkewPercent !== null && (!Number.isFinite(report.maximumSkewPercent) || report.maximumSkewPercent < 0 || report.maximumSkewPercent > 100)) throw new RangeError('Throughput-skew library maximumSkewPercent must be null or from 0 to 100'); if (!Number.isFinite(report.confidence) || report.confidence < 0 || report.confidence > 1) throw new RangeError('Throughput-skew library confidence must be between 0 and 1'); return report;
}
function requireReports(reports) { if (!Array.isArray(reports)) throw new TypeError('Throughput-skew library reports must be an array'); if (reports.length > 64) throw new RangeError('Throughput-skew library accepts at most 64 reports'); return Object.freeze(reports.map(requireReport)); }
function mergedState(reports) { if (reports.length === 0) return 'insufficient-data'; if (reports.some((report) => report.state === 'no-disks')) return 'no-disks'; if (reports.some((report) => report.state === 'incomplete-throughput-evidence')) return 'incomplete-throughput-evidence'; if (reports.some((report) => report.state === 'throughput-skew-sustained')) return 'throughput-skew-sustained'; if (reports.some((report) => report.state === 'throughput-skew-observed')) return 'throughput-skew-observed'; if (reports.every((report) => report.state === 'insufficient-data')) return 'insufficient-data'; return 'balanced-throughput'; }
function mergedConfidence(reports) { if (reports.length === 0) return 0; const samples = reports.reduce((sum, report) => sum + report.sampleCount, 0); if (samples === 0) return 0; return Math.round((reports.reduce((sum, report) => sum + report.observedCount, 0) / samples) * 10000) / 10000; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-throughput-samples']); if (state === 'no-disks') return Object.freeze(['no-disk-io-review']); if (state === 'incomplete-throughput-evidence') return Object.freeze(['request-throughput-observation']); if (state === 'throughput-skew-sustained') return Object.freeze(['review-read-write-contention', 'hold-queue-policy-change']); if (state === 'throughput-skew-observed') return Object.freeze(['observe-throughput-balance']); return Object.freeze(['no-change']); }
function environmentOf(environment) { return ENVIRONMENTS.includes(environment) ? environment : 'unknown'; }
function planMode(state, environment) { if (environment === 'unknown') return 'profile-required'; if (state === 'throughput-skew-sustained') return 'throughput-skew-review'; if (state === 'throughput-skew-observed') return 'throughput-skew-observation'; if (state === 'no-disks') return 'no-disk-observation'; if (state === 'incomplete-throughput-evidence') return 'evidence-bootstrap'; if (state === 'insufficient-data') return 'sample-bootstrap'; return 'balanced-throughput-observation'; }
function intervalFor(state, environment) { if (state === 'throughput-skew-sustained') return 750; if (state === 'throughput-skew-observed') return 1000; if (state === 'no-disks') return 10000; if (state === 'incomplete-throughput-evidence' || state === 'insufficient-data') return 1500; return environment === 'headless' ? 10000 : 5000; }
function latest(reports) { return reports.at(-1) || { diskCount: 0, maximumSkewPercent: null }; }
export function mergeDiskIoThroughputSkewReports(reports) { const validated = requireReports(reports); const state = mergedState(validated); const last = latest(validated); return Object.freeze({ library: DISK_IO_THROUGHPUT_SKEW_LIBRARY_ID, libraryVersion: DISK_IO_THROUGHPUT_SKEW_LIBRARY_VERSION, reportCount: validated.length, state, sampleCount: validated.reduce((sum, report) => sum + report.sampleCount, 0), diskCount: last.diskCount, maximumSkewPercent: last.maximumSkewPercent, observedCount: validated.reduce((sum, report) => sum + report.observedCount, 0), incompleteCount: validated.reduce((sum, report) => sum + report.incompleteCount, 0), noDiskCount: validated.reduce((sum, report) => sum + report.noDiskCount, 0), skewSampleCount: validated.reduce((sum, report) => sum + report.skewSampleCount, 0), confidence: mergedConfidence(validated), recommendations: recommendations(state) }); }
export function buildDiskIoThroughputSkewPlan(report, environment) { const validated = requireReport(report); const normalizedEnvironment = environmentOf(environment); return Object.freeze({ library: DISK_IO_THROUGHPUT_SKEW_LIBRARY_ID, environment: normalizedEnvironment, mode: planMode(validated.state, normalizedEnvironment), intervalMs: intervalFor(validated.state, normalizedEnvironment), state: validated.state, confidence: validated.sampleCount === 0 ? 0 : Math.round((validated.observedCount / validated.sampleCount) * 10000) / 10000 }); }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Throughput-skew library clock must return a number'); return timestamp; }
export function buildDiskIoThroughputSkewEnvelope(report, { trigger, now = Date.now } = {}) { if (typeof trigger !== 'string' || trigger.length === 0) throw new TypeError('Throughput-skew library trigger is required'); return Object.freeze({ library: DISK_IO_THROUGHPUT_SKEW_LIBRARY_ID, libraryVersion: DISK_IO_THROUGHPUT_SKEW_LIBRARY_VERSION, trigger, generatedAt: new Date(requireClock(now)).toISOString(), report: requireReport(report) }); }
export function createDiskIoThroughputSkewLibrary() { return Object.freeze({ id: DISK_IO_THROUGHPUT_SKEW_LIBRARY_ID, version: DISK_IO_THROUGHPUT_SKEW_LIBRARY_VERSION, merge: mergeDiskIoThroughputSkewReports, plan: buildDiskIoThroughputSkewPlan, envelope: buildDiskIoThroughputSkewEnvelope }); }
