/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Dedicated workload-conflict library for bounded contention evidence.
 */

export const WORKSTATION_WORKLOAD_CONFLICT_LIBRARY_ID = 'workstation-health.workload-conflict.library';
export const WORKSTATION_WORKLOAD_CONFLICT_LIBRARY_VERSION = 1;
const STATES = Object.freeze(['insufficient-data', 'observation-required', 'conflict-observed', 'no-conflict']);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function requireReport(report) { if (!isRecord(report)) throw new TypeError('Workload-conflict library report must be an object'); if (report.turbo !== 'workstation-health.workload-conflict') throw new Error('Workload-conflict library requires a workload-conflict turbo report'); if (!STATES.includes(report.state)) throw new Error('Workload-conflict library report has an invalid state'); if (!Number.isFinite(report.confidence) || report.confidence < 0 || report.confidence > 1) throw new RangeError('Workload-conflict library confidence must be between 0 and 1'); return report; }
function reportsOf(reports) { if (!Array.isArray(reports)) throw new TypeError('Workload-conflict library reports must be an array'); if (reports.length > 64) throw new RangeError('Workload-conflict library accepts at most 64 reports'); return Object.freeze(reports.map(requireReport)); }
function stateOf(reports) { if (!reports.length) return 'insufficient-data'; if (reports.some((report) => report.state === 'observation-required')) return 'observation-required'; if (reports.some((report) => report.state === 'conflict-observed')) return 'conflict-observed'; if (reports.every((report) => report.state === 'insufficient-data')) return 'insufficient-data'; return 'no-conflict'; }
function recommendations(state) { if (state === 'conflict-observed') return Object.freeze(['review-gaming-build-workload-policy']); if (state === 'observation-required') return Object.freeze(['request-workload-declaration']); if (state === 'insufficient-data') return Object.freeze(['collect-more-workload-samples']); return Object.freeze(['no-change']); }
export function mergeWorkstationWorkloadConflictReports(reports) { const validated = reportsOf(reports); const state = stateOf(validated); const latest = validated.at(-1); return Object.freeze({ library: WORKSTATION_WORKLOAD_CONFLICT_LIBRARY_ID, libraryVersion: WORKSTATION_WORKLOAD_CONFLICT_LIBRARY_VERSION, reportCount: validated.length, state, conflictCount: validated.reduce((sum, report) => sum + (report.conflictCount || 0), 0), observedCount: validated.reduce((sum, report) => sum + (report.observedCount || 0), 0), finalForegroundClass: latest?.finalForegroundClass ?? null, confidence: latest?.confidence || 0, recommendations: recommendations(state) }); }
export function buildWorkstationWorkloadConflictPlan(report, environment = 'unknown') { const validated = requireReport(report); return Object.freeze({ library: WORKSTATION_WORKLOAD_CONFLICT_LIBRARY_ID, environment, mode: environment === 'unknown' ? 'profile-required' : validated.state === 'conflict-observed' ? 'contention-review' : 'workload-observation', intervalMs: validated.state === 'conflict-observed' ? 1500 : 5000, state: validated.state, confidence: validated.confidence }); }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Workload-conflict library clock must return a number'); return timestamp; }
export function buildWorkstationWorkloadConflictEnvelope(report, { trigger, now = Date.now } = {}) { if (typeof trigger !== 'string' || !trigger) throw new TypeError('Workload-conflict library trigger is required'); return Object.freeze({ library: WORKSTATION_WORKLOAD_CONFLICT_LIBRARY_ID, libraryVersion: WORKSTATION_WORKLOAD_CONFLICT_LIBRARY_VERSION, trigger, generatedAt: new Date(requireClock(now)).toISOString(), report: requireReport(report) }); }
export function createWorkstationWorkloadConflictLibrary() { return Object.freeze({ id: WORKSTATION_WORKLOAD_CONFLICT_LIBRARY_ID, version: WORKSTATION_WORKLOAD_CONFLICT_LIBRARY_VERSION, merge: mergeWorkstationWorkloadConflictReports, plan: buildWorkstationWorkloadConflictPlan, envelope: buildWorkstationWorkloadConflictEnvelope }); }
