/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Dedicated safety-audit approval-drift library. It validates explicit
 * approval evidence and builds review-only plans.
 */
export const SAFETY_APPROVAL_DRIFT_LIBRARY_ID = 'safety-audit.approval-drift.library';
export const SAFETY_APPROVAL_DRIFT_LIBRARY_VERSION = 1;
const STATES = Object.freeze(['approval-stable', 'approval-required', 'approval-drift-observed', 'approval-drift-sustained', 'observation-required', 'approval-unknown', 'insufficient-data']);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function requireReport(report) { if (!isRecord(report)) throw new TypeError('Approval-drift library report must be an object'); if (report.turbo !== 'safety-audit.approval-drift') throw new Error('Approval-drift library requires an approval-drift turbo report'); if (!STATES.includes(report.state)) throw new Error('Approval-drift library report has an invalid state'); if (!Number.isInteger(report.sampleCount) || report.sampleCount < 0 || report.sampleCount > 64) throw new RangeError('Approval-drift library sampleCount must be from 0 to 64'); if (!Number.isInteger(report.minimumSamples) || report.minimumSamples < 1 || report.minimumSamples > 64) throw new RangeError('Approval-drift library minimumSamples must be from 1 to 64'); if (!Number.isInteger(report.persistenceThreshold) || report.persistenceThreshold < 1 || report.persistenceThreshold > 64) throw new RangeError('Approval-drift library persistenceThreshold must be from 1 to 64'); for (const [field, label] of [['observedCount', 'observed count'], ['unknownCount', 'unknown count'], ['comparisonCount', 'comparison count'], ['changeCount', 'change count']]) if (!Number.isInteger(report[field]) || report[field] < 0 || report[field] > 4096) throw new RangeError(`Approval-drift library ${label} must be from 0 to 4096`); if (!ENVIRONMENTS.includes(report.finalEnvironment)) throw new TypeError('Approval-drift library finalEnvironment must be normalized'); if (report.finalApproval !== null && typeof report.finalApproval !== 'boolean') throw new TypeError('Approval-drift library finalApproval must be boolean or null'); if (!Number.isFinite(report.confidence) || report.confidence < 0 || report.confidence > 1) throw new RangeError('Approval-drift library confidence must be between 0 and 1'); return report; }
function requireReports(reports) { if (!Array.isArray(reports)) throw new TypeError('Approval-drift library reports must be an array'); if (reports.length > 64) throw new RangeError('Approval-drift library accepts at most 64 reports'); return Object.freeze(reports.map(requireReport)); }
function mergedState(reports) { if (reports.length === 0) return 'insufficient-data'; if (reports.some((report) => report.state === 'approval-unknown')) return 'approval-unknown'; if (reports.some((report) => report.state === 'observation-required')) return 'observation-required'; if (reports.some((report) => report.state === 'approval-drift-sustained')) return 'approval-drift-sustained'; if (reports.some((report) => report.state === 'approval-drift-observed')) return 'approval-drift-observed'; if (reports.some((report) => report.state === 'approval-required')) return 'approval-required'; if (reports.every((report) => report.state === 'insufficient-data')) return 'insufficient-data'; return 'approval-stable'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-approval-evidence']); if (state === 'approval-unknown') return Object.freeze(['request-explicit-approval-evidence']); if (state === 'observation-required') return Object.freeze(['request-complete-approval-observation']); if (state === 'approval-drift-sustained') return Object.freeze(['review-approval-drift']); if (state === 'approval-drift-observed') return Object.freeze(['observe-approval-stability']); if (state === 'approval-required') return Object.freeze(['request-explicit-user-approval']); return Object.freeze(['preserve-user-approval-boundary']); }
function environmentOf(value) { return ENVIRONMENTS.includes(value) ? value : 'unknown'; }
function planMode(state, environment) { if (environment === 'unknown') return 'profile-required'; if (state === 'approval-unknown' || state === 'observation-required') return 'evidence-bootstrap'; if (state === 'approval-drift-sustained') return 'approval-review'; if (state === 'approval-drift-observed') return 'approval-observation'; if (state === 'approval-required') return 'approval-request'; if (state === 'insufficient-data') return 'sample-bootstrap'; return 'stable-observation'; }
function intervalFor(state, environment) { if (state === 'approval-unknown' || state === 'observation-required' || state === 'insufficient-data') return 2000; if (state === 'approval-drift-sustained') return 750; if (state === 'approval-drift-observed') return 1500; if (state === 'approval-required') return 2500; return environment === 'headless' ? 10000 : 5000; }
export function mergeSafetyApprovalDriftReports(reports) { const validated = requireReports(reports); const state = mergedState(validated); const latest = validated.at(-1); return Object.freeze({ library: SAFETY_APPROVAL_DRIFT_LIBRARY_ID, libraryVersion: SAFETY_APPROVAL_DRIFT_LIBRARY_VERSION, reportCount: validated.length, state, sampleCount: validated.reduce((sum, report) => sum + report.sampleCount, 0), observedCount: validated.reduce((sum, report) => sum + report.observedCount, 0), unknownCount: validated.reduce((sum, report) => sum + report.unknownCount, 0), comparisonCount: validated.reduce((sum, report) => sum + report.comparisonCount, 0), changeCount: validated.reduce((sum, report) => sum + report.changeCount, 0), finalEnvironment: latest?.finalEnvironment || 'unknown', finalApproval: latest?.finalApproval ?? null, confidence: latest?.confidence || 0, recommendations: recommendations(state) }); }
export function buildSafetyApprovalDriftPlan(report, environment) { const validated = requireReport(report); const normalizedEnvironment = environmentOf(environment); return Object.freeze({ library: SAFETY_APPROVAL_DRIFT_LIBRARY_ID, environment: normalizedEnvironment, mode: planMode(validated.state, normalizedEnvironment), intervalMs: intervalFor(validated.state, normalizedEnvironment), state: validated.state, confidence: validated.sampleCount === 0 ? 0 : validated.confidence }); }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Approval-drift library clock must return a number'); return timestamp; }
export function buildSafetyApprovalDriftEnvelope(report, { trigger, now = Date.now } = {}) { if (typeof trigger !== 'string' || trigger.length === 0) throw new TypeError('Approval-drift library trigger is required'); return Object.freeze({ library: SAFETY_APPROVAL_DRIFT_LIBRARY_ID, libraryVersion: SAFETY_APPROVAL_DRIFT_LIBRARY_VERSION, trigger, generatedAt: new Date(requireClock(now)).toISOString(), report: requireReport(report) }); }
export function createSafetyApprovalDriftLibrary() { return Object.freeze({ id: SAFETY_APPROVAL_DRIFT_LIBRARY_ID, version: SAFETY_APPROVAL_DRIFT_LIBRARY_VERSION, merge: mergeSafetyApprovalDriftReports, plan: buildSafetyApprovalDriftPlan, envelope: buildSafetyApprovalDriftEnvelope }); }
