/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Safety-audit approval-drift turbo. It tracks explicit user approval without
 * executing, approving, or rejecting a proposed action.
 */
export const SAFETY_APPROVAL_DRIFT_TURBO_ID = 'safety-audit.approval-drift';
export const SAFETY_APPROVAL_DRIFT_TURBO_VERSION = 1;
export const SAFETY_APPROVAL_DRIFT_TRIGGERS = Object.freeze(['install.preflight', 'system.facts.request', 'workload.changed', 'health.interval']);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function approvalOf(value) { return typeof value === 'boolean' ? value : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Safety-audit approval-drift snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Safety-audit approval-drift requires a system-facts snapshot'); if (!isRecord(snapshot.audit)) throw new TypeError('Safety-audit approval-drift snapshot requires an audit object'); return snapshot; }
function evidenceOf(snapshot) { const source = requireSnapshot(snapshot); const approval = approvalOf(source.audit.userApproval); return Object.freeze({ environment: ENVIRONMENTS.includes(source.environment) ? source.environment : 'unknown', approval, observed: approval !== null, signature: approval === null ? '?' : String(approval) }); }
function requireTrigger(trigger) { if (!SAFETY_APPROVAL_DRIFT_TRIGGERS.includes(trigger)) throw new Error(`Unsupported safety-audit approval-drift trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindow(value) { if (!Number.isInteger(value) || value < 2 || value > 64) throw new RangeError('Safety-audit approval-drift windowSize must be an integer from 2 to 64'); return value; }
function requireMinimum(value, windowSize) { if (!Number.isInteger(value) || value < 1 || value > windowSize) throw new RangeError('Safety-audit approval-drift minimumSamples must fit inside the window'); return value; }
function requireThreshold(value, windowSize) { if (!Number.isInteger(value) || value < 1 || value > windowSize) throw new RangeError('Safety-audit approval-drift persistenceThreshold must fit inside the window'); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Safety-audit approval-drift clock must return a number'); return timestamp; }
function stateFor(sampleCount, minimumSamples, observedCount, unknownCount, changeCount, persistenceThreshold, finalApproval) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (observedCount === 0) return 'approval-unknown'; if (unknownCount > 0) return 'observation-required'; if (changeCount >= persistenceThreshold) return 'approval-drift-sustained'; if (changeCount > 0) return 'approval-drift-observed'; if (finalApproval === false) return 'approval-required'; return 'approval-stable'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-approval-evidence']); if (state === 'approval-unknown') return Object.freeze(['request-explicit-approval-evidence']); if (state === 'observation-required') return Object.freeze(['request-complete-approval-observation']); if (state === 'approval-drift-sustained') return Object.freeze(['review-approval-drift']); if (state === 'approval-drift-observed') return Object.freeze(['observe-approval-stability']); if (state === 'approval-required') return Object.freeze(['request-explicit-user-approval']); return Object.freeze(['preserve-user-approval-boundary']); }
export function runSafetyApprovalDriftTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Safety-audit approval-drift samples must be an array'); const boundedWindow = requireWindow(windowSize); const requiredSamples = requireMinimum(minimumSamples, boundedWindow); const requiredPersistence = requireThreshold(persistenceThreshold, boundedWindow); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = selected.map(evidenceOf); const changes = evidence.slice(1).map((current, index) => Object.freeze({ changed: current.signature !== evidence[index].signature })); const observedCount = evidence.filter((item) => item.observed).length; const unknownCount = evidence.length - observedCount; const changeCount = changes.filter((item) => item.changed).length; const latest = evidence.length === 0 ? null : evidence[evidence.length - 1]; const state = stateFor(selected.length, requiredSamples, observedCount, unknownCount, changeCount, requiredPersistence, latest ? latest.approval : null); return Object.freeze({ protocolVersion: 1, turbo: SAFETY_APPROVAL_DRIFT_TURBO_ID, turboVersion: SAFETY_APPROVAL_DRIFT_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, observedCount, unknownCount, comparisonCount: changes.length, changeCount, finalEnvironment: latest ? latest.environment : 'unknown', finalApproval: latest ? latest.approval : null, state, confidence: selected.length === 0 ? 0 : Math.round((observedCount / selected.length) * 10000) / 10000, recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
