/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Route-stability turbo. It compares bounded default-route evidence without
 * changing routes, interfaces, or network settings.
 */

export const NETWORK_OBSERVATION_ROUTE_STABILITY_TURBO_ID = 'network-observation.route-stability';
export const NETWORK_OBSERVATION_ROUTE_STABILITY_TURBO_VERSION = 1;
export const NETWORK_OBSERVATION_ROUTE_STABILITY_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Route-stability snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Route-stability requires a system-facts snapshot'); if (!Array.isArray(snapshot.network)) throw new TypeError('Route-stability snapshot requires a network list'); return snapshot; }
function requireTrigger(trigger) { if (!NETWORK_OBSERVATION_ROUTE_STABILITY_TRIGGERS.includes(trigger)) throw new Error(`Unsupported route-stability trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Route-stability windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Route-stability minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Route-stability ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Route-stability clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot, previous) { const source = requireSnapshot(snapshot); const rows = source.network.filter(isRecord); const routes = rows.filter((link) => link.defaultRoute === true).map((link) => `${text(link.name) || 'unnamed'}|${text(link.kind) || 'unknown'}`); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', linkCount: rows.length, defaultRouteCount: routes.length, routeChangeCount: 0, comparisonCount: 0, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-network', linkCount: 0, defaultRouteCount: 0, routeChangeCount: 0, comparisonCount: 0, review: false }); const previousRoutes = previous?.routes || []; const comparable = previous?.state === 'observed'; const routeChanged = comparable && (routes.length !== previousRoutes.length || routes.some((route) => !previousRoutes.includes(route))); const routeChangeCount = routeChanged ? Math.max(routes.length, previousRoutes.length) : 0; return Object.freeze({ state: 'observed', linkCount: rows.length, defaultRouteCount: routes.length, routeChangeCount, comparisonCount: comparable ? 1 : 0, review: routeChanged, routes }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, changeSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-network')) return 'no-network'; if (incompleteCount > 0) return 'incomplete-evidence'; if (changeSampleCount >= persistenceThreshold) return 'route-drift-sustained'; if (changeSampleCount > 0) return 'route-drift-observed'; return 'stable-routes'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-route-evidence']); if (state === 'no-network') return Object.freeze(['no-network-route-review']); if (state === 'incomplete-evidence') return Object.freeze(['request-network-environment-profile']); if (state === 'route-drift-sustained') return Object.freeze(['review-route-drift-without-network-mutation']); if (state === 'route-drift-observed') return Object.freeze(['observe-route-stability']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runNetworkObservationRouteStabilityTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Route-stability samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = []; let previous; for (const sample of selected) { const current = aggregate(sample, previous); evidence.push(current); previous = current; } const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noNetworkCount = evidence.filter((item) => item.state === 'no-network').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const comparisonCount = evidence.reduce((sum, item) => sum + item.comparisonCount, 0); const routeChangeSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const latest = evidence.at(-1) || Object.freeze({ linkCount: 0, defaultRouteCount: 0, routeChangeCount: 0 }); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, routeChangeSampleCount, requiredPersistence); return Object.freeze({ protocolVersion: 1, turbo: NETWORK_OBSERVATION_ROUTE_STABILITY_TURBO_ID, turboVersion: NETWORK_OBSERVATION_ROUTE_STABILITY_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, linkCount: latest.linkCount, defaultRouteCount: latest.defaultRouteCount, routeChangeCount: latest.routeChangeCount, observedCount, incompleteCount, noNetworkCount, comparisonCount, routeChangeSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
