/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Destination-selection library for merging reviewable target evidence.
 */

export const DOWNLOAD_GUARD_DESTINATION_SELECTION_LIBRARY_ID = 'download-guard.destination-selection.library';
export const DOWNLOAD_GUARD_DESTINATION_SELECTION_LIBRARY_VERSION = 1;
const STATES = Object.freeze(['destination-selected', 'redirect-required', 'observation-required']);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function requireReport(report) { if (!isRecord(report)) throw new TypeError('Destination-selection library report must be an object'); if (report.turbo !== 'download-guard.destination-selection') throw new Error('Destination-selection library requires a destination-selection turbo report'); if (!STATES.includes(report.state)) throw new Error('Destination-selection library report has an invalid state'); if (typeof report.finalTarget !== 'string' && report.finalTarget !== null) throw new TypeError('Destination-selection library finalTarget must be a string or null'); return report; }
function requireReports(reports) { if (!Array.isArray(reports)) throw new TypeError('Destination-selection library reports must be an array'); if (reports.length > 64) throw new RangeError('Destination-selection library accepts at most 64 reports'); return Object.freeze(reports.map(requireReport)); }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Destination-selection library clock must return a number'); return timestamp; }
export function mergeDownloadGuardDestinationSelectionReports(reports) { const validated = requireReports(reports); const latest = validated.at(-1) || null; const state = validated.some((report) => report.state === 'redirect-required') ? 'redirect-required' : validated.some((report) => report.state === 'destination-selected') ? 'destination-selected' : 'observation-required'; return Object.freeze({ library: DOWNLOAD_GUARD_DESTINATION_SELECTION_LIBRARY_ID, libraryVersion: DOWNLOAD_GUARD_DESTINATION_SELECTION_LIBRARY_VERSION, reportCount: validated.length, state, finalTarget: latest?.finalTarget || null, redirectedCount: validated.reduce((sum, report) => sum + report.redirectedCount, 0) }); }
export function buildDownloadGuardDestinationSelectionPlan(report, environment = 'unknown') { const validated = requireReport(report); const normalized = ['interactive', 'headless'].includes(environment) ? environment : 'unknown'; return Object.freeze({ library: DOWNLOAD_GUARD_DESTINATION_SELECTION_LIBRARY_ID, environment: normalized, mode: normalized === 'unknown' ? 'profile-required' : validated.state === 'redirect-required' ? 'approval-required' : 'destination-review', target: validated.finalTarget }); }
export function buildDownloadGuardDestinationSelectionEnvelope(report, { trigger, now = Date.now } = {}) { if (typeof trigger !== 'string' || !trigger) throw new TypeError('Destination-selection library trigger is required'); return Object.freeze({ library: DOWNLOAD_GUARD_DESTINATION_SELECTION_LIBRARY_ID, libraryVersion: DOWNLOAD_GUARD_DESTINATION_SELECTION_LIBRARY_VERSION, trigger, generatedAt: new Date(requireClock(now)).toISOString(), report: requireReport(report) }); }
export function createDownloadGuardDestinationSelectionLibrary() { return Object.freeze({ id: DOWNLOAD_GUARD_DESTINATION_SELECTION_LIBRARY_ID, version: DOWNLOAD_GUARD_DESTINATION_SELECTION_LIBRARY_VERSION, merge: mergeDownloadGuardDestinationSelectionReports, plan: buildDownloadGuardDestinationSelectionPlan, envelope: buildDownloadGuardDestinationSelectionEnvelope }); }
