/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Proposal-drift turbo. It compares explicit organization proposals without
 * moving, renaming, deleting, overwriting, or inspecting files.
 */

export const ORGANIZATION_PREVIEW_PROPOSAL_DRIFT_TURBO_ID = 'organization-preview.proposal-drift';
export const ORGANIZATION_PREVIEW_PROPOSAL_DRIFT_TURBO_VERSION = 1;
export const ORGANIZATION_PREVIEW_PROPOSAL_DRIFT_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Proposal-drift snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Proposal-drift requires a system-facts snapshot'); if (!isRecord(snapshot.organization)) throw new TypeError('Proposal-drift snapshot requires an organization object'); if (!Array.isArray(snapshot.organization.items)) throw new TypeError('Proposal-drift snapshot requires an organization item list'); return snapshot; }
function requireTrigger(trigger) { if (!ORGANIZATION_PREVIEW_PROPOSAL_DRIFT_TRIGGERS.includes(trigger)) throw new Error(`Unsupported proposal-drift trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Proposal-drift windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Proposal-drift minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Proposal-drift ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Proposal-drift clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot, previous) { const source = requireSnapshot(snapshot); const rows = source.organization.items.filter(isRecord).map((item) => ({ key: text(item.name) || 'unnamed', proposal: text(item.proposal) })); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', itemCount: rows.length, unknownProposalCount: rows.filter((row) => row.proposal === null).length, proposalChangeCount: 0, comparisonCount: 0, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-organization-preview', itemCount: 0, unknownProposalCount: 0, proposalChangeCount: 0, comparisonCount: 0, review: false }); const unknownProposalCount = rows.filter((row) => row.proposal === null).length; if (unknownProposalCount > 0) return Object.freeze({ state: 'incomplete', itemCount: rows.length, unknownProposalCount, proposalChangeCount: 0, comparisonCount: 0, review: false }); const previousRows = previous?.rows || []; const previousMap = new Map(previousRows.map((row) => [row.key, row.proposal])); const comparable = previous?.state === 'observed'; const proposalChangeCount = comparable ? rows.filter((row) => previousMap.get(row.key) !== undefined && previousMap.get(row.key) !== row.proposal).length : 0; return Object.freeze({ state: 'observed', itemCount: rows.length, unknownProposalCount: 0, proposalChangeCount, comparisonCount: comparable ? 1 : 0, review: proposalChangeCount > 0, rows }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, changeSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-organization-preview')) return 'no-organization-preview'; if (incompleteCount > 0) return 'incomplete-evidence'; if (changeSampleCount >= persistenceThreshold) return 'proposal-drift-sustained'; if (changeSampleCount > 0) return 'proposal-drift-observed'; return 'stable-proposals'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-organization-proposals']); if (state === 'no-organization-preview') return Object.freeze(['no-organization-preview']); if (state === 'incomplete-evidence') return Object.freeze(['request-explicit-organization-proposals']); if (state === 'proposal-drift-sustained') return Object.freeze(['review-proposal-drift-without-file-mutation']); if (state === 'proposal-drift-observed') return Object.freeze(['observe-proposal-stability']); return Object.freeze(['preview-proposals-only']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runOrganizationPreviewProposalDriftTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Proposal-drift samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = []; let previous; for (const sample of selected) { const current = aggregate(sample, previous); evidence.push(current); previous = current; } const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noOrganizationCount = evidence.filter((item) => item.state === 'no-organization-preview').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const proposalChangeSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const latest = evidence.at(-1) || Object.freeze({ itemCount: 0, unknownProposalCount: 0, proposalChangeCount: 0 }); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, proposalChangeSampleCount, requiredPersistence); return Object.freeze({ protocolVersion: 1, turbo: ORGANIZATION_PREVIEW_PROPOSAL_DRIFT_TURBO_ID, turboVersion: ORGANIZATION_PREVIEW_PROPOSAL_DRIFT_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, itemCount: latest.itemCount, unknownProposalCount: latest.unknownProposalCount, proposalChangeCount: latest.proposalChangeCount, observedCount, incompleteCount, noOrganizationCount, proposalChangeSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
