/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Dedicated I/O-evidence library. It validates, aggregates, and plans fact
 * completeness reports without importing the turbo or changing disks.
 */

export const DISK_IO_EVIDENCE_LIBRARY_ID = 'disk-io.io-evidence.library';
export const DISK_IO_EVIDENCE_LIBRARY_VERSION = 1;
const STATES = Object.freeze(['io-evidence-gap-sustained', 'io-evidence-gap-observed', 'complete-io-evidence', 'no-disks', 'incomplete-io-evidence', 'insufficient-data']); const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function requireSampleCount(report, field, label) { if (!Number.isInteger(report[field]) || report[field] < 0 || report[field] > report.sampleCount) throw new RangeError(`I/O-evidence library report ${label} must fit inside sampleCount`); return report[field]; }
function requireReport(report) {
  if (!isRecord(report)) throw new TypeError('I/O-evidence library report must be an object'); if (report.turbo !== 'disk-io.io-evidence') throw new Error('I/O-evidence library requires an I/O-evidence turbo report'); if (!STATES.includes(report.state)) throw new Error('I/O-evidence library report has an invalid state');
  if (!Number.isInteger(report.sampleCount) || report.sampleCount < 0 || report.sampleCount > 64) throw new RangeError('I/O-evidence library report sampleCount must be from 0 to 64'); if (!Number.isInteger(report.minimumSamples) || report.minimumSamples < 1 || report.minimumSamples > 64) throw new RangeError('I/O-evidence library minimumSamples must be from 1 to 64'); if (!Number.isFinite(report.evidenceThreshold) || report.evidenceThreshold < 0 || report.evidenceThreshold > 1) throw new RangeError('I/O-evidence library evidenceThreshold must be between 0 and 1'); if (!Number.isInteger(report.persistenceThreshold) || report.persistenceThreshold < 1 || report.persistenceThreshold > 64) throw new RangeError('I/O-evidence library persistenceThreshold must be from 1 to 64');
  for (const [field, label] of [['observedCount', 'observed count'], ['incompleteCount', 'incomplete count'], ['noDiskCount', 'no-disk count'], ['gapSampleCount', 'gap sample count']]) requireSampleCount(report, field, label); if (!Number.isInteger(report.diskCount) || report.diskCount < 0 || report.diskCount > 4096) throw new RangeError('I/O-evidence library diskCount must be from 0 to 4096'); for (const [field, label] of [['completeCount', 'complete count'], ['incompleteRowCount', 'incomplete row count']]) if (!Number.isInteger(report[field]) || report[field] < 0 || report[field] > report.diskCount) throw new RangeError(`I/O-evidence library ${label} must fit inside diskCount`); if (report.evidenceRatio !== null && (!Number.isFinite(report.evidenceRatio) || report.evidenceRatio < 0 || report.evidenceRatio > 1)) throw new RangeError('I/O-evidence library evidenceRatio must be null or between 0 and 1'); if (!Number.isFinite(report.confidence) || report.confidence < 0 || report.confidence > 1) throw new RangeError('I/O-evidence library confidence must be between 0 and 1'); return report;
}
function requireReports(reports) { if (!Array.isArray(reports)) throw new TypeError('I/O-evidence library reports must be an array'); if (reports.length > 64) throw new RangeError('I/O-evidence library accepts at most 64 reports'); return Object.freeze(reports.map(requireReport)); }
function mergedState(reports) { if (reports.length === 0) return 'insufficient-data'; if (reports.some((report) => report.state === 'no-disks')) return 'no-disks'; if (reports.some((report) => report.state === 'incomplete-io-evidence')) return 'incomplete-io-evidence'; if (reports.some((report) => report.state === 'io-evidence-gap-sustained')) return 'io-evidence-gap-sustained'; if (reports.some((report) => report.state === 'io-evidence-gap-observed')) return 'io-evidence-gap-observed'; if (reports.every((report) => report.state === 'insufficient-data')) return 'insufficient-data'; return 'complete-io-evidence'; }
function mergedConfidence(reports) { if (reports.length === 0) return 0; const samples = reports.reduce((sum, report) => sum + report.sampleCount, 0); if (samples === 0) return 0; return Math.round((reports.reduce((sum, report) => sum + report.observedCount, 0) / samples) * 10000) / 10000; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-io-facts']); if (state === 'no-disks') return Object.freeze(['no-disk-io-review']); if (state === 'incomplete-io-evidence') return Object.freeze(['request-environment-profile']); if (state === 'io-evidence-gap-sustained') return Object.freeze(['request-complete-io-facts']); if (state === 'io-evidence-gap-observed') return Object.freeze(['observe-io-fact-completeness']); return Object.freeze(['no-change']); }
function environmentOf(environment) { return ENVIRONMENTS.includes(environment) ? environment : 'unknown'; }
function planMode(state, environment) { if (environment === 'unknown') return 'profile-required'; if (state === 'io-evidence-gap-sustained') return 'io-fact-review'; if (state === 'io-evidence-gap-observed') return 'io-fact-observation'; if (state === 'no-disks') return 'no-disk-observation'; if (state === 'incomplete-io-evidence') return 'evidence-bootstrap'; if (state === 'insufficient-data') return 'sample-bootstrap'; return 'complete-io-observation'; }
function intervalFor(state, environment) { if (state === 'io-evidence-gap-sustained') return 750; if (state === 'io-evidence-gap-observed') return 1000; if (state === 'no-disks') return 10000; if (state === 'incomplete-io-evidence' || state === 'insufficient-data') return 1500; return environment === 'headless' ? 10000 : 5000; }
function latest(reports) { return reports.at(-1) || { diskCount: 0, completeCount: 0, incompleteRowCount: 0, evidenceRatio: null }; }
export function mergeDiskIoEvidenceReports(reports) { const validated = requireReports(reports); const state = mergedState(validated); const last = latest(validated); return Object.freeze({ library: DISK_IO_EVIDENCE_LIBRARY_ID, libraryVersion: DISK_IO_EVIDENCE_LIBRARY_VERSION, reportCount: validated.length, state, sampleCount: validated.reduce((sum, report) => sum + report.sampleCount, 0), diskCount: last.diskCount, completeCount: last.completeCount, incompleteRowCount: last.incompleteRowCount, evidenceRatio: last.evidenceRatio, observedCount: validated.reduce((sum, report) => sum + report.observedCount, 0), incompleteCount: validated.reduce((sum, report) => sum + report.incompleteCount, 0), noDiskCount: validated.reduce((sum, report) => sum + report.noDiskCount, 0), gapSampleCount: validated.reduce((sum, report) => sum + report.gapSampleCount, 0), confidence: mergedConfidence(validated), recommendations: recommendations(state) }); }
export function buildDiskIoEvidencePlan(report, environment) { const validated = requireReport(report); const normalizedEnvironment = environmentOf(environment); return Object.freeze({ library: DISK_IO_EVIDENCE_LIBRARY_ID, environment: normalizedEnvironment, mode: planMode(validated.state, normalizedEnvironment), intervalMs: intervalFor(validated.state, normalizedEnvironment), state: validated.state, confidence: validated.sampleCount === 0 ? 0 : Math.round((validated.observedCount / validated.sampleCount) * 10000) / 10000 }); }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('I/O-evidence library clock must return a number'); return timestamp; }
export function buildDiskIoEvidenceEnvelope(report, { trigger, now = Date.now } = {}) { if (typeof trigger !== 'string' || trigger.length === 0) throw new TypeError('I/O-evidence library trigger is required'); return Object.freeze({ library: DISK_IO_EVIDENCE_LIBRARY_ID, libraryVersion: DISK_IO_EVIDENCE_LIBRARY_VERSION, trigger, generatedAt: new Date(requireClock(now)).toISOString(), report: requireReport(report) }); }
export function createDiskIoEvidenceLibrary() { return Object.freeze({ id: DISK_IO_EVIDENCE_LIBRARY_ID, version: DISK_IO_EVIDENCE_LIBRARY_VERSION, merge: mergeDiskIoEvidenceReports, plan: buildDiskIoEvidencePlan, envelope: buildDiskIoEvidenceEnvelope }); }
