/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * I/O-evidence turbo. It scores bounded read, write, and wait evidence
 * without probing devices, changing queues, or changing files.
 */

export const DISK_IO_EVIDENCE_TURBO_ID = 'disk-io.io-evidence';
export const DISK_IO_EVIDENCE_TURBO_VERSION = 1;
export const DISK_IO_EVIDENCE_TRIGGERS = Object.freeze(['install.preflight', 'system.facts.request', 'workload.changed', 'health.interval']);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']); const EMPTY_ARRAY = Object.freeze([]);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function nonNegative(value) { return Number.isFinite(value) && value >= 0 ? value : null; }
function percent(value) { if (!Number.isFinite(value)) return null; return Math.min(100, Math.max(0, value)); }
function completeRow(row) { return nonNegative(row.readBytesPerSecond) !== null && nonNegative(row.writeBytesPerSecond) !== null && percent(row.ioWaitPercent) !== null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('I/O-evidence snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('I/O-evidence requires a system-facts snapshot'); if (!Array.isArray(snapshot.storage)) throw new TypeError('I/O-evidence snapshot requires a storage list'); return snapshot; }
function requireTrigger(trigger) { if (!DISK_IO_EVIDENCE_TRIGGERS.includes(trigger)) throw new Error(`Unsupported I/O-evidence trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('I/O-evidence windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('I/O-evidence minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`I/O-evidence ${name} must be an integer from 1 to 64`); return value; }
function requireRatio(value) { if (!Number.isFinite(value) || value < 0 || value > 1) throw new RangeError('I/O-evidence evidenceThreshold must be between 0 and 1'); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('I/O-evidence clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot, evidenceThreshold) { const source = requireSnapshot(snapshot); const rows = source.storage.filter(isRecord); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', diskCount: rows.length, completeCount: 0, incompleteRowCount: rows.length, evidenceRatio: null, gap: false }); if (rows.length === 0) return Object.freeze({ state: 'no-disks', diskCount: 0, completeCount: 0, incompleteRowCount: 0, evidenceRatio: null, gap: false }); const completeCount = rows.filter(completeRow).length; const incompleteRowCount = rows.length - completeCount; const evidenceRatio = completeCount / rows.length; return Object.freeze({ state: 'observed', diskCount: rows.length, completeCount, incompleteRowCount, evidenceRatio, gap: evidenceRatio < evidenceThreshold }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, gapSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-disks')) return 'no-disks'; if (incompleteCount > 0) return 'incomplete-io-evidence'; if (gapSampleCount >= persistenceThreshold) return 'io-evidence-gap-sustained'; if (gapSampleCount > 0) return 'io-evidence-gap-observed'; return 'complete-io-evidence'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-io-facts']); if (state === 'no-disks') return Object.freeze(['no-disk-io-review']); if (state === 'incomplete-io-evidence') return Object.freeze(['request-environment-profile']); if (state === 'io-evidence-gap-sustained') return Object.freeze(['request-complete-io-facts']); if (state === 'io-evidence-gap-observed') return Object.freeze(['observe-io-fact-completeness']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }
export function runDiskIoEvidenceTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, evidenceThreshold = 0.75, persistenceThreshold = 2, now = Date.now } = {}) {
  requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('I/O-evidence samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredThreshold = requireRatio(evidenceThreshold); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = selected.map((sample) => aggregate(sample, requiredThreshold)); const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noDiskCount = evidence.filter((item) => item.state === 'no-disks').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const gapSampleCount = evidence.filter((item) => item.state === 'observed' && item.gap).length; const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, gapSampleCount, requiredPersistence); const latest = evidence.at(-1) || Object.freeze({ diskCount: 0, completeCount: 0, incompleteRowCount: 0, evidenceRatio: null });
  return Object.freeze({ protocolVersion: 1, turbo: DISK_IO_EVIDENCE_TURBO_ID, turboVersion: DISK_IO_EVIDENCE_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, evidenceThreshold: requiredThreshold, persistenceThreshold: requiredPersistence, diskCount: latest.diskCount, completeCount: latest.completeCount, incompleteRowCount: latest.incompleteRowCount, evidenceRatio: latest.evidenceRatio, observedCount, incompleteCount, noDiskCount, gapSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY });
}
