/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Dedicated workload-profile declaration-stability library. It validates
 * declaration evidence and creates bounded review envelopes.
 */
export const WORKLOAD_DECLARATION_STABILITY_LIBRARY_ID = 'workload-profile.declaration-stability.library';
export const WORKLOAD_DECLARATION_STABILITY_LIBRARY_VERSION = 1;
const STATES = Object.freeze(['stable-declaration', 'declaration-required', 'declaration-drift-observed', 'declaration-drift-sustained', 'observation-required', 'declaration-unknown', 'insufficient-data']);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function requireReport(report) {
  if (!isRecord(report)) throw new TypeError('Declaration-stability library report must be an object');
  if (report.turbo !== 'workload-profile.declaration-stability') throw new Error('Declaration-stability library requires a declaration-stability turbo report');
  if (!STATES.includes(report.state)) throw new Error('Declaration-stability library report has an invalid state');
  if (!Number.isInteger(report.sampleCount) || report.sampleCount < 0 || report.sampleCount > 64) throw new RangeError('Declaration-stability library sampleCount must be from 0 to 64');
  if (!Number.isInteger(report.minimumSamples) || report.minimumSamples < 1 || report.minimumSamples > 64) throw new RangeError('Declaration-stability library minimumSamples must be from 1 to 64');
  if (!Number.isInteger(report.persistenceThreshold) || report.persistenceThreshold < 1 || report.persistenceThreshold > 64) throw new RangeError('Declaration-stability library persistenceThreshold must be from 1 to 64');
  for (const [field, label] of [['observedCount', 'observed count'], ['unknownCount', 'unknown count'], ['comparisonCount', 'comparison count'], ['changeCount', 'change count'], ['declarationChangeCount', 'declaration-change count'], ['interactiveChangeCount', 'interactive-change count']]) if (!Number.isInteger(report[field]) || report[field] < 0 || report[field] > 4096) throw new RangeError(`Declaration-stability library ${label} must be from 0 to 4096`);
  if (!ENVIRONMENTS.includes(report.finalEnvironment)) throw new TypeError('Declaration-stability library finalEnvironment must be normalized');
  if (report.finalDeclared !== null && typeof report.finalDeclared !== 'boolean') throw new TypeError('Declaration-stability library finalDeclared must be boolean or null');
  if (report.finalInteractive !== null && typeof report.finalInteractive !== 'boolean') throw new TypeError('Declaration-stability library finalInteractive must be boolean or null');
  if (!Number.isFinite(report.confidence) || report.confidence < 0 || report.confidence > 1) throw new RangeError('Declaration-stability library confidence must be between 0 and 1');
  return report;
}
function requireReports(reports) { if (!Array.isArray(reports)) throw new TypeError('Declaration-stability library reports must be an array'); if (reports.length > 64) throw new RangeError('Declaration-stability library accepts at most 64 reports'); return Object.freeze(reports.map(requireReport)); }
function mergedState(reports) {
  if (reports.length === 0) return 'insufficient-data'; if (reports.some((report) => report.state === 'declaration-unknown')) return 'declaration-unknown'; if (reports.some((report) => report.state === 'observation-required')) return 'observation-required'; if (reports.some((report) => report.state === 'declaration-drift-sustained')) return 'declaration-drift-sustained'; if (reports.some((report) => report.state === 'declaration-drift-observed')) return 'declaration-drift-observed'; if (reports.some((report) => report.state === 'declaration-required')) return 'declaration-required'; if (reports.every((report) => report.state === 'insufficient-data')) return 'insufficient-data'; return 'stable-declaration';
}
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-declaration-samples']); if (state === 'declaration-unknown') return Object.freeze(['request-workload-declaration']); if (state === 'observation-required') return Object.freeze(['request-complete-declaration-observation']); if (state === 'declaration-drift-sustained') return Object.freeze(['review-declaration-drift']); if (state === 'declaration-drift-observed') return Object.freeze(['observe-declaration-stability']); if (state === 'declaration-required') return Object.freeze(['request-explicit-workload-declaration']); return Object.freeze(['preserve-user-declaration']); }
function environmentOf(value) { return ENVIRONMENTS.includes(value) ? value : 'unknown'; }
function planMode(state, environment) { if (environment === 'unknown') return 'profile-required'; if (state === 'declaration-unknown' || state === 'observation-required') return 'evidence-bootstrap'; if (state === 'declaration-drift-sustained') return 'declaration-review'; if (state === 'declaration-drift-observed') return 'declaration-observation'; if (state === 'declaration-required') return 'declaration-request'; if (state === 'insufficient-data') return 'sample-bootstrap'; return 'stable-observation'; }
function intervalFor(state, environment) { if (state === 'declaration-unknown' || state === 'observation-required' || state === 'insufficient-data') return 2000; if (state === 'declaration-drift-sustained') return 750; if (state === 'declaration-drift-observed') return 1500; if (state === 'declaration-required') return 2500; return environment === 'headless' ? 10000 : 5000; }
export function mergeWorkloadDeclarationStabilityReports(reports) { const validated = requireReports(reports); const state = mergedState(validated); const latest = validated.at(-1); return Object.freeze({ library: WORKLOAD_DECLARATION_STABILITY_LIBRARY_ID, libraryVersion: WORKLOAD_DECLARATION_STABILITY_LIBRARY_VERSION, reportCount: validated.length, state, sampleCount: validated.reduce((sum, report) => sum + report.sampleCount, 0), observedCount: validated.reduce((sum, report) => sum + report.observedCount, 0), unknownCount: validated.reduce((sum, report) => sum + report.unknownCount, 0), comparisonCount: validated.reduce((sum, report) => sum + report.comparisonCount, 0), changeCount: validated.reduce((sum, report) => sum + report.changeCount, 0), declarationChangeCount: validated.reduce((sum, report) => sum + report.declarationChangeCount, 0), interactiveChangeCount: validated.reduce((sum, report) => sum + report.interactiveChangeCount, 0), finalEnvironment: latest?.finalEnvironment || 'unknown', finalDeclared: latest?.finalDeclared ?? null, finalInteractive: latest?.finalInteractive ?? null, confidence: latest?.confidence || 0, recommendations: recommendations(state) }); }
export function buildWorkloadDeclarationStabilityPlan(report, environment) { const validated = requireReport(report); const normalizedEnvironment = environmentOf(environment); return Object.freeze({ library: WORKLOAD_DECLARATION_STABILITY_LIBRARY_ID, environment: normalizedEnvironment, mode: planMode(validated.state, normalizedEnvironment), intervalMs: intervalFor(validated.state, normalizedEnvironment), state: validated.state, confidence: validated.sampleCount === 0 ? 0 : validated.confidence }); }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Declaration-stability library clock must return a number'); return timestamp; }
export function buildWorkloadDeclarationStabilityEnvelope(report, { trigger, now = Date.now } = {}) { if (typeof trigger !== 'string' || trigger.length === 0) throw new TypeError('Declaration-stability library trigger is required'); return Object.freeze({ library: WORKLOAD_DECLARATION_STABILITY_LIBRARY_ID, libraryVersion: WORKLOAD_DECLARATION_STABILITY_LIBRARY_VERSION, trigger, generatedAt: new Date(requireClock(now)).toISOString(), report: requireReport(report) }); }
export function createWorkloadDeclarationStabilityLibrary() { return Object.freeze({ id: WORKLOAD_DECLARATION_STABILITY_LIBRARY_ID, version: WORKLOAD_DECLARATION_STABILITY_LIBRARY_VERSION, merge: mergeWorkloadDeclarationStabilityReports, plan: buildWorkloadDeclarationStabilityPlan, envelope: buildWorkloadDeclarationStabilityEnvelope }); }
