/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Workload-profile declaration-stability turbo. It observes explicit workload
 * declarations and interactive flags without changing user preferences.
 */
export const WORKLOAD_DECLARATION_STABILITY_TURBO_ID = 'workload-profile.declaration-stability';
export const WORKLOAD_DECLARATION_STABILITY_TURBO_VERSION = 1;
export const WORKLOAD_DECLARATION_STABILITY_TRIGGERS = Object.freeze(['install.preflight', 'system.facts.request', 'workload.changed', 'health.interval']);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function booleanOrNull(value) { return typeof value === 'boolean' ? value : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Workload-profile declaration-stability snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Workload-profile declaration-stability requires a system-facts snapshot'); if (!isRecord(snapshot.workload)) throw new TypeError('Workload-profile declaration-stability snapshot requires a workload object'); return snapshot; }
function evidenceOf(snapshot) { const source = requireSnapshot(snapshot); const declared = booleanOrNull(source.workload.declared); const interactive = booleanOrNull(source.workload.interactive); return Object.freeze({ environment: ENVIRONMENTS.includes(source.environment) ? source.environment : 'unknown', declared, interactive, observed: declared !== null || interactive !== null, signature: `${declared === null ? '?' : declared}:${interactive === null ? '?' : interactive}` }); }
function requireTrigger(trigger) { if (!WORKLOAD_DECLARATION_STABILITY_TRIGGERS.includes(trigger)) throw new Error(`Unsupported workload-profile declaration-stability trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindow(value) { if (!Number.isInteger(value) || value < 2 || value > 64) throw new RangeError('Workload-profile declaration-stability windowSize must be an integer from 2 to 64'); return value; }
function requireMinimum(value, windowSize) { if (!Number.isInteger(value) || value < 1 || value > windowSize) throw new RangeError('Workload-profile declaration-stability minimumSamples must fit inside the window'); return value; }
function requireThreshold(value, windowSize) { if (!Number.isInteger(value) || value < 1 || value > windowSize) throw new RangeError('Workload-profile declaration-stability persistenceThreshold must fit inside the window'); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Workload-profile declaration-stability clock must return a number'); return timestamp; }
function stateFor(sampleCount, minimumSamples, observedCount, unknownCount, changeCount, persistenceThreshold, finalDeclared) {
  if (sampleCount < minimumSamples) return 'insufficient-data'; if (observedCount === 0) return 'declaration-unknown'; if (unknownCount > 0) return 'observation-required'; if (changeCount >= persistenceThreshold) return 'declaration-drift-sustained'; if (changeCount > 0) return 'declaration-drift-observed'; if (finalDeclared === false) return 'declaration-required'; return 'stable-declaration';
}
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-declaration-samples']); if (state === 'declaration-unknown') return Object.freeze(['request-workload-declaration']); if (state === 'observation-required') return Object.freeze(['request-complete-declaration-observation']); if (state === 'declaration-drift-sustained') return Object.freeze(['review-declaration-drift']); if (state === 'declaration-drift-observed') return Object.freeze(['observe-declaration-stability']); if (state === 'declaration-required') return Object.freeze(['request-explicit-workload-declaration']); return Object.freeze(['preserve-user-declaration']); }
export function runWorkloadDeclarationStabilityTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) {
  requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Workload-profile declaration-stability samples must be an array'); const boundedWindow = requireWindow(windowSize); const requiredSamples = requireMinimum(minimumSamples, boundedWindow); const requiredPersistence = requireThreshold(persistenceThreshold, boundedWindow); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = selected.map(evidenceOf);
  const changes = evidence.slice(1).map((current, index) => Object.freeze({ changed: current.signature !== evidence[index].signature, declarationChanged: current.declared !== evidence[index].declared, interactiveChanged: current.interactive !== evidence[index].interactive })); const observedCount = evidence.filter((item) => item.observed).length; const unknownCount = evidence.length - observedCount; const changeCount = changes.filter((item) => item.changed).length; const latest = evidence.length === 0 ? null : evidence[evidence.length - 1]; const state = stateFor(selected.length, requiredSamples, observedCount, unknownCount, changeCount, requiredPersistence, latest ? latest.declared : null);
  return Object.freeze({ protocolVersion: 1, turbo: WORKLOAD_DECLARATION_STABILITY_TURBO_ID, turboVersion: WORKLOAD_DECLARATION_STABILITY_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, observedCount, unknownCount, comparisonCount: changes.length, changeCount, declarationChangeCount: changes.filter((item) => item.declarationChanged).length, interactiveChangeCount: changes.filter((item) => item.interactiveChanged).length, finalEnvironment: latest ? latest.environment : 'unknown', finalDeclared: latest ? latest.declared : null, finalInteractive: latest ? latest.interactive : null, state, confidence: selected.length === 0 ? 0 : Math.round((observedCount / selected.length) * 10000) / 10000, recommendations: recommendations(state), actions: EMPTY_ARRAY });
}
