/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Mesh-evidence turbo. It compares explicit mesh membership evidence without
 * changing interfaces, routes, or network settings.
 */

export const NETWORK_OBSERVATION_MESH_EVIDENCE_TURBO_ID = 'network-observation.mesh-evidence';
export const NETWORK_OBSERVATION_MESH_EVIDENCE_TURBO_VERSION = 1;
export const NETWORK_OBSERVATION_MESH_EVIDENCE_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Mesh-evidence snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Mesh-evidence requires a system-facts snapshot'); if (!Array.isArray(snapshot.network)) throw new TypeError('Mesh-evidence snapshot requires a network list'); return snapshot; }
function requireTrigger(trigger) { if (!NETWORK_OBSERVATION_MESH_EVIDENCE_TRIGGERS.includes(trigger)) throw new Error(`Unsupported mesh-evidence trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Mesh-evidence windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Mesh-evidence minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Mesh-evidence ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Mesh-evidence clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot, previous) { const source = requireSnapshot(snapshot); const rows = source.network.filter(isRecord); const identities = rows.filter((link) => link.mesh === true).map((link) => `${text(link.name) || 'unnamed'}|${text(link.kind) || 'unknown'}`); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', linkCount: rows.length, meshCount: identities.length, unknownMeshCount: 0, meshChangeCount: 0, comparisonCount: 0, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-network', linkCount: 0, meshCount: 0, unknownMeshCount: 0, meshChangeCount: 0, comparisonCount: 0, review: false }); const unknownMeshCount = rows.filter((link) => typeof link.mesh !== 'boolean').length; if (unknownMeshCount > 0) return Object.freeze({ state: 'incomplete', linkCount: rows.length, meshCount: identities.length, unknownMeshCount, meshChangeCount: 0, comparisonCount: 0, review: false }); const previousIdentities = previous?.identities || []; const comparable = previous?.state === 'observed'; const meshChanged = comparable && (identities.length !== previousIdentities.length || identities.some((identity) => !previousIdentities.includes(identity))); const meshChangeCount = meshChanged ? Math.max(identities.length, previousIdentities.length) : 0; return Object.freeze({ state: 'observed', linkCount: rows.length, meshCount: identities.length, unknownMeshCount: 0, meshChangeCount, comparisonCount: comparable ? 1 : 0, review: meshChanged, identities }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, changeSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-network')) return 'no-network'; if (incompleteCount > 0) return 'incomplete-evidence'; if (changeSampleCount >= persistenceThreshold) return 'mesh-drift-sustained'; if (changeSampleCount > 0) return 'mesh-drift-observed'; return 'stable-mesh-evidence'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-mesh-evidence']); if (state === 'no-network') return Object.freeze(['no-network-mesh-review']); if (state === 'incomplete-evidence') return Object.freeze(['request-explicit-mesh-evidence']); if (state === 'mesh-drift-sustained') return Object.freeze(['review-mesh-evidence-drift-without-network-mutation']); if (state === 'mesh-drift-observed') return Object.freeze(['observe-mesh-evidence-stability']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runNetworkObservationMeshEvidenceTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Mesh-evidence samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = []; let previous; for (const sample of selected) { const current = aggregate(sample, previous); evidence.push(current); previous = current; } const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noNetworkCount = evidence.filter((item) => item.state === 'no-network').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const comparisonCount = evidence.reduce((sum, item) => sum + item.comparisonCount, 0); const meshChangeSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const latest = evidence.at(-1) || Object.freeze({ linkCount: 0, meshCount: 0, unknownMeshCount: 0, meshChangeCount: 0 }); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, meshChangeSampleCount, requiredPersistence); return Object.freeze({ protocolVersion: 1, turbo: NETWORK_OBSERVATION_MESH_EVIDENCE_TURBO_ID, turboVersion: NETWORK_OBSERVATION_MESH_EVIDENCE_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, linkCount: latest.linkCount, meshCount: latest.meshCount, unknownMeshCount: latest.unknownMeshCount, meshChangeCount: latest.meshChangeCount, observedCount, incompleteCount, noNetworkCount, comparisonCount, meshChangeSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
