/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Evidence-drift turbo. It observes bounded documented/unverified driver
 * evidence without installing, replacing, loading, or changing drivers.
 */

export const DRIVER_CAPABILITY_EVIDENCE_DRIFT_TURBO_ID = 'driver-capability.evidence-drift';
export const DRIVER_CAPABILITY_EVIDENCE_DRIFT_TURBO_VERSION = 1;
export const DRIVER_CAPABILITY_EVIDENCE_DRIFT_TRIGGERS = Object.freeze(['install.preflight', 'system.facts.request', 'workload.changed', 'health.interval']);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']); const STATES = Object.freeze(['documented', 'unverified', 'unknown']); const EMPTY_ARRAY = Object.freeze([]);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function evidenceOf(driver) { if (driver.documented === true) return 'documented'; if (driver.documented === false) return 'unverified'; return 'unknown'; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Evidence-drift snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Evidence-drift requires a system-facts snapshot'); if (!Array.isArray(snapshot.drivers)) throw new TypeError('Evidence-drift snapshot requires a driver list'); return snapshot; }
function requireTrigger(trigger) { if (!DRIVER_CAPABILITY_EVIDENCE_DRIFT_TRIGGERS.includes(trigger)) throw new Error(`Unsupported evidence-drift trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Evidence-drift windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Evidence-drift minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Evidence-drift ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Evidence-drift clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot) { const source = requireSnapshot(snapshot); const rows = source.drivers.filter(isRecord).map(evidenceOf); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', driverCount: rows.length, unverifiedCount: 0, unknownCount: rows.length, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-drivers', driverCount: 0, unverifiedCount: 0, unknownCount: 0, review: false }); const unverifiedCount = rows.filter((value) => value === 'unverified').length; const unknownCount = rows.filter((value) => value === 'unknown').length; return Object.freeze({ state: 'observed', driverCount: rows.length, unverifiedCount, unknownCount, review: unverifiedCount > 0 || unknownCount > 0 }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, reviewSampleCount, unverifiedSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-drivers')) return 'no-drivers'; if (incompleteCount > 0) return 'incomplete-evidence'; if (unverifiedSampleCount >= persistenceThreshold) return 'unverified-sustained'; if (reviewSampleCount > 0) return 'evidence-review-observed'; return 'documented-drivers'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-driver-evidence']); if (state === 'no-drivers') return Object.freeze(['no-driver-capability-review']); if (state === 'incomplete-evidence') return Object.freeze(['request-environment-profile']); if (state === 'unverified-sustained') return Object.freeze(['review-driver-source-without-change']); if (state === 'evidence-review-observed') return Object.freeze(['request-driver-capability-observation']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }
export function runDriverCapabilityEvidenceDriftTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Evidence-drift samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = selected.map(aggregate); const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noDriverCount = evidence.filter((item) => item.state === 'no-drivers').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const reviewSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const unverifiedSampleCount = evidence.filter((item) => item.state === 'observed' && item.unverifiedCount > 0).length; const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, reviewSampleCount, unverifiedSampleCount, requiredPersistence); const latest = evidence.at(-1) || Object.freeze({ driverCount: 0, unverifiedCount: 0, unknownCount: 0 }); return Object.freeze({ protocolVersion: 1, turbo: DRIVER_CAPABILITY_EVIDENCE_DRIFT_TURBO_ID, turboVersion: DRIVER_CAPABILITY_EVIDENCE_DRIFT_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, driverCount: latest.driverCount, unverifiedCount: latest.unverifiedCount, unknownCount: latest.unknownCount, observedCount, incompleteCount, noDriverCount, reviewSampleCount, unverifiedSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
