/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Dedicated safety-audit admin-boundary library. It validates privilege
 * evidence and exposes review-only plans with an explicit admin boundary.
 */
export const SAFETY_ADMIN_BOUNDARY_LIBRARY_ID = 'safety-audit.admin-boundary.library';
export const SAFETY_ADMIN_BOUNDARY_LIBRARY_VERSION = 1;
const STATES = Object.freeze(['normal-user-boundary', 'admin-review', 'admin-boundary-drift-observed', 'admin-boundary-drift-sustained', 'observation-required', 'admin-unknown', 'insufficient-data']); const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function requireReport(report) { if (!isRecord(report)) throw new TypeError('Admin-boundary library report must be an object'); if (report.turbo !== 'safety-audit.admin-boundary') throw new Error('Admin-boundary library requires an admin-boundary turbo report'); if (!STATES.includes(report.state)) throw new Error('Admin-boundary library report has an invalid state'); if (!Number.isInteger(report.sampleCount) || report.sampleCount < 0 || report.sampleCount > 64) throw new RangeError('Admin-boundary library sampleCount must be from 0 to 64'); if (!Number.isInteger(report.minimumSamples) || report.minimumSamples < 1 || report.minimumSamples > 64) throw new RangeError('Admin-boundary library minimumSamples must be from 1 to 64'); if (!Number.isInteger(report.persistenceThreshold) || report.persistenceThreshold < 1 || report.persistenceThreshold > 64) throw new RangeError('Admin-boundary library persistenceThreshold must be from 1 to 64'); for (const [field, label] of [['observedCount', 'observed count'], ['unknownCount', 'unknown count'], ['comparisonCount', 'comparison count'], ['changeCount', 'change count']]) if (!Number.isInteger(report[field]) || report[field] < 0 || report[field] > 4096) throw new RangeError(`Admin-boundary library ${label} must be from 0 to 4096`); if (!ENVIRONMENTS.includes(report.finalEnvironment)) throw new TypeError('Admin-boundary library finalEnvironment must be normalized'); if (report.finalAdminRequired !== null && typeof report.finalAdminRequired !== 'boolean') throw new TypeError('Admin-boundary library finalAdminRequired must be boolean or null'); if (!Number.isFinite(report.confidence) || report.confidence < 0 || report.confidence > 1) throw new RangeError('Admin-boundary library confidence must be between 0 and 1'); return report; }
function requireReports(reports) { if (!Array.isArray(reports)) throw new TypeError('Admin-boundary library reports must be an array'); if (reports.length > 64) throw new RangeError('Admin-boundary library accepts at most 64 reports'); return Object.freeze(reports.map(requireReport)); }
function mergedState(reports) { if (reports.length === 0) return 'insufficient-data'; if (reports.some((report) => report.state === 'admin-unknown')) return 'admin-unknown'; if (reports.some((report) => report.state === 'observation-required')) return 'observation-required'; if (reports.some((report) => report.state === 'admin-boundary-drift-sustained')) return 'admin-boundary-drift-sustained'; if (reports.some((report) => report.state === 'admin-boundary-drift-observed')) return 'admin-boundary-drift-observed'; if (reports.some((report) => report.state === 'admin-review')) return 'admin-review'; if (reports.every((report) => report.state === 'insufficient-data')) return 'insufficient-data'; return 'normal-user-boundary'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-admin-boundary-evidence']); if (state === 'admin-unknown') return Object.freeze(['request-admin-boundary-evidence']); if (state === 'observation-required') return Object.freeze(['request-complete-admin-boundary-observation']); if (state === 'admin-boundary-drift-sustained') return Object.freeze(['review-admin-boundary-drift']); if (state === 'admin-boundary-drift-observed') return Object.freeze(['observe-admin-boundary-stability']); if (state === 'admin-review') return Object.freeze(['show-admin-required-boundary']); return Object.freeze(['preserve-normal-user-boundary']); }
function environmentOf(value) { return ENVIRONMENTS.includes(value) ? value : 'unknown'; }
function planMode(state, environment) { if (environment === 'unknown') return 'profile-required'; if (state === 'admin-unknown' || state === 'observation-required') return 'evidence-bootstrap'; if (state === 'admin-boundary-drift-sustained') return 'admin-boundary-review'; if (state === 'admin-boundary-drift-observed') return 'admin-boundary-observation'; if (state === 'admin-review') return 'admin-review'; if (state === 'insufficient-data') return 'sample-bootstrap'; return 'normal-user-observation'; }
function intervalFor(state, environment) { if (state === 'admin-unknown' || state === 'observation-required' || state === 'insufficient-data') return 2000; if (state === 'admin-boundary-drift-sustained') return 750; if (state === 'admin-boundary-drift-observed') return 1500; if (state === 'admin-review') return 2500; return environment === 'headless' ? 10000 : 5000; }
export function mergeSafetyAdminBoundaryReports(reports) { const validated = requireReports(reports); const state = mergedState(validated); const latest = validated.at(-1); return Object.freeze({ library: SAFETY_ADMIN_BOUNDARY_LIBRARY_ID, libraryVersion: SAFETY_ADMIN_BOUNDARY_LIBRARY_VERSION, reportCount: validated.length, state, sampleCount: validated.reduce((sum, report) => sum + report.sampleCount, 0), observedCount: validated.reduce((sum, report) => sum + report.observedCount, 0), unknownCount: validated.reduce((sum, report) => sum + report.unknownCount, 0), comparisonCount: validated.reduce((sum, report) => sum + report.comparisonCount, 0), changeCount: validated.reduce((sum, report) => sum + report.changeCount, 0), finalEnvironment: latest?.finalEnvironment || 'unknown', finalAdminRequired: latest?.finalAdminRequired ?? null, confidence: latest?.confidence || 0, recommendations: recommendations(state) }); }
export function buildSafetyAdminBoundaryPlan(report, environment) { const validated = requireReport(report); const normalizedEnvironment = environmentOf(environment); return Object.freeze({ library: SAFETY_ADMIN_BOUNDARY_LIBRARY_ID, environment: normalizedEnvironment, mode: planMode(validated.state, normalizedEnvironment), intervalMs: intervalFor(validated.state, normalizedEnvironment), state: validated.state, confidence: validated.sampleCount === 0 ? 0 : validated.confidence }); }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Admin-boundary library clock must return a number'); return timestamp; }
export function buildSafetyAdminBoundaryEnvelope(report, { trigger, now = Date.now } = {}) { if (typeof trigger !== 'string' || trigger.length === 0) throw new TypeError('Admin-boundary library trigger is required'); return Object.freeze({ library: SAFETY_ADMIN_BOUNDARY_LIBRARY_ID, libraryVersion: SAFETY_ADMIN_BOUNDARY_LIBRARY_VERSION, trigger, generatedAt: new Date(requireClock(now)).toISOString(), report: requireReport(report) }); }
export function createSafetyAdminBoundaryLibrary() { return Object.freeze({ id: SAFETY_ADMIN_BOUNDARY_LIBRARY_ID, version: SAFETY_ADMIN_BOUNDARY_LIBRARY_VERSION, merge: mergeSafetyAdminBoundaryReports, plan: buildSafetyAdminBoundaryPlan, envelope: buildSafetyAdminBoundaryEnvelope }); }
