/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Safety-audit admin-boundary turbo. It reports explicit privilege boundaries
 * without requesting elevation or executing an administrative action.
 */
export const SAFETY_ADMIN_BOUNDARY_TURBO_ID = 'safety-audit.admin-boundary';
export const SAFETY_ADMIN_BOUNDARY_TURBO_VERSION = 1;
export const SAFETY_ADMIN_BOUNDARY_TRIGGERS = Object.freeze(['install.preflight', 'system.facts.request', 'workload.changed', 'health.interval']);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']); const EMPTY_ARRAY = Object.freeze([]);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function booleanOrNull(value) { return typeof value === 'boolean' ? value : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Safety-audit admin-boundary snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Safety-audit admin-boundary requires a system-facts snapshot'); if (!isRecord(snapshot.audit)) throw new TypeError('Safety-audit admin-boundary snapshot requires an audit object'); return snapshot; }
function evidenceOf(snapshot) { const source = requireSnapshot(snapshot); const adminRequired = booleanOrNull(source.audit.adminRequired); return Object.freeze({ environment: ENVIRONMENTS.includes(source.environment) ? source.environment : 'unknown', adminRequired, observed: adminRequired !== null, signature: adminRequired === null ? '?' : String(adminRequired) }); }
function requireTrigger(trigger) { if (!SAFETY_ADMIN_BOUNDARY_TRIGGERS.includes(trigger)) throw new Error(`Unsupported safety-audit admin-boundary trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindow(value) { if (!Number.isInteger(value) || value < 2 || value > 64) throw new RangeError('Safety-audit admin-boundary windowSize must be an integer from 2 to 64'); return value; }
function requireMinimum(value, windowSize) { if (!Number.isInteger(value) || value < 1 || value > windowSize) throw new RangeError('Safety-audit admin-boundary minimumSamples must fit inside the window'); return value; }
function requireThreshold(value, windowSize) { if (!Number.isInteger(value) || value < 1 || value > windowSize) throw new RangeError('Safety-audit admin-boundary persistenceThreshold must fit inside the window'); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Safety-audit admin-boundary clock must return a number'); return timestamp; }
function stateFor(sampleCount, minimumSamples, observedCount, unknownCount, changeCount, persistenceThreshold, finalAdmin) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (observedCount === 0) return 'admin-unknown'; if (unknownCount > 0) return 'observation-required'; if (changeCount >= persistenceThreshold) return 'admin-boundary-drift-sustained'; if (changeCount > 0) return 'admin-boundary-drift-observed'; if (finalAdmin === true) return 'admin-review'; return 'normal-user-boundary'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-admin-boundary-evidence']); if (state === 'admin-unknown') return Object.freeze(['request-admin-boundary-evidence']); if (state === 'observation-required') return Object.freeze(['request-complete-admin-boundary-observation']); if (state === 'admin-boundary-drift-sustained') return Object.freeze(['review-admin-boundary-drift']); if (state === 'admin-boundary-drift-observed') return Object.freeze(['observe-admin-boundary-stability']); if (state === 'admin-review') return Object.freeze(['show-admin-required-boundary']); return Object.freeze(['preserve-normal-user-boundary']); }
export function runSafetyAdminBoundaryTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Safety-audit admin-boundary samples must be an array'); const boundedWindow = requireWindow(windowSize); const requiredSamples = requireMinimum(minimumSamples, boundedWindow); const requiredPersistence = requireThreshold(persistenceThreshold, boundedWindow); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = selected.map(evidenceOf); const changes = evidence.slice(1).map((current, index) => Object.freeze({ changed: current.signature !== evidence[index].signature })); const observedCount = evidence.filter((item) => item.observed).length; const unknownCount = evidence.length - observedCount; const changeCount = changes.filter((item) => item.changed).length; const latest = evidence.length === 0 ? null : evidence[evidence.length - 1]; const state = stateFor(selected.length, requiredSamples, observedCount, unknownCount, changeCount, requiredPersistence, latest ? latest.adminRequired : null); return Object.freeze({ protocolVersion: 1, turbo: SAFETY_ADMIN_BOUNDARY_TURBO_ID, turboVersion: SAFETY_ADMIN_BOUNDARY_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, observedCount, unknownCount, comparisonCount: changes.length, changeCount, finalEnvironment: latest ? latest.environment : 'unknown', finalAdminRequired: latest ? latest.adminRequired : null, state, confidence: selected.length === 0 ? 0 : Math.round((observedCount / selected.length) * 10000) / 10000, recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
