/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Encryption-drift turbo. It compares explicit encryption evidence without
 * changing links, routes, or network settings.
 */

export const NETWORK_SAFETY_ENCRYPTION_DRIFT_TURBO_ID = 'network-safety.encryption-drift';
export const NETWORK_SAFETY_ENCRYPTION_DRIFT_TURBO_VERSION = 1;
export const NETWORK_SAFETY_ENCRYPTION_DRIFT_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Encryption-drift snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Encryption-drift requires a system-facts snapshot'); if (!Array.isArray(snapshot.network)) throw new TypeError('Encryption-drift snapshot requires a network list'); return snapshot; }
function requireTrigger(trigger) { if (!NETWORK_SAFETY_ENCRYPTION_DRIFT_TRIGGERS.includes(trigger)) throw new Error(`Unsupported encryption-drift trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Encryption-drift windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Encryption-drift minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Encryption-drift ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Encryption-drift clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot, previous) { const source = requireSnapshot(snapshot); const rows = source.network.filter(isRecord).map((link) => ({ key: `${text(link.name) || 'unnamed'}|${text(link.kind) || 'unknown'}`, encrypted: typeof link.encrypted === 'boolean' ? link.encrypted : null })); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', linkCount: rows.length, encryptedCount: rows.filter((row) => row.encrypted === true).length, unknownEncryptionCount: rows.filter((row) => row.encrypted === null).length, encryptionChangeCount: 0, comparisonCount: 0, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-network', linkCount: 0, encryptedCount: 0, unknownEncryptionCount: 0, encryptionChangeCount: 0, comparisonCount: 0, review: false }); const unknownEncryptionCount = rows.filter((row) => row.encrypted === null).length; if (unknownEncryptionCount > 0) return Object.freeze({ state: 'incomplete', linkCount: rows.length, encryptedCount: rows.filter((row) => row.encrypted === true).length, unknownEncryptionCount, encryptionChangeCount: 0, comparisonCount: 0, review: false }); const previousRows = previous?.rows || []; const previousMap = new Map(previousRows.map((row) => [row.key, row.encrypted])); const comparable = previous?.state === 'observed'; const encryptionChangeCount = comparable ? rows.filter((row) => previousMap.get(row.key) !== undefined && previousMap.get(row.key) !== row.encrypted).length : 0; return Object.freeze({ state: 'observed', linkCount: rows.length, encryptedCount: rows.filter((row) => row.encrypted === true).length, unknownEncryptionCount: 0, encryptionChangeCount, comparisonCount: comparable ? 1 : 0, review: encryptionChangeCount > 0, rows }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, changeSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-network')) return 'no-network'; if (incompleteCount > 0) return 'incomplete-evidence'; if (changeSampleCount >= persistenceThreshold) return 'encryption-drift-sustained'; if (changeSampleCount > 0) return 'encryption-drift-observed'; return 'stable-encryption'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-encryption-evidence']); if (state === 'no-network') return Object.freeze(['no-network-encryption-review']); if (state === 'incomplete-evidence') return Object.freeze(['request-explicit-encryption-evidence']); if (state === 'encryption-drift-sustained') return Object.freeze(['review-encryption-drift-without-network-mutation']); if (state === 'encryption-drift-observed') return Object.freeze(['observe-encryption-stability']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runNetworkSafetyEncryptionDriftTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Encryption-drift samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = []; let previous; for (const sample of selected) { const current = aggregate(sample, previous); evidence.push(current); previous = current; } const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noNetworkCount = evidence.filter((item) => item.state === 'no-network').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const comparisonCount = evidence.reduce((sum, item) => sum + item.comparisonCount, 0); const encryptionChangeSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const latest = evidence.at(-1) || Object.freeze({ linkCount: 0, encryptedCount: 0, unknownEncryptionCount: 0, encryptionChangeCount: 0 }); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, encryptionChangeSampleCount, requiredPersistence); return Object.freeze({ protocolVersion: 1, turbo: NETWORK_SAFETY_ENCRYPTION_DRIFT_TURBO_ID, turboVersion: NETWORK_SAFETY_ENCRYPTION_DRIFT_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, linkCount: latest.linkCount, encryptedCount: latest.encryptedCount, unknownEncryptionCount: latest.unknownEncryptionCount, encryptionChangeCount: latest.encryptionChangeCount, observedCount, incompleteCount, noNetworkCount, comparisonCount, encryptionChangeSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
