/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Identity-completeness turbo. It observes missing bounded driver identity
 * fields without installing, replacing, loading, or changing drivers.
 */

export const DRIVER_CAPABILITY_IDENTITY_COMPLETENESS_TURBO_ID = 'driver-capability.identity-completeness';
export const DRIVER_CAPABILITY_IDENTITY_COMPLETENESS_TURBO_VERSION = 1;
export const DRIVER_CAPABILITY_IDENTITY_COMPLETENESS_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const IDENTITY_FIELDS = Object.freeze(['name', 'vendor', 'version']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Identity-completeness snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Identity-completeness requires a system-facts snapshot'); if (!Array.isArray(snapshot.drivers)) throw new TypeError('Identity-completeness snapshot requires a driver list'); return snapshot; }
function requireTrigger(trigger) { if (!DRIVER_CAPABILITY_IDENTITY_COMPLETENESS_TRIGGERS.includes(trigger)) throw new Error(`Unsupported identity-completeness trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Identity-completeness windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Identity-completeness minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Identity-completeness ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Identity-completeness clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function identityOf(driver) { const missing = IDENTITY_FIELDS.filter((field) => text(driver[field]) === null); if (typeof driver.documented !== 'boolean') missing.push('documented'); return Object.freeze({ complete: missing.length === 0, missing }); }
function aggregate(snapshot) { const source = requireSnapshot(snapshot); const rows = source.drivers.filter(isRecord); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', driverCount: rows.length, completeCount: 0, incompleteRowCount: rows.length, missingFieldCount: rows.length * IDENTITY_FIELDS.length, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-drivers', driverCount: 0, completeCount: 0, incompleteRowCount: 0, missingFieldCount: 0, review: false }); const identities = rows.map(identityOf); const incompleteRowCount = identities.filter((identity) => !identity.complete).length; const missingFieldCount = identities.reduce((sum, identity) => sum + identity.missing.length, 0); return Object.freeze({ state: 'observed', driverCount: rows.length, completeCount: rows.length - incompleteRowCount, incompleteRowCount, missingFieldCount, review: incompleteRowCount > 0 }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, gapSampleCount, sustainedGapCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-drivers')) return 'no-drivers'; if (incompleteCount > 0) return 'incomplete-evidence'; if (sustainedGapCount >= persistenceThreshold) return 'identity-gap-sustained'; if (gapSampleCount > 0) return 'identity-gap-observed'; return 'complete-identity'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-driver-identity']); if (state === 'no-drivers') return Object.freeze(['no-driver-identity-review']); if (state === 'incomplete-evidence') return Object.freeze(['request-environment-profile']); if (state === 'identity-gap-sustained') return Object.freeze(['review-driver-identity-source-without-change']); if (state === 'identity-gap-observed') return Object.freeze(['request-driver-identity-observation']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runDriverCapabilityIdentityCompletenessTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Identity-completeness samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = selected.map(aggregate); const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noDriverCount = evidence.filter((item) => item.state === 'no-drivers').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const gapSampleCount = evidence.filter((item) => item.state === 'observed' && item.incompleteRowCount > 0).length; const sustainedGapCount = evidence.filter((item) => item.state === 'observed' && item.incompleteRowCount > 0).length; const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, gapSampleCount, sustainedGapCount, requiredPersistence); const latest = evidence.at(-1) || Object.freeze({ driverCount: 0, completeCount: 0, incompleteRowCount: 0, missingFieldCount: 0 }); return Object.freeze({ protocolVersion: 1, turbo: DRIVER_CAPABILITY_IDENTITY_COMPLETENESS_TURBO_ID, turboVersion: DRIVER_CAPABILITY_IDENTITY_COMPLETENESS_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, driverCount: latest.driverCount, completeCount: latest.completeCount, incompleteRowCount: latest.incompleteRowCount, missingFieldCount: latest.missingFieldCount, observedCount, incompleteCount, noDriverCount, gapSampleCount, sustainedGapCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
