/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Safety-evidence turbo. It aggregates explicit review, observed, and unknown
 * risk evidence without changing links, routes, or network settings.
 */

export const NETWORK_SAFETY_SAFETY_EVIDENCE_TURBO_ID = 'network-safety.safety-evidence';
export const NETWORK_SAFETY_SAFETY_EVIDENCE_TURBO_VERSION = 1;
export const NETWORK_SAFETY_SAFETY_EVIDENCE_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function riskOf(link) { if (link.trusted === false) return 'review'; if (link.public === true && link.encrypted !== true) return 'review'; if (link.trusted === true && (link.encrypted === true || link.public !== true)) return 'observed'; return 'unknown'; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Safety-evidence snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Safety-evidence requires a system-facts snapshot'); if (!Array.isArray(snapshot.network)) throw new TypeError('Safety-evidence snapshot requires a network list'); return snapshot; }
function requireTrigger(trigger) { if (!NETWORK_SAFETY_SAFETY_EVIDENCE_TRIGGERS.includes(trigger)) throw new Error(`Unsupported safety-evidence trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Safety-evidence windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Safety-evidence minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Safety-evidence ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Safety-evidence clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot, previous) { const source = requireSnapshot(snapshot); const rows = source.network.filter(isRecord).map((link) => ({ key: `${text(link.name) || 'unnamed'}|${text(link.kind) || 'unknown'}`, risk: riskOf(link) })); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', linkCount: rows.length, reviewCount: 0, unknownCount: 0, observedCount: 0, riskChangeCount: 0, comparisonCount: 0, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-network', linkCount: 0, reviewCount: 0, unknownCount: 0, observedCount: 0, riskChangeCount: 0, comparisonCount: 0, review: false }); const reviewCount = rows.filter((row) => row.risk === 'review').length; const unknownCount = rows.filter((row) => row.risk === 'unknown').length; const observedCount = rows.filter((row) => row.risk === 'observed').length; const previousRows = previous?.rows || []; const previousMap = new Map(previousRows.map((row) => [row.key, row.risk])); const comparable = previous?.state === 'observed'; const riskChangeCount = comparable ? rows.filter((row) => previousMap.get(row.key) !== undefined && previousMap.get(row.key) !== row.risk).length : 0; return Object.freeze({ state: 'observed', linkCount: rows.length, reviewCount, unknownCount, observedCount, riskChangeCount, comparisonCount: comparable ? 1 : 0, review: reviewCount > 0, rows }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, reviewSampleCount, unknownSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-network')) return 'no-network'; if (incompleteCount > 0) return 'incomplete-evidence'; if (reviewSampleCount >= persistenceThreshold) return 'review-risk-sustained'; if (reviewSampleCount > 0) return 'review-risk-observed'; if (unknownSampleCount > 0) return 'unknown-risk-evidence'; return 'observed-safe-evidence'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-safety-evidence']); if (state === 'no-network') return Object.freeze(['no-network-safety-review']); if (state === 'incomplete-evidence') return Object.freeze(['request-network-environment-profile']); if (state === 'review-risk-sustained') return Object.freeze(['review-network-safety-evidence-without-network-mutation']); if (state === 'review-risk-observed') return Object.freeze(['observe-network-safety-review-state']); if (state === 'unknown-risk-evidence') return Object.freeze(['request-network-safety-observation']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runNetworkSafetySafetyEvidenceTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Safety-evidence samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = []; let previous; for (const sample of selected) { const current = aggregate(sample, previous); evidence.push(current); previous = current; } const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noNetworkCount = evidence.filter((item) => item.state === 'no-network').length; const observedSampleCount = evidence.filter((item) => item.state === 'observed').length; const reviewSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const unknownSampleCount = evidence.filter((item) => item.state === 'observed' && item.unknownCount > 0).length; const latest = evidence.at(-1) || Object.freeze({ linkCount: 0, reviewCount: 0, unknownCount: 0, observedCount: 0, riskChangeCount: 0 }); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, reviewSampleCount, unknownSampleCount, requiredPersistence); return Object.freeze({ protocolVersion: 1, turbo: NETWORK_SAFETY_SAFETY_EVIDENCE_TURBO_ID, turboVersion: NETWORK_SAFETY_SAFETY_EVIDENCE_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, linkCount: latest.linkCount, reviewCount: latest.reviewCount, unknownCount: latest.unknownCount, observedCount: latest.observedCount, riskChangeCount: latest.riskChangeCount, observedSampleCount, incompleteCount, noNetworkCount, reviewSampleCount, unknownSampleCount, state, confidence: confidence(selected.length, observedSampleCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
