/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Dedicated resource-pressure library for bounded report merging and plans.
 */

export const WORKSTATION_RESOURCE_PRESSURE_LIBRARY_ID = 'workstation-health.resource-pressure.library';
export const WORKSTATION_RESOURCE_PRESSURE_LIBRARY_VERSION = 1;
const STATES = Object.freeze(['insufficient-data', 'observation-required', 'critical-pressure', 'pressure-observed', 'stable-resources']);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function requireReport(report) { if (!isRecord(report)) throw new TypeError('Resource-pressure library report must be an object'); if (report.turbo !== 'workstation-health.resource-pressure') throw new Error('Resource-pressure library requires a resource-pressure turbo report'); if (!STATES.includes(report.state)) throw new Error('Resource-pressure library report has an invalid state'); if (!Number.isFinite(report.confidence) || report.confidence < 0 || report.confidence > 1) throw new RangeError('Resource-pressure library confidence must be between 0 and 1'); return report; }
function reportsOf(reports) { if (!Array.isArray(reports)) throw new TypeError('Resource-pressure library reports must be an array'); if (reports.length > 64) throw new RangeError('Resource-pressure library accepts at most 64 reports'); return Object.freeze(reports.map(requireReport)); }
function stateOf(reports) { if (!reports.length) return 'insufficient-data'; if (reports.some((report) => report.state === 'critical-pressure')) return 'critical-pressure'; if (reports.some((report) => report.state === 'observation-required')) return 'observation-required'; if (reports.some((report) => report.state === 'pressure-observed')) return 'pressure-observed'; if (reports.every((report) => report.state === 'insufficient-data')) return 'insufficient-data'; return 'stable-resources'; }
function recommendations(state) { if (state === 'critical-pressure') return Object.freeze(['review-thermal-and-resource-pressure']); if (state === 'pressure-observed') return Object.freeze(['observe-next-resource-sample']); if (state === 'observation-required') return Object.freeze(['request-resource-observation']); if (state === 'insufficient-data') return Object.freeze(['collect-more-resource-samples']); return Object.freeze(['no-change']); }
export function mergeWorkstationResourcePressureReports(reports) { const validated = reportsOf(reports); const state = stateOf(validated); const latest = validated.at(-1); return Object.freeze({ library: WORKSTATION_RESOURCE_PRESSURE_LIBRARY_ID, libraryVersion: WORKSTATION_RESOURCE_PRESSURE_LIBRARY_VERSION, reportCount: validated.length, state, maximumPressure: latest?.maximumPressure || 'normal', criticalCount: validated.reduce((sum, report) => sum + (report.criticalCount || 0), 0), warningCount: validated.reduce((sum, report) => sum + (report.warningCount || 0), 0), confidence: latest?.confidence || 0, recommendations: recommendations(state) }); }
export function buildWorkstationResourcePressurePlan(report, environment = 'unknown') { const validated = requireReport(report); return Object.freeze({ library: WORKSTATION_RESOURCE_PRESSURE_LIBRARY_ID, environment, mode: environment === 'unknown' ? 'profile-required' : validated.state === 'critical-pressure' ? 'thermal-resource-review' : 'resource-observation', intervalMs: validated.state === 'critical-pressure' ? 300000 : 3600000, state: validated.state, confidence: validated.confidence }); }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Resource-pressure library clock must return a number'); return timestamp; }
export function buildWorkstationResourcePressureEnvelope(report, { trigger, now = Date.now } = {}) { if (typeof trigger !== 'string' || !trigger) throw new TypeError('Resource-pressure library trigger is required'); return Object.freeze({ library: WORKSTATION_RESOURCE_PRESSURE_LIBRARY_ID, libraryVersion: WORKSTATION_RESOURCE_PRESSURE_LIBRARY_VERSION, trigger, generatedAt: new Date(requireClock(now)).toISOString(), report: requireReport(report) }); }
export function createWorkstationResourcePressureLibrary() { return Object.freeze({ id: WORKSTATION_RESOURCE_PRESSURE_LIBRARY_ID, version: WORKSTATION_RESOURCE_PRESSURE_LIBRARY_VERSION, merge: mergeWorkstationResourcePressureReports, plan: buildWorkstationResourcePressurePlan, envelope: buildWorkstationResourcePressureEnvelope }); }
