/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Dedicated storage-trend library for bounded daily report aggregation.
 */

export const WORKSTATION_STORAGE_TREND_LIBRARY_ID = 'workstation-health.storage-trend.library';
export const WORKSTATION_STORAGE_TREND_LIBRARY_VERSION = 1;
const STATES = Object.freeze(['insufficient-data', 'observation-required', 'free-space-loss', 'free-space-gain', 'stable-free-space']);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function requireReport(report) { if (!isRecord(report)) throw new TypeError('Storage-trend library report must be an object'); if (report.turbo !== 'workstation-health.storage-trend') throw new Error('Storage-trend library requires a storage-trend turbo report'); if (!STATES.includes(report.state)) throw new Error('Storage-trend library report has an invalid state'); if (!Number.isInteger(report.sampleCount) || report.sampleCount < 0 || report.sampleCount > 64) throw new RangeError('Storage-trend library sampleCount must be from 0 to 64'); if (!Number.isFinite(report.confidence) || report.confidence < 0 || report.confidence > 1) throw new RangeError('Storage-trend library confidence must be between 0 and 1'); return report; }
function reportsOf(reports) { if (!Array.isArray(reports)) throw new TypeError('Storage-trend library reports must be an array'); if (reports.length > 64) throw new RangeError('Storage-trend library accepts at most 64 reports'); return Object.freeze(reports.map(requireReport)); }
function stateOf(reports) { if (!reports.length) return 'insufficient-data'; if (reports.some((report) => report.state === 'observation-required')) return 'observation-required'; if (reports.some((report) => report.state === 'free-space-loss')) return 'free-space-loss'; if (reports.some((report) => report.state === 'free-space-gain')) return 'free-space-gain'; if (reports.every((report) => report.state === 'insufficient-data')) return 'insufficient-data'; return 'stable-free-space'; }
function recommendations(state) { if (state === 'free-space-loss') return Object.freeze(['review-storage-pressure-guard']); if (state === 'free-space-gain') return Object.freeze(['record-storage-recovery']); if (state === 'observation-required') return Object.freeze(['request-storage-trend-observation']); if (state === 'insufficient-data') return Object.freeze(['collect-more-storage-trend-samples']); return Object.freeze(['no-change']); }
export function mergeWorkstationStorageTrendReports(reports) { const validated = reportsOf(reports); const state = stateOf(validated); const latest = validated.at(-1); return Object.freeze({ library: WORKSTATION_STORAGE_TREND_LIBRARY_ID, libraryVersion: WORKSTATION_STORAGE_TREND_LIBRARY_VERSION, reportCount: validated.length, state, sampleCount: validated.reduce((sum, report) => sum + report.sampleCount, 0), observedCount: validated.reduce((sum, report) => sum + (report.observedCount || 0), 0), finalFreeBytes: latest?.finalFreeBytes ?? null, deltaBytes: latest?.deltaBytes ?? null, confidence: latest?.confidence || 0, recommendations: recommendations(state) }); }
export function buildWorkstationStorageTrendPlan(report, environment = 'unknown') { const validated = requireReport(report); const mode = environment === 'unknown' ? 'profile-required' : validated.state === 'free-space-loss' ? 'storage-review' : 'storage-observation'; return Object.freeze({ library: WORKSTATION_STORAGE_TREND_LIBRARY_ID, environment, mode, intervalMs: validated.state === 'free-space-loss' ? 900000 : 86400000, state: validated.state, confidence: validated.confidence }); }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Storage-trend library clock must return a number'); return timestamp; }
export function buildWorkstationStorageTrendEnvelope(report, { trigger, now = Date.now } = {}) { if (typeof trigger !== 'string' || !trigger) throw new TypeError('Storage-trend library trigger is required'); return Object.freeze({ library: WORKSTATION_STORAGE_TREND_LIBRARY_ID, libraryVersion: WORKSTATION_STORAGE_TREND_LIBRARY_VERSION, trigger, generatedAt: new Date(requireClock(now)).toISOString(), report: requireReport(report) }); }
export function createWorkstationStorageTrendLibrary() { return Object.freeze({ id: WORKSTATION_STORAGE_TREND_LIBRARY_ID, version: WORKSTATION_STORAGE_TREND_LIBRARY_VERSION, merge: mergeWorkstationStorageTrendReports, plan: buildWorkstationStorageTrendPlan, envelope: buildWorkstationStorageTrendEnvelope }); }
