/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Inventory-drift turbo. It compares bounded driver identity sets without
 * installing, replacing, loading, or changing drivers.
 */

export const DRIVER_CAPABILITY_INVENTORY_DRIFT_TURBO_ID = 'driver-capability.inventory-drift';
export const DRIVER_CAPABILITY_INVENTORY_DRIFT_TURBO_VERSION = 1;
export const DRIVER_CAPABILITY_INVENTORY_DRIFT_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function identityOf(driver) { const name = text(driver.name); const vendor = text(driver.vendor); return name && vendor ? `${vendor}|${name}` : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Inventory-drift snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Inventory-drift requires a system-facts snapshot'); if (!Array.isArray(snapshot.drivers)) throw new TypeError('Inventory-drift snapshot requires a driver list'); return snapshot; }
function requireTrigger(trigger) { if (!DRIVER_CAPABILITY_INVENTORY_DRIFT_TRIGGERS.includes(trigger)) throw new Error(`Unsupported inventory-drift trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Inventory-drift windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Inventory-drift minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Inventory-drift ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Inventory-drift clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot, previous) { const source = requireSnapshot(snapshot); const rows = source.drivers.filter(isRecord).map(identityOf); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', driverCount: rows.length, comparisonCount: 0, addedCount: 0, removedCount: 0, inventoryChangeCount: 0, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-drivers', driverCount: 0, comparisonCount: 0, addedCount: 0, removedCount: 0, inventoryChangeCount: 0, review: false }); if (rows.some((identity) => identity === null)) return Object.freeze({ state: 'incomplete', driverCount: rows.length, comparisonCount: 0, addedCount: 0, removedCount: 0, inventoryChangeCount: 0, review: false }); const identities = new Set(rows); const previousIdentities = previous?.identities || new Set(); const comparable = previous?.state === 'observed'; const addedCount = comparable ? [...identities].filter((identity) => !previousIdentities.has(identity)).length : 0; const removedCount = comparable ? [...previousIdentities].filter((identity) => !identities.has(identity)).length : 0; const inventoryChangeCount = addedCount + removedCount; return Object.freeze({ state: 'observed', driverCount: identities.size, comparisonCount: comparable ? 1 : 0, addedCount, removedCount, inventoryChangeCount, review: inventoryChangeCount > 0, identities }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, changeSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-drivers')) return 'no-drivers'; if (incompleteCount > 0) return 'incomplete-evidence'; if (changeSampleCount >= persistenceThreshold) return 'inventory-drift-sustained'; if (changeSampleCount > 0) return 'inventory-drift-observed'; return 'stable-inventory'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-driver-inventory']); if (state === 'no-drivers') return Object.freeze(['no-driver-inventory-review']); if (state === 'incomplete-evidence') return Object.freeze(['request-driver-inventory-evidence']); if (state === 'inventory-drift-sustained') return Object.freeze(['review-driver-inventory-drift-without-change']); if (state === 'inventory-drift-observed') return Object.freeze(['observe-driver-inventory-stability']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runDriverCapabilityInventoryDriftTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Inventory-drift samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = []; let previous; for (const sample of selected) { const current = aggregate(sample, previous); evidence.push(current); previous = current; } const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noDriverCount = evidence.filter((item) => item.state === 'no-drivers').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const comparisonCount = evidence.reduce((sum, item) => sum + item.comparisonCount, 0); const inventoryChangeSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const latest = evidence.at(-1) || Object.freeze({ driverCount: 0, addedCount: 0, removedCount: 0, inventoryChangeCount: 0 }); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, inventoryChangeSampleCount, requiredPersistence); return Object.freeze({ protocolVersion: 1, turbo: DRIVER_CAPABILITY_INVENTORY_DRIFT_TURBO_ID, turboVersion: DRIVER_CAPABILITY_INVENTORY_DRIFT_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, driverCount: latest.driverCount, addedCount: latest.addedCount, removedCount: latest.removedCount, inventoryChangeCount: latest.inventoryChangeCount, observedCount, incompleteCount, noDriverCount, comparisonCount, inventoryChangeSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
