/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Item-inventory turbo. It compares explicit organization item identities
 * without moving, renaming, deleting, overwriting, or inspecting files.
 */

export const ORGANIZATION_PREVIEW_ITEM_INVENTORY_TURBO_ID = 'organization-preview.item-inventory';
export const ORGANIZATION_PREVIEW_ITEM_INVENTORY_TURBO_VERSION = 1;
export const ORGANIZATION_PREVIEW_ITEM_INVENTORY_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Item-inventory snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Item-inventory requires a system-facts snapshot'); if (!isRecord(snapshot.organization)) throw new TypeError('Item-inventory snapshot requires an organization object'); if (!Array.isArray(snapshot.organization.items)) throw new TypeError('Item-inventory snapshot requires an organization item list'); return snapshot; }
function requireTrigger(trigger) { if (!ORGANIZATION_PREVIEW_ITEM_INVENTORY_TRIGGERS.includes(trigger)) throw new Error(`Unsupported item-inventory trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Item-inventory windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Item-inventory minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Item-inventory ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Item-inventory clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot, previous) { const source = requireSnapshot(snapshot); const rows = source.organization.items.filter(isRecord).map((item) => text(item.name)); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', itemCount: rows.length, addedCount: 0, removedCount: 0, inventoryChangeCount: 0, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-organization-preview', itemCount: 0, addedCount: 0, removedCount: 0, inventoryChangeCount: 0, review: false }); if (rows.some((name) => name === null)) return Object.freeze({ state: 'incomplete', itemCount: rows.length, addedCount: 0, removedCount: 0, inventoryChangeCount: 0, review: false }); const identities = new Set(rows); const previousIdentities = previous?.identities || new Set(); const comparable = previous?.state === 'observed'; const addedCount = comparable ? [...identities].filter((name) => !previousIdentities.has(name)).length : 0; const removedCount = comparable ? [...previousIdentities].filter((name) => !identities.has(name)).length : 0; const inventoryChangeCount = addedCount + removedCount; return Object.freeze({ state: 'observed', itemCount: identities.size, addedCount, removedCount, inventoryChangeCount, comparisonCount: comparable ? 1 : 0, review: inventoryChangeCount > 0, identities }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, changeSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-organization-preview')) return 'no-organization-preview'; if (incompleteCount > 0) return 'incomplete-evidence'; if (changeSampleCount >= persistenceThreshold) return 'item-drift-sustained'; if (changeSampleCount > 0) return 'item-drift-observed'; return 'stable-item-inventory'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-organization-items']); if (state === 'no-organization-preview') return Object.freeze(['no-organization-preview']); if (state === 'incomplete-evidence') return Object.freeze(['request-item-identity-observation']); if (state === 'item-drift-sustained') return Object.freeze(['review-item-inventory-drift-without-file-mutation']); if (state === 'item-drift-observed') return Object.freeze(['observe-item-inventory-stability']); return Object.freeze(['preview-proposals-only']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runOrganizationPreviewItemInventoryTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Item-inventory samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = []; let previous; for (const sample of selected) { const current = aggregate(sample, previous); evidence.push(current); previous = current; } const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noOrganizationCount = evidence.filter((item) => item.state === 'no-organization-preview').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const inventoryChangeSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const latest = evidence.at(-1) || Object.freeze({ itemCount: 0, addedCount: 0, removedCount: 0, inventoryChangeCount: 0 }); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, inventoryChangeSampleCount, requiredPersistence); return Object.freeze({ protocolVersion: 1, turbo: ORGANIZATION_PREVIEW_ITEM_INVENTORY_TURBO_ID, turboVersion: ORGANIZATION_PREVIEW_ITEM_INVENTORY_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, itemCount: latest.itemCount, addedCount: latest.addedCount, removedCount: latest.removedCount, inventoryChangeCount: latest.inventoryChangeCount, observedCount, incompleteCount, noOrganizationCount, inventoryChangeSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
