/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Dedicated safety-audit proposal-risk library. It validates action evidence
 * and creates review-only plans without executing proposals.
 */
export const SAFETY_PROPOSAL_RISK_LIBRARY_ID = 'safety-audit.proposal-risk.library';
export const SAFETY_PROPOSAL_RISK_LIBRARY_VERSION = 1;
const STATES = Object.freeze(['no-proposal', 'proposal-review', 'destructive-proposal', 'destructive-risk-observed', 'destructive-risk-sustained', 'observation-required', 'risk-unknown', 'insufficient-data']); const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function requireReport(report) { if (!isRecord(report)) throw new TypeError('Proposal-risk library report must be an object'); if (report.turbo !== 'safety-audit.proposal-risk') throw new Error('Proposal-risk library requires a proposal-risk turbo report'); if (!STATES.includes(report.state)) throw new Error('Proposal-risk library report has an invalid state'); if (!Number.isInteger(report.sampleCount) || report.sampleCount < 0 || report.sampleCount > 64) throw new RangeError('Proposal-risk library sampleCount must be from 0 to 64'); if (!Number.isInteger(report.minimumSamples) || report.minimumSamples < 1 || report.minimumSamples > 64) throw new RangeError('Proposal-risk library minimumSamples must be from 1 to 64'); if (!Number.isInteger(report.persistenceThreshold) || report.persistenceThreshold < 1 || report.persistenceThreshold > 64) throw new RangeError('Proposal-risk library persistenceThreshold must be from 1 to 64'); for (const [field, label] of [['observedCount', 'observed count'], ['unknownCount', 'unknown count'], ['comparisonCount', 'comparison count'], ['changeCount', 'change count'], ['actionChangeCount', 'action-change count'], ['destructiveChangeCount', 'destructive-change count']]) if (!Number.isInteger(report[field]) || report[field] < 0 || report[field] > 4096) throw new RangeError(`Proposal-risk library ${label} must be from 0 to 4096`); if (report.finalActionCount !== null && (!Number.isFinite(report.finalActionCount) || report.finalActionCount < 0)) throw new TypeError('Proposal-risk library finalActionCount must be non-negative or null'); if (report.finalDestructiveCount !== null && (!Number.isFinite(report.finalDestructiveCount) || report.finalDestructiveCount < 0)) throw new TypeError('Proposal-risk library finalDestructiveCount must be non-negative or null'); if (!ENVIRONMENTS.includes(report.finalEnvironment)) throw new TypeError('Proposal-risk library finalEnvironment must be normalized'); if (!Number.isFinite(report.confidence) || report.confidence < 0 || report.confidence > 1) throw new RangeError('Proposal-risk library confidence must be between 0 and 1'); return report; }
function requireReports(reports) { if (!Array.isArray(reports)) throw new TypeError('Proposal-risk library reports must be an array'); if (reports.length > 64) throw new RangeError('Proposal-risk library accepts at most 64 reports'); return Object.freeze(reports.map(requireReport)); }
function mergedState(reports) { if (reports.length === 0) return 'insufficient-data'; if (reports.some((report) => report.state === 'risk-unknown')) return 'risk-unknown'; if (reports.some((report) => report.state === 'observation-required')) return 'observation-required'; if (reports.some((report) => report.state === 'destructive-risk-sustained')) return 'destructive-risk-sustained'; if (reports.some((report) => report.state === 'destructive-risk-observed')) return 'destructive-risk-observed'; if (reports.some((report) => report.state === 'destructive-proposal')) return 'destructive-proposal'; if (reports.some((report) => report.state === 'proposal-review')) return 'proposal-review'; if (reports.every((report) => report.state === 'insufficient-data')) return 'insufficient-data'; return 'no-proposal'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-proposal-evidence']); if (state === 'risk-unknown') return Object.freeze(['request-proposal-risk-evidence']); if (state === 'observation-required') return Object.freeze(['request-complete-proposal-observation']); if (state === 'destructive-risk-sustained') return Object.freeze(['reject-destructive-proposal']); if (state === 'destructive-risk-observed') return Object.freeze(['review-destructive-proposal']); if (state === 'destructive-proposal') return Object.freeze(['require-explicit-review-before-action']); if (state === 'proposal-review') return Object.freeze(['review-proposal-without-execution']); return Object.freeze(['no-action-review']); }
function environmentOf(value) { return ENVIRONMENTS.includes(value) ? value : 'unknown'; }
function planMode(state, environment) { if (environment === 'unknown') return 'profile-required'; if (state === 'risk-unknown' || state === 'observation-required') return 'evidence-bootstrap'; if (state === 'destructive-risk-sustained') return 'destructive-risk-review'; if (state === 'destructive-risk-observed') return 'destructive-risk-observation'; if (state === 'destructive-proposal') return 'destructive-review'; if (state === 'proposal-review') return 'proposal-review'; if (state === 'insufficient-data') return 'sample-bootstrap'; return 'no-action-observation'; }
function intervalFor(state, environment) { if (state === 'risk-unknown' || state === 'observation-required' || state === 'insufficient-data') return 2000; if (state === 'destructive-risk-sustained') return 750; if (state === 'destructive-risk-observed') return 1000; if (state === 'destructive-proposal' || state === 'proposal-review') return 2500; return environment === 'headless' ? 10000 : 5000; }
export function mergeSafetyProposalRiskReports(reports) { const validated = requireReports(reports); const state = mergedState(validated); const latest = validated.at(-1); return Object.freeze({ library: SAFETY_PROPOSAL_RISK_LIBRARY_ID, libraryVersion: SAFETY_PROPOSAL_RISK_LIBRARY_VERSION, reportCount: validated.length, state, sampleCount: validated.reduce((sum, report) => sum + report.sampleCount, 0), observedCount: validated.reduce((sum, report) => sum + report.observedCount, 0), unknownCount: validated.reduce((sum, report) => sum + report.unknownCount, 0), comparisonCount: validated.reduce((sum, report) => sum + report.comparisonCount, 0), changeCount: validated.reduce((sum, report) => sum + report.changeCount, 0), actionChangeCount: validated.reduce((sum, report) => sum + report.actionChangeCount, 0), destructiveChangeCount: validated.reduce((sum, report) => sum + report.destructiveChangeCount, 0), finalEnvironment: latest?.finalEnvironment || 'unknown', finalActionCount: latest?.finalActionCount ?? null, finalDestructiveCount: latest?.finalDestructiveCount ?? null, confidence: latest?.confidence || 0, recommendations: recommendations(state) }); }
export function buildSafetyProposalRiskPlan(report, environment) { const validated = requireReport(report); const normalizedEnvironment = environmentOf(environment); return Object.freeze({ library: SAFETY_PROPOSAL_RISK_LIBRARY_ID, environment: normalizedEnvironment, mode: planMode(validated.state, normalizedEnvironment), intervalMs: intervalFor(validated.state, normalizedEnvironment), state: validated.state, confidence: validated.sampleCount === 0 ? 0 : validated.confidence }); }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Proposal-risk library clock must return a number'); return timestamp; }
export function buildSafetyProposalRiskEnvelope(report, { trigger, now = Date.now } = {}) { if (typeof trigger !== 'string' || trigger.length === 0) throw new TypeError('Proposal-risk library trigger is required'); return Object.freeze({ library: SAFETY_PROPOSAL_RISK_LIBRARY_ID, libraryVersion: SAFETY_PROPOSAL_RISK_LIBRARY_VERSION, trigger, generatedAt: new Date(requireClock(now)).toISOString(), report: requireReport(report) }); }
export function createSafetyProposalRiskLibrary() { return Object.freeze({ id: SAFETY_PROPOSAL_RISK_LIBRARY_ID, version: SAFETY_PROPOSAL_RISK_LIBRARY_VERSION, merge: mergeSafetyProposalRiskReports, plan: buildSafetyProposalRiskPlan, envelope: buildSafetyProposalRiskEnvelope }); }
