/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Safety-audit proposal-risk turbo. It classifies explicit action and
 * destructive-action counts without executing any proposed action.
 */
export const SAFETY_PROPOSAL_RISK_TURBO_ID = 'safety-audit.proposal-risk';
export const SAFETY_PROPOSAL_RISK_TURBO_VERSION = 1;
export const SAFETY_PROPOSAL_RISK_TRIGGERS = Object.freeze(['install.preflight', 'system.facts.request', 'workload.changed', 'health.interval']);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']); const EMPTY_ARRAY = Object.freeze([]);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function nonNegative(value) { return Number.isFinite(value) && value >= 0 ? value : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Safety-audit proposal-risk snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Safety-audit proposal-risk requires a system-facts snapshot'); if (!isRecord(snapshot.audit)) throw new TypeError('Safety-audit proposal-risk snapshot requires an audit object'); return snapshot; }
function evidenceOf(snapshot) { const source = requireSnapshot(snapshot); const actionCount = nonNegative(source.audit.actionCount); const destructiveCount = nonNegative(source.audit.destructiveCount); return Object.freeze({ environment: ENVIRONMENTS.includes(source.environment) ? source.environment : 'unknown', actionCount, destructiveCount, observed: actionCount !== null && destructiveCount !== null, signature: `${actionCount === null ? '?' : actionCount}:${destructiveCount === null ? '?' : destructiveCount}` }); }
function requireTrigger(trigger) { if (!SAFETY_PROPOSAL_RISK_TRIGGERS.includes(trigger)) throw new Error(`Unsupported safety-audit proposal-risk trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindow(value) { if (!Number.isInteger(value) || value < 2 || value > 64) throw new RangeError('Safety-audit proposal-risk windowSize must be an integer from 2 to 64'); return value; }
function requireMinimum(value, windowSize) { if (!Number.isInteger(value) || value < 1 || value > windowSize) throw new RangeError('Safety-audit proposal-risk minimumSamples must fit inside the window'); return value; }
function requireThreshold(value, windowSize) { if (!Number.isInteger(value) || value < 1 || value > windowSize) throw new RangeError('Safety-audit proposal-risk persistenceThreshold must fit inside the window'); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Safety-audit proposal-risk clock must return a number'); return timestamp; }
function stateFor(sampleCount, minimumSamples, observedCount, unknownCount, changeCount, persistenceThreshold, finalActions, finalDestructive) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (observedCount === 0) return 'risk-unknown'; if (unknownCount > 0) return 'observation-required'; if (finalDestructive > 0 && changeCount >= persistenceThreshold) return 'destructive-risk-sustained'; if (finalDestructive > 0 && changeCount > 0) return 'destructive-risk-observed'; if (finalDestructive > 0) return 'destructive-proposal'; if (finalActions > 0) return 'proposal-review'; return 'no-proposal'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-proposal-evidence']); if (state === 'risk-unknown') return Object.freeze(['request-proposal-risk-evidence']); if (state === 'observation-required') return Object.freeze(['request-complete-proposal-observation']); if (state === 'destructive-risk-sustained') return Object.freeze(['reject-destructive-proposal']); if (state === 'destructive-risk-observed') return Object.freeze(['review-destructive-proposal']); if (state === 'destructive-proposal') return Object.freeze(['require-explicit-review-before-action']); if (state === 'proposal-review') return Object.freeze(['review-proposal-without-execution']); return Object.freeze(['no-action-review']); }
export function runSafetyProposalRiskTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Safety-audit proposal-risk samples must be an array'); const boundedWindow = requireWindow(windowSize); const requiredSamples = requireMinimum(minimumSamples, boundedWindow); const requiredPersistence = requireThreshold(persistenceThreshold, boundedWindow); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = selected.map(evidenceOf); const changes = evidence.slice(1).map((current, index) => Object.freeze({ changed: current.signature !== evidence[index].signature, actionChanged: current.actionCount !== evidence[index].actionCount, destructiveChanged: current.destructiveCount !== evidence[index].destructiveCount })); const observedCount = evidence.filter((item) => item.observed).length; const unknownCount = evidence.length - observedCount; const changeCount = changes.filter((item) => item.changed).length; const latest = evidence.length === 0 ? null : evidence[evidence.length - 1]; const state = stateFor(selected.length, requiredSamples, observedCount, unknownCount, changeCount, requiredPersistence, latest ? latest.actionCount : 0, latest ? latest.destructiveCount : 0); return Object.freeze({ protocolVersion: 1, turbo: SAFETY_PROPOSAL_RISK_TURBO_ID, turboVersion: SAFETY_PROPOSAL_RISK_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, observedCount, unknownCount, comparisonCount: changes.length, changeCount, actionChangeCount: changes.filter((item) => item.actionChanged).length, destructiveChangeCount: changes.filter((item) => item.destructiveChanged).length, finalEnvironment: latest ? latest.environment : 'unknown', finalActionCount: latest ? latest.actionCount : null, finalDestructiveCount: latest ? latest.destructiveCount : null, state, confidence: selected.length === 0 ? 0 : Math.round((observedCount / selected.length) * 10000) / 10000, recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
