/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Version-churn turbo. It compares bounded driver version observations without
 * installing, replacing, loading, or changing drivers.
 */

export const DRIVER_CAPABILITY_VERSION_CHURN_TURBO_ID = 'driver-capability.version-churn';
export const DRIVER_CAPABILITY_VERSION_CHURN_TURBO_VERSION = 1;
export const DRIVER_CAPABILITY_VERSION_CHURN_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function identityOf(driver) { const name = text(driver.name); const vendor = text(driver.vendor); const version = text(driver.version); return Object.freeze({ key: name && vendor ? `${vendor}|${name}` : null, version }); }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Version-churn snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Version-churn requires a system-facts snapshot'); if (!Array.isArray(snapshot.drivers)) throw new TypeError('Version-churn snapshot requires a driver list'); return snapshot; }
function requireTrigger(trigger) { if (!DRIVER_CAPABILITY_VERSION_CHURN_TRIGGERS.includes(trigger)) throw new Error(`Unsupported version-churn trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Version-churn windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Version-churn minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Version-churn ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Version-churn clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot, previous) { const source = requireSnapshot(snapshot); const rows = source.drivers.filter(isRecord).map(identityOf); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', driverCount: rows.length, comparisonCount: 0, versionChangeCount: 0, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-drivers', driverCount: 0, comparisonCount: 0, versionChangeCount: 0, review: false }); if (rows.some((row) => row.key === null || row.version === null)) return Object.freeze({ state: 'incomplete', driverCount: rows.length, comparisonCount: 0, versionChangeCount: 0, review: false }); const previousRows = previous?.rows || []; const previousMap = new Map(previousRows.map((row) => [row.key, row.version])); const versionChangeCount = previous?.state === 'observed' ? rows.filter((row) => previousMap.get(row.key) !== undefined && previousMap.get(row.key) !== row.version).length : 0; return Object.freeze({ state: 'observed', driverCount: rows.length, comparisonCount: previous?.state === 'observed' ? 1 : 0, versionChangeCount, review: versionChangeCount > 0, rows }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, changeSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-drivers')) return 'no-drivers'; if (incompleteCount > 0) return 'incomplete-evidence'; if (changeSampleCount >= persistenceThreshold) return 'version-churn-sustained'; if (changeSampleCount > 0) return 'version-churn-observed'; return 'stable-versions'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-driver-versions']); if (state === 'no-drivers') return Object.freeze(['no-driver-version-review']); if (state === 'incomplete-evidence') return Object.freeze(['request-driver-version-evidence']); if (state === 'version-churn-sustained') return Object.freeze(['review-driver-version-churn-without-change']); if (state === 'version-churn-observed') return Object.freeze(['observe-driver-version-stability']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runDriverCapabilityVersionChurnTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Version-churn samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = []; let previous; for (const sample of selected) { const current = aggregate(sample, previous); evidence.push(current); previous = current; } const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noDriverCount = evidence.filter((item) => item.state === 'no-drivers').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const comparisonCount = evidence.reduce((sum, item) => sum + item.comparisonCount, 0); const versionChangeSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const versionChangeCount = evidence.at(-1)?.versionChangeCount || 0; const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, versionChangeSampleCount, requiredPersistence); const latest = evidence.at(-1) || Object.freeze({ driverCount: 0 }); return Object.freeze({ protocolVersion: 1, turbo: DRIVER_CAPABILITY_VERSION_CHURN_TURBO_ID, turboVersion: DRIVER_CAPABILITY_VERSION_CHURN_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, driverCount: latest.driverCount, observedCount, incompleteCount, noDriverCount, comparisonCount, versionChangeCount, versionChangeSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
