/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Interface-inventory turbo. It compares explicit interface identities without
 * changing interfaces, routes, or network settings.
 */

export const NETWORK_OBSERVATION_INTERFACE_INVENTORY_TURBO_ID = 'network-observation.interface-inventory';
export const NETWORK_OBSERVATION_INTERFACE_INVENTORY_TURBO_VERSION = 1;
export const NETWORK_OBSERVATION_INTERFACE_INVENTORY_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function identityOf(link) { const name = text(link.name); const kind = text(link.kind); return name && kind ? `${kind}|${name}` : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Interface-inventory snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Interface-inventory requires a system-facts snapshot'); if (!Array.isArray(snapshot.network)) throw new TypeError('Interface-inventory snapshot requires a network list'); return snapshot; }
function requireTrigger(trigger) { if (!NETWORK_OBSERVATION_INTERFACE_INVENTORY_TRIGGERS.includes(trigger)) throw new Error(`Unsupported interface-inventory trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Interface-inventory windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Interface-inventory minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Interface-inventory ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Interface-inventory clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot, previous) { const source = requireSnapshot(snapshot); const rows = source.network.filter(isRecord); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', linkCount: rows.length, addedCount: 0, removedCount: 0, inventoryChangeCount: 0, comparisonCount: 0, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-network', linkCount: 0, addedCount: 0, removedCount: 0, inventoryChangeCount: 0, comparisonCount: 0, review: false }); const identities = rows.map(identityOf); if (identities.some((identity) => identity === null)) return Object.freeze({ state: 'incomplete', linkCount: rows.length, addedCount: 0, removedCount: 0, inventoryChangeCount: 0, comparisonCount: 0, review: false }); const unique = new Set(identities); const previousIdentities = previous?.identities || new Set(); const comparable = previous?.state === 'observed'; const addedCount = comparable ? [...unique].filter((identity) => !previousIdentities.has(identity)).length : 0; const removedCount = comparable ? [...previousIdentities].filter((identity) => !unique.has(identity)).length : 0; const inventoryChangeCount = addedCount + removedCount; return Object.freeze({ state: 'observed', linkCount: unique.size, addedCount, removedCount, inventoryChangeCount, comparisonCount: comparable ? 1 : 0, review: inventoryChangeCount > 0, identities: unique }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, changeSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-network')) return 'no-network'; if (incompleteCount > 0) return 'incomplete-evidence'; if (changeSampleCount >= persistenceThreshold) return 'interface-drift-sustained'; if (changeSampleCount > 0) return 'interface-drift-observed'; return 'stable-interface-inventory'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-interface-inventory']); if (state === 'no-network') return Object.freeze(['no-network-interface-review']); if (state === 'incomplete-evidence') return Object.freeze(['request-interface-identity-evidence']); if (state === 'interface-drift-sustained') return Object.freeze(['review-interface-inventory-drift-without-network-mutation']); if (state === 'interface-drift-observed') return Object.freeze(['observe-interface-inventory-stability']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runNetworkObservationInterfaceInventoryTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Interface-inventory samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = []; let previous; for (const sample of selected) { const current = aggregate(sample, previous); evidence.push(current); previous = current; } const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noNetworkCount = evidence.filter((item) => item.state === 'no-network').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const comparisonCount = evidence.reduce((sum, item) => sum + item.comparisonCount, 0); const inventoryChangeSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const latest = evidence.at(-1) || Object.freeze({ linkCount: 0, addedCount: 0, removedCount: 0, inventoryChangeCount: 0 }); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, inventoryChangeSampleCount, requiredPersistence); return Object.freeze({ protocolVersion: 1, turbo: NETWORK_OBSERVATION_INTERFACE_INVENTORY_TURBO_ID, turboVersion: NETWORK_OBSERVATION_INTERFACE_INVENTORY_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, linkCount: latest.linkCount, addedCount: latest.addedCount, removedCount: latest.removedCount, inventoryChangeCount: latest.inventoryChangeCount, observedCount, incompleteCount, noNetworkCount, comparisonCount, inventoryChangeSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
