/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Category-drift turbo. It compares bounded organization categories without
 * moving, renaming, deleting, overwriting, or inspecting files.
 */

export const ORGANIZATION_PREVIEW_CATEGORY_DRIFT_TURBO_ID = 'organization-preview.category-drift';
export const ORGANIZATION_PREVIEW_CATEGORY_DRIFT_TURBO_VERSION = 1;
export const ORGANIZATION_PREVIEW_CATEGORY_DRIFT_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const CATEGORIES = Object.freeze(['documents', 'media', 'downloads', 'projects', 'archive']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function categoryOf(value) { if (typeof value !== 'string' || value.trim().length === 0) return 'unknown'; const normalized = value.trim().toLowerCase(); return CATEGORIES.includes(normalized) ? normalized : 'unknown'; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Category-drift snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Category-drift requires a system-facts snapshot'); if (!isRecord(snapshot.organization)) throw new TypeError('Category-drift snapshot requires an organization object'); if (!Array.isArray(snapshot.organization.items)) throw new TypeError('Category-drift snapshot requires an organization item list'); return snapshot; }
function requireTrigger(trigger) { if (!ORGANIZATION_PREVIEW_CATEGORY_DRIFT_TRIGGERS.includes(trigger)) throw new Error(`Unsupported category-drift trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Category-drift windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Category-drift minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Category-drift ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Category-drift clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot, previous) { const source = requireSnapshot(snapshot); const rows = source.organization.items.filter(isRecord).map((item) => ({ key: text(item.name) || 'unnamed', category: categoryOf(item.category) })); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', itemCount: rows.length, unknownCategoryCount: rows.filter((row) => row.category === 'unknown').length, categoryChangeCount: 0, comparisonCount: 0, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-organization-preview', itemCount: 0, unknownCategoryCount: 0, categoryChangeCount: 0, comparisonCount: 0, review: false }); const unknownCategoryCount = rows.filter((row) => row.category === 'unknown').length; if (unknownCategoryCount > 0) return Object.freeze({ state: 'incomplete', itemCount: rows.length, unknownCategoryCount, categoryChangeCount: 0, comparisonCount: 0, review: false }); const previousRows = previous?.rows || []; const previousMap = new Map(previousRows.map((row) => [row.key, row.category])); const comparable = previous?.state === 'observed'; const categoryChangeCount = comparable ? rows.filter((row) => previousMap.get(row.key) !== undefined && previousMap.get(row.key) !== row.category).length : 0; return Object.freeze({ state: 'observed', itemCount: rows.length, unknownCategoryCount: 0, categoryChangeCount, comparisonCount: comparable ? 1 : 0, review: categoryChangeCount > 0, rows }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, changeSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-organization-preview')) return 'no-organization-preview'; if (incompleteCount > 0) return 'incomplete-evidence'; if (changeSampleCount >= persistenceThreshold) return 'category-drift-sustained'; if (changeSampleCount > 0) return 'category-drift-observed'; return 'stable-categories'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-organization-categories']); if (state === 'no-organization-preview') return Object.freeze(['no-organization-preview']); if (state === 'incomplete-evidence') return Object.freeze(['request-organization-category-observation']); if (state === 'category-drift-sustained') return Object.freeze(['review-category-drift-without-file-mutation']); if (state === 'category-drift-observed') return Object.freeze(['observe-category-stability']); return Object.freeze(['preview-proposals-only']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runOrganizationPreviewCategoryDriftTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Category-drift samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = []; let previous; for (const sample of selected) { const current = aggregate(sample, previous); evidence.push(current); previous = current; } const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noOrganizationCount = evidence.filter((item) => item.state === 'no-organization-preview').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const comparisonCount = evidence.reduce((sum, item) => sum + item.comparisonCount, 0); const categoryChangeSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const latest = evidence.at(-1) || Object.freeze({ itemCount: 0, unknownCategoryCount: 0, categoryChangeCount: 0 }); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, categoryChangeSampleCount, requiredPersistence); return Object.freeze({ protocolVersion: 1, turbo: ORGANIZATION_PREVIEW_CATEGORY_DRIFT_TURBO_ID, turboVersion: ORGANIZATION_PREVIEW_CATEGORY_DRIFT_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, itemCount: latest.itemCount, unknownCategoryCount: latest.unknownCategoryCount, categoryChangeCount: latest.categoryChangeCount, observedCount, incompleteCount, noOrganizationCount, comparisonCount, categoryChangeSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
