/**
 * RNK Vortex System Optimizer
 * Contributor: Lisa's Dungeon
 *
 * Ownership-review turbo. It reports explicit user-owned evidence without
 * moving, renaming, deleting, overwriting, or inspecting files.
 */

export const ORGANIZATION_PREVIEW_OWNERSHIP_REVIEW_TURBO_ID = 'organization-preview.ownership-review';
export const ORGANIZATION_PREVIEW_OWNERSHIP_REVIEW_TURBO_VERSION = 1;
export const ORGANIZATION_PREVIEW_OWNERSHIP_REVIEW_TRIGGERS = Object.freeze([
  'install.preflight', 'system.facts.request', 'workload.changed', 'health.interval'
]);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']);
const EMPTY_ARRAY = Object.freeze([]);

function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function text(value) { return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null; }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Ownership-review snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Ownership-review requires a system-facts snapshot'); if (!isRecord(snapshot.organization)) throw new TypeError('Ownership-review snapshot requires an organization object'); if (!Array.isArray(snapshot.organization.items)) throw new TypeError('Ownership-review snapshot requires an organization item list'); return snapshot; }
function requireTrigger(trigger) { if (!ORGANIZATION_PREVIEW_OWNERSHIP_REVIEW_TRIGGERS.includes(trigger)) throw new Error(`Unsupported ownership-review trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Ownership-review windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Ownership-review minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Ownership-review ${name} must be an integer from 1 to 64`); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Ownership-review clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot) { const source = requireSnapshot(snapshot); const rows = source.organization.items.filter(isRecord).map((item) => ({ key: text(item.name) || 'unnamed', owned: typeof item.userOwned === 'boolean' ? item.userOwned : null })); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', itemCount: rows.length, userOwnedCount: rows.filter((row) => row.owned === true).length, unknownOwnershipCount: rows.filter((row) => row.owned === null).length, review: false }); if (rows.length === 0) return Object.freeze({ state: 'no-organization-preview', itemCount: 0, userOwnedCount: 0, unknownOwnershipCount: 0, review: false }); const unknownOwnershipCount = rows.filter((row) => row.owned === null).length; if (unknownOwnershipCount > 0) return Object.freeze({ state: 'incomplete', itemCount: rows.length, userOwnedCount: rows.filter((row) => row.owned === true).length, unknownOwnershipCount, review: false }); const userOwnedCount = rows.filter((row) => row.owned === true).length; return Object.freeze({ state: 'observed', itemCount: rows.length, userOwnedCount, unknownOwnershipCount: 0, review: userOwnedCount > 0 }); }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, ownedSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-organization-preview')) return 'no-organization-preview'; if (incompleteCount > 0) return 'incomplete-evidence'; if (ownedSampleCount >= persistenceThreshold) return 'ownership-review-sustained'; if (ownedSampleCount > 0) return 'ownership-review-observed'; return 'no-user-owned-items'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-ownership-evidence']); if (state === 'no-organization-preview') return Object.freeze(['no-organization-preview']); if (state === 'incomplete-evidence') return Object.freeze(['request-explicit-ownership-evidence']); if (state === 'ownership-review-sustained') return Object.freeze(['request-explicit-organization-approval']); if (state === 'ownership-review-observed') return Object.freeze(['observe-user-owned-review-boundary']); return Object.freeze(['preview-proposals-only']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }

export function runOrganizationPreviewOwnershipReviewTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, persistenceThreshold = 2, now = Date.now } = {}) { requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Ownership-review samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = selected.map(aggregate); const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noOrganizationCount = evidence.filter((item) => item.state === 'no-organization-preview').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const ownedSampleCount = evidence.filter((item) => item.state === 'observed' && item.review).length; const latest = evidence.at(-1) || Object.freeze({ itemCount: 0, userOwnedCount: 0, unknownOwnershipCount: 0 }); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, ownedSampleCount, requiredPersistence); return Object.freeze({ protocolVersion: 1, turbo: ORGANIZATION_PREVIEW_OWNERSHIP_REVIEW_TURBO_ID, turboVersion: ORGANIZATION_PREVIEW_OWNERSHIP_REVIEW_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, persistenceThreshold: requiredPersistence, itemCount: latest.itemCount, userOwnedCount: latest.userOwnedCount, unknownOwnershipCount: latest.unknownOwnershipCount, observedCount, incompleteCount, noOrganizationCount, ownedSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY }); }
