/**
 * RNK Vortex System Optimizer
 * Contributor: RNK Enterprise
 *
 * Wait-trend turbo. It observes bounded adjacent I/O-wait movement without
 * changing queues, services, mounts, files, or transport state.
 */

export const DISK_IO_WAIT_TREND_TURBO_ID = 'disk-io.wait-trend';
export const DISK_IO_WAIT_TREND_TURBO_VERSION = 1;
export const DISK_IO_WAIT_TREND_TRIGGERS = Object.freeze(['install.preflight', 'system.facts.request', 'workload.changed', 'health.interval']);
const ENVIRONMENTS = Object.freeze(['interactive', 'headless', 'unknown']); const EMPTY_ARRAY = Object.freeze([]);
function isRecord(value) { return Boolean(value) && typeof value === 'object' && !Array.isArray(value); }
function percent(value) { if (!Number.isFinite(value)) return null; return Math.min(100, Math.max(0, value)); }
function requireSnapshot(snapshot) { if (!isRecord(snapshot)) throw new TypeError('Wait-trend snapshot must be an object'); if (snapshot.engine !== 'system-facts') throw new Error('Wait-trend requires a system-facts snapshot'); if (!Array.isArray(snapshot.storage)) throw new TypeError('Wait-trend snapshot requires a storage list'); return snapshot; }
function requireTrigger(trigger) { if (!DISK_IO_WAIT_TREND_TRIGGERS.includes(trigger)) throw new Error(`Unsupported wait-trend trigger: ${trigger || 'unknown'}`); return trigger; }
function requireWindowSize(value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError('Wait-trend windowSize must be an integer from 1 to 64'); return value; }
function requireMinimumSamples(value, size) { if (!Number.isInteger(value) || value < 1 || value > size) throw new RangeError('Wait-trend minimumSamples must fit inside the window'); return value; }
function requireCount(name, value) { if (!Number.isInteger(value) || value < 1 || value > 64) throw new RangeError(`Wait-trend ${name} must be an integer from 1 to 64`); return value; }
function requireThreshold(value) { if (!Number.isFinite(value) || value < 0 || value > 100) throw new RangeError('Wait-trend increaseThreshold must be between 0 and 100'); return value; }
function requireClock(now) { const timestamp = now(); if (!Number.isFinite(timestamp)) throw new TypeError('Wait-trend clock must return a number'); return timestamp; }
function environmentKnown(snapshot) { return ENVIRONMENTS.includes(snapshot.environment) && snapshot.environment !== 'unknown'; }
function aggregate(snapshot) { const source = requireSnapshot(snapshot); const rows = source.storage.filter(isRecord).map((item) => percent(item.ioWaitPercent)); if (!environmentKnown(source)) return Object.freeze({ state: 'incomplete', diskCount: rows.length, maximumWaitPercent: null }); if (rows.length === 0) return Object.freeze({ state: 'no-disks', diskCount: 0, maximumWaitPercent: null }); if (rows.some((value) => value === null)) return Object.freeze({ state: 'incomplete', diskCount: rows.length, maximumWaitPercent: null }); return Object.freeze({ state: 'observed', diskCount: rows.length, maximumWaitPercent: Math.max(...rows) }); }
function increaseSamples(evidence, increaseThreshold) { let count = 0; for (let index = 1; index < evidence.length; index += 1) { const before = evidence[index - 1]; const current = evidence[index]; if (before.state === 'observed' && current.state === 'observed' && current.maximumWaitPercent - before.maximumWaitPercent >= increaseThreshold) count += 1; } return count; }
function stateFor(sampleCount, minimumSamples, evidence, incompleteCount, increaseSampleCount, persistenceThreshold) { if (sampleCount < minimumSamples) return 'insufficient-data'; if (evidence.some((item) => item.state === 'no-disks')) return 'no-disks'; if (incompleteCount > 0) return 'incomplete-trend-evidence'; if (increaseSampleCount >= persistenceThreshold) return 'wait-increase-sustained'; if (increaseSampleCount > 0) return 'wait-increase-observed'; return 'stable-wait-trend'; }
function recommendations(state) { if (state === 'insufficient-data') return Object.freeze(['collect-more-wait-trend-samples']); if (state === 'no-disks') return Object.freeze(['no-disk-io-review']); if (state === 'incomplete-trend-evidence') return Object.freeze(['request-wait-observation']); if (state === 'wait-increase-sustained') return Object.freeze(['review-contention-trend', 'protect-services']); if (state === 'wait-increase-observed') return Object.freeze(['observe-next-wait-trend']); return Object.freeze(['no-change']); }
function confidence(sampleCount, observedCount, minimumSamples) { if (sampleCount === 0) return 0; return Math.round((observedCount / sampleCount) * Math.min(1, sampleCount / minimumSamples) * 10000) / 10000; }
export function runDiskIoWaitTrendTurbo(samples = [], { trigger, windowSize = 16, minimumSamples = 2, increaseThreshold = 5, persistenceThreshold = 2, now = Date.now } = {}) {
  requireTrigger(trigger); if (!Array.isArray(samples)) throw new TypeError('Wait-trend samples must be an array'); const boundedWindow = requireWindowSize(windowSize); const requiredSamples = requireMinimumSamples(minimumSamples, boundedWindow); const requiredThreshold = requireThreshold(increaseThreshold); const requiredPersistence = requireCount('persistenceThreshold', persistenceThreshold); const selected = samples.slice(-boundedWindow); const timestamp = requireClock(now); const evidence = selected.map(aggregate); const incompleteCount = evidence.filter((item) => item.state === 'incomplete').length; const noDiskCount = evidence.filter((item) => item.state === 'no-disks').length; const observedCount = evidence.filter((item) => item.state === 'observed').length; const increaseSampleCount = increaseSamples(evidence, requiredThreshold); const state = stateFor(selected.length, requiredSamples, evidence, incompleteCount, increaseSampleCount, requiredPersistence); const latest = evidence.at(-1) || Object.freeze({ diskCount: 0, maximumWaitPercent: null }); return Object.freeze({ protocolVersion: 1, turbo: DISK_IO_WAIT_TREND_TURBO_ID, turboVersion: DISK_IO_WAIT_TREND_TURBO_VERSION, trigger, generatedAt: new Date(timestamp).toISOString(), sampleCount: selected.length, minimumSamples: requiredSamples, increaseThreshold: requiredThreshold, persistenceThreshold: requiredPersistence, diskCount: latest.diskCount, maximumWaitPercent: latest.maximumWaitPercent, observedCount, incompleteCount, noDiskCount, increaseSampleCount, state, confidence: confidence(selected.length, observedCount, requiredSamples), recommendations: recommendations(state), actions: EMPTY_ARRAY });
}
